In [2]:
from datasets import load_dataset
from transformers import AutoTokenizer
import matplotlib.pyplot as plt
import pandas as pd
from ast import literal_eval


pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [1]:
import glob
import pandas as pd
import os

file_list = glob.glob('./data/220-1.관광 KVQA 데이터(동부권)/01-1.정식개방데이터/Training/01.원천데이터/TS_트리플_동부권_부산_레포츠/*.csv')

rows = []

for file_path in file_list:
    try:
        temp_df = pd.read_csv(file_path, encoding='utf-8')
        row_dict = temp_df.set_index('관광타입')['레포츠'].to_dict()
        rows.append(row_dict)
    except Exception as e:
        print(f"Error parsing {file_path}: {e}")

df = pd.DataFrame(rows)

cols = ['시설명'] + [c for c in df.columns if c not in ['시설명']]
df = df[cols]

print(f"총 {len(df)}개의 데이터가 정리되었습니다.")
df.head()

총 1321개의 데이터가 정리되었습니다.

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
0,바디로운필라테스,기구필라테스 체형교정 전문센터 바디로운필라테스 2호점 덕천점 입니다 많은 회원님들...,부산 북구 만덕대로27번길 3 세빈빌딩 8층 바디로운 필라테스,부산 북구 만덕대로27번길 3,부산 북구 덕천동 398-4,0507-1451-1026,09:00 - 22:00,"매주 토요일, 공휴일",전화문의,있음,없음,"친절해요, 자세를 꼼꼼히 봐주세요, 시설이 깔끔해요, 수업이 체계적이에요, 상담이 ..."
1,국제기구필라테스 망미점,부산 수영구 망미동에 위치한 국제기구필라테스 망미점입니다. 강사님과 단둘이 진행하는...,부산 수영구 과정로 63 6층,부산 수영구 과정로 63,부산 수영구 망미동 432-22,051-761-1138,09:00~22:00,"매주 토요일, 일요일, 공휴일",전화문의,있음,필라테스,없음
2,모션업PT 양정점,양정역 3번 출구에서 인접해 있습니다.,부산 부산진구 동평로 412 6층 모션업PT,부산 부산진구 동평로 412,부산 부산진구 양정동 370-2,0507-1351-4857,06:00 - 24:00,없음,전화문의,있음,없음,없음
3,알통클럽 엄궁점,"엄궁최대규모로 헬스,GX, 1대1PT, 그룹PT 등 다양한프로그램을 진행하고 있으며...",부산 사상구 낙동대로 751 동일메가타워 7층 알통클럽 엄궁점,부산 사상구 낙동대로 751,부산 사상구 엄궁동 376-1,051-317-2999,06:00 - 19:00/23:00,전화문의,전화문의,있음,"PT, GX",없음
4,클럽S휘트니스,"GX 스피닝, 플라잉요가, 필라테스, 줌바, 요가 보다 전문적이고 보다 친근한 강사...",부산 해운대구 좌동순환로 175 대하프라자 2층,부산 해운대구 좌동순환로 175,부산 해운대구 좌동 1407-3,0507-1322-9966,09:00 - 14:00/23:00,매주 일요일,전화문의,있음,헬스,"친절해요, GX프로그램이 다양해요, 가격이 합리적이에요, 상담이 자세해요, 시설이 ..."

In [2]:
# 부산
df = df[df['주소'].str.contains('부산', na=False)]

print(f"{len(df)}")
df.head()

1321

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
0,바디로운필라테스,기구필라테스 체형교정 전문센터 바디로운필라테스 2호점 덕천점 입니다 많은 회원님들...,부산 북구 만덕대로27번길 3 세빈빌딩 8층 바디로운 필라테스,부산 북구 만덕대로27번길 3,부산 북구 덕천동 398-4,0507-1451-1026,09:00 - 22:00,"매주 토요일, 공휴일",전화문의,있음,없음,"친절해요, 자세를 꼼꼼히 봐주세요, 시설이 깔끔해요, 수업이 체계적이에요, 상담이 ..."
1,국제기구필라테스 망미점,부산 수영구 망미동에 위치한 국제기구필라테스 망미점입니다. 강사님과 단둘이 진행하는...,부산 수영구 과정로 63 6층,부산 수영구 과정로 63,부산 수영구 망미동 432-22,051-761-1138,09:00~22:00,"매주 토요일, 일요일, 공휴일",전화문의,있음,필라테스,없음
2,모션업PT 양정점,양정역 3번 출구에서 인접해 있습니다.,부산 부산진구 동평로 412 6층 모션업PT,부산 부산진구 동평로 412,부산 부산진구 양정동 370-2,0507-1351-4857,06:00 - 24:00,없음,전화문의,있음,없음,없음
3,알통클럽 엄궁점,"엄궁최대규모로 헬스,GX, 1대1PT, 그룹PT 등 다양한프로그램을 진행하고 있으며...",부산 사상구 낙동대로 751 동일메가타워 7층 알통클럽 엄궁점,부산 사상구 낙동대로 751,부산 사상구 엄궁동 376-1,051-317-2999,06:00 - 19:00/23:00,전화문의,전화문의,있음,"PT, GX",없음
4,클럽S휘트니스,"GX 스피닝, 플라잉요가, 필라테스, 줌바, 요가 보다 전문적이고 보다 친근한 강사...",부산 해운대구 좌동순환로 175 대하프라자 2층,부산 해운대구 좌동순환로 175,부산 해운대구 좌동 1407-3,0507-1322-9966,09:00 - 14:00/23:00,매주 일요일,전화문의,있음,헬스,"친절해요, GX프로그램이 다양해요, 가격이 합리적이에요, 상담이 자세해요, 시설이 ..."

In [3]:
# 리뷰 없는 애들 빼기
df = df[df['리뷰키워드'] != '없음'].copy()

df = df[df['리뷰키워드'] != '없음']
df = df[df['리뷰키워드'].str.len() > 5].copy()

print(f"after filtering: {len(df)}")

after filtering: 582

In [4]:
df.sample(5)

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
1092,아더필라테스&플라잉요가 대연점,"아더 필라테스,플라잉요가 대연점입니다. 대연사거리 신협 건물 3층에 있던 아더 대연...",부산 남구 유엔평화로 21 민제빌딩 3층,부산 남구 유엔평화로 21,부산 남구 대연동 888-4,051-612-5978,09:00 - 23:00,"매주 토요일, 공휴일",전화문의,있음,전화문의,"친절해요, 시설이 깔끔해요, 공간이 넓어요, 상담이 자세해요, 수업이 체계적이에요"
1269,온리포원 필라테스,안녕하세요 광안역 6번 출구에 위치한 온리포원 필라테스입니다. 현재 오픈 기념 1 ...,부산 수영구 수영로 569 3층 온리포원 필라테스,부산 수영구 수영로 569,부산 수영구 광안동 744-17,010-4836-1500,07:00~01:00,없음,전화문의,없음,필라테스,"친절해요, 자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 시설이 깔끔해요, 수업이..."
307,필라테스홀릭,6 대 1 소그룹 전문으로 진행 됩니다. 스카이짐 피트니스와 공동운영으로 필라테스홀...,부산 동래구 안남로 108 2층,부산 동래구 안남로 108,부산 동래구 안락동 243-1,0507-1347-5656,09:00~22:00,"매주 토요일, 일요일",전화문의,있음,"필라테스, 기구필라테스","친절해요, 공간이 넓어요, 자세를 꼼꼼히 봐주세요, 상담이 자세해요, 시설이 깔끔해요"
848,무지개휘트니스 대연점&기구필라테스,"개개인에 목적에 따른 전문적인 상담을 통한 고퀄리티 서비스를 해드리며, 경력 높은 ...",부산 남구 수영로 295 세웅빌딩 6층 무지개휘트니스,부산 남구 수영로 295 세웅빌딩 6층 무지개휘트니스,NaN,0507-1441-4445,06:00/08:00~20:00/24:00,매주 일요일,전화문의,있음,"헬스, 필라테스","친절해요, 시설이 깔끔해요, 자세를 꼼꼼히 봐주세요, 기구가 다양해요, 공간이 넓어요"
365,비나이더 헬스 필라 요가 냉정점,회원님들의 변화를 위해 밤낮없이 달리는 고투 냉정점입니다. 운동이 일상의 습관이 되...,"부산 사상구 가야대로 374 신성빌딩 6,7층 고투 냉정점",부산 사상구 가야대로 374,부산 사상구 주례동 60-5,0507-1332-8189,06:00/08:00 - 20:00/23:00,"첫째, 셋째, 다섯째 일요일","요가 99000원, 필라테스 99000원",있음,"요가, 필라테스","친절해요, 자세를 꼼꼼히 봐주세요, 상담이 자세해요, 시설이 깔끔해요, 수업이 체계..."

In [5]:
# 리뷰 길이
df_sorted = df.sort_values(by='리뷰키워드', key=lambda x: x.str.len(), ascending=True)
df_sorted.head(10)

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
132,필라걸 헬스보이짐 구서점,헬스보이짐 구서점 22호점입니다. 구서동헬스장 헬스보이짐 OPEN SALE 진행 중...,부산 금정구 구서로 12 2층,부산 금정구 구서로 12,부산 금정구 구서동 87-9,0507-1363-8189,06:00/10:00 -19:00/24:00,전화문의,전화문의,있음,PT,"친절해요, 시설이 깔끔해요, 상담이 자세해요, 공간이 넓어요, 기구가 다양해요"
300,베스트피트니스 센텀점,"헬스는 이태리 헬스 머신 명품기구 테크노짐, 넓은 프리웨이트존, 웨이트트레이닝 하기...",부산 해운대구 센텀서로 30 케이엔엔타워 3층 베스트 피트니스,부산 해운대구 센텀서로 30,부산 해운대구 우동 1468,0507-1310-6650,06:00/08:00~20:00/24:00,매주 일요일,전화문의,있음,"PT, 헬스, 요가, 필라테스, 줌바, 스피닝","기구가 다양해요, 시설이 깔끔해요, 친절해요, 공간이 넓어요, 주차하기 편해요"
814,더매력짐 기구필라테스,"부곡동, 서동, 온천장 지점입니다. 300평 최대 규모의 부산 24시 헬스장이며 기...",부산 금정구 부곡로 50,부산 금정구 부곡로 50,부산 금정구 부곡동 386-6,0507-1419-6678,06:00/10:00 - 20:00/24:00,전화문의,전화문의,있음,PT,"시설이 깔끔해요, 친절해요, 기구가 다양해요, 공간이 넓어요, 주차하기 편해요"
637,벡스휘트니스,"장산역 13번 출구, 모스버거, 써브웨이가 인접해 있습니다.",부산 해운대구 해운대로 794 퀸즈파크여성병원 9층 901호,부산 해운대구 해운대로 794,부산 해운대구 좌동 1473-2,051-747-0336,06:00/08:00 - 18:00/23:00,"첫째, 셋째 일요일",전화문의,있음,헬스,"친절해요, 시설이 깔끔해요, 기구가 다양해요, 공간이 넓어요, 상담이 자세해요"
1239,상상피트니스 벡스코점,"1300대 가량 주차 가능합니다. 벡스코역 9번 출구, 부산시립미술관, GS25가...",부산 해운대구 APEC로 55 지하1층,부산 해운대구 APEC로 55,부산 해운대구 우동 1500,0507-1392-7960,06:00/08:00 - 20:00/23:00,전화문의,100000원,있음,헬스,"친절해요, 기구가 다양해요, 시설이 깔끔해요, 공간이 넓어요, 상담이 자세해요"
313,달라스짐 광안점,"아름다운 운동의 세계로 여러분을 초대합니다. 진로비치, 신협, 와이모텔, 프렌즈아카...",부산 수영구 광안해변로 292 2층 달라스짐 광안점,부산 수영구 광안해변로 292,부산 수영구 민락동 181-97,0507-1322-7591,07:00/08:00 - 19:00/24:00,매주 일요일,16500원,있음,PT,"기구가 다양해요, 시설이 깔끔해요, 공간이 넓어요, 친절해요, 상담이 자세해요"
1195,어반짐,PT존 스트레칭존 프리웨이트 유산소 공간이 따로 있으며 250평 규모에 최신식 시설...,부산 북구 기찰로 164 3층,부산 북구 기찰로 164,부산 북구 덕천동 370,0507-1306-0053,06:00/09:00 - 18:00/23:00,매주 일요일,전화문의,있음,없음,"시설이 깔끔해요, 기구가 다양해요, 주차하기 편해요, 공간이 넓어요, 친절해요"
1181,탑휘트니스,[문현동 최고의 헬스/PT 전문 운동 센터] 1.100대 이상 주차 가능한 넓은 ...,부산 남구 전포대로 26 삼성힐타워 2층 탑휘트니스,부산 남구 전포대로 26,부산 남구 문현동 383-1,051-633-2147,06:00/10:00 - 19:00/23:00,전화문의,전화문의,있음,없음,"친절해요, 기구가 다양해요, 상담이 자세해요, 시설이 깔끔해요, 공간이 넓어요"
596,커스텀피트니스,서면 최대 규모 프리미엄 헬스장 커스텀 피트니스 회원님의 원하는 바디를 커스텀 해드...,부산 부산진구 전포대로199번길 15 현대오피스텔 지하1층,부산 부산진구 전포대로199번길 15,부산 부산진구 전포동 690-4,0507-1435-7378,06:00/08:00 - 20:00/24:00,없음,1일 입장권 15000원,있음,없음,"시설이 깔끔해요, 친절해요, 기구가 다양해요, 공간이 넓어요, 상담이 자세해요"
950,어나더짐 민락본점,광안리 운동맛집 헬창의 일번지 어나더짐 민락본점입니다. 서희스타힐스센텀프리모오피스텔...,부산 수영구 광안해변로 311 서희스타힐스 센텀프리모 2층 어나더짐민락본점,부산 수영구 광안해변로 311,부산 수영구 민락동 135,0507-1400-8586,00:00 - 24:00,없음,15000원,있음,PT,"기구가 다양해요, 시설이 깔끔해요, 친절해요, 공간이 넓어요, 주차하기 편해요"

In [14]:
# 헬스, pt, 요가, 필라테스 빼기 
keywords = ['헬스', 'pt', '필라테스', '골프', '볼링', '요가', 'CC', '휘트니스', '짐', '피티', '피트니스', '크로스핏', '테니스', 'GYM']
pattern = '|'.join(keywords) 

# 2. 키워드가 포함되지 않은(~) 행만 뽑기
# case=False : 대소문자 무시 (PT, pt, Pt 다 걸러냄)
# na=False   : 혹시 내용이 비어있어도 에러 안 나게 처리
df_filtered = df[~df['시설명'].str.contains(pattern, case=False, na=False)]

df_filtered = df[~df['체험프로그램'].str.contains(pattern, case=False, na=False)]
df_filtered = df[~df['개요'].str.contains(pattern, case=False, na=False)]

df_filtered = df_filtered[~df_filtered['시설명'].str.contains(pattern, case=False, na=False)]

# 결과 확인
print(f"원래 {len(df)}개 -> 필터링 후 {len(df_filtered)}개")
df_filtered.sample(5)

원래 582개 -> 필터링 후 33개

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
613,웨이브락 클라이밍 광안리점,상세한 이용 정보는 웨이브락 공식 홈페이지에서 확인하실 수 있습니다. 광안역 2번출...,부산 수영구 장대골로 41,부산 수영구 장대골로 41,부산 수영구 광안동 569-19,0507-1416-4226,10:00/12:00 - 21:00/22:30,전화문의,전화문의,있음,클라이밍,"친절해요, 시설이 깔끔해요, 문제가 다양해요, 안전하게 관리해요, 공간이 넓어요"
42,부산요트투어 G,동백역 3번 출구가 인접해 있습니다.,부산 해운대구 해운대해변로 84 수영만요트경기장,부산 해운대구 해운대해변로 84 수영만요트경기장,NaN,0507-1350-6087,10:00-23:00,없음,15000원,있음,요트,"뷰가 좋아요, 친절해요, 가격이 합리적이에요, 안전하게 관리해요, 최신 장비를 사용해요"
490,프렌즈스크린,세븐일레븐이 인접해 있습니다.,부산 강서구 명지국제6로 21 플러스시티 5층,부산 강서구 명지국제6로 21,부산 강서구 명지동 3589-9,0507-1399-8852,00:00-24:00,없음,전화문의,있음,없음,"시설이 깔끔해요, 친절해요, 최신 장비를 사용해요, 주차하기 편해요, 가격이 합리적이에요"
69,락오디세이 클라이밍 하단점,"부산클라이밍, 부산실내암벽, 사하구클라이밍, 명지클라이밍입니다. 하단역 9번출구, ...",부산 사하구 낙동대로 498 초이스타워2층,부산 사하구 낙동대로 498,부산 사하구 하단동 510-9,0507-1312-5158,11:00 - 20:00/22:30,전화문의,체험 20000원,있음,클라이밍,"초보자에게도 적합해요, 친절해요, 안전하게 관리해요, 시설이 깔끔해요, 공간이 넓어요"
357,데이핏,데이핏은 체계적인 바디 트레이닝 시스템을 갖춘 퍼스널 트레이닝 전문센터입니다. 가격...,부산 부산진구 서전로 12 3층,부산 부산진구 서전로 12,부산 부산진구 부전동 153-1,0507-1312-1980,09:00-18:00/23:00,매주 일요일,전화문의,없음,없음,"수업이 체계적이에요, 자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 시설이 깔끔해..."

In [15]:
df_filtered

,시설명,개요,주소,주소(도로명),주소(지번주소),대표번호,이용시간,휴무일,입장료/시설이용료,주차시설 유무,체험프로그램,리뷰키워드
42,부산요트투어 G,동백역 3번 출구가 인접해 있습니다.,부산 해운대구 해운대해변로 84 수영만요트경기장,부산 해운대구 해운대해변로 84 수영만요트경기장,NaN,0507-1350-6087,10:00-23:00,없음,15000원,있음,요트,"뷰가 좋아요, 친절해요, 가격이 합리적이에요, 안전하게 관리해요, 최신 장비를 사용해요"
59,클럽스파이더클라이밍,"부산역 바로 옆 영주동에 위치한클럽스파이더 클라이밍 센터입니다. 부산역 1번출구, ...",부산 중구 대영로 224,부산 중구 대영로 224,부산 중구 영주동 565-2,0507-1398-7055,13:00/15:00 - 18:00/22:00,"매주 일요일, 공휴일",일일이용 15000원,없음,클라이밍,"친절해요, 가격이 합리적이에요, 수업이 체계적이에요, 시설이 깔끔해요, 안전하게 관리해요"
69,락오디세이 클라이밍 하단점,"부산클라이밍, 부산실내암벽, 사하구클라이밍, 명지클라이밍입니다. 하단역 9번출구, ...",부산 사하구 낙동대로 498 초이스타워2층,부산 사하구 낙동대로 498,부산 사하구 하단동 510-9,0507-1312-5158,11:00 - 20:00/22:30,전화문의,체험 20000원,있음,클라이밍,"초보자에게도 적합해요, 친절해요, 안전하게 관리해요, 시설이 깔끔해요, 공간이 넓어요"
81,리얼핏 1대1 프라이빗 퍼스널 트레이닝 스튜디오,안녕하세요. 저희 REAL FIT 을 방문해 주셔서 감사드립니다. 저희 리얼핏은 국...,부산 남구 용소로8번길 21 행운빌딩 5층 리얼핏,부산 남구 용소로8번길 21,부산 남구 대연동 68-17,0507-1381-9113,07:00 - 18:00/23:00,매주 일요일,전화문,있음,없음,"자세를 꼼꼼하게 봐주세요, 친절해요, 수업이 체계적이에요, 기구가 다양해요, 상담이..."
128,웨이브락 클라이밍 부산대점,WE SET FUN 웨이브락 클라이밍에 오신 것을 환영합니다. 가장 즐거운 클라이밍...,부산 금정구 장전온천천로 51 테라스파크 2층 201호,부산 금정구 장전온천천로 51,부산 금정구 장전동 643-117,0507-1321-0231,10:00/12:00-21:00/22:30,전화문의,20000원,있음,클라이밍,"시설이 깔끔해요, 친절해요, 안전하게 관리해요, 공간이 넓어요, 문제가 다양해요"
254,팀터틀랫 부산동래점,"팀터틀랫은 마치 거북이 등 근육처럼 단단한 근육질 몸을 뜻하는 의미로, 2014년 ...",부산 동래구 명륜로 125 승풍빌딩 4층,부산 동래구 명륜로 125,부산 동래구 명륜동 505-6,0507-1361-1885,00:00~24:00,없음,전화문의,있음,PT,"친절해요, 시설이 깔끔해요, 가격이 합리적이에요, 기구가 다양해요, 상담이 자세해요"
285,스카이롤러파크,YouTube 스카이롤러파크 Instagram 스카이롤러파크 open 2020. 6...,부산 기장군 정관읍 정관중앙로 45 탑스퀘어빌딩 정관 CGV 12층,부산 기장군 정관읍 정관중앙로 45,부산 기장군 정관읍 매학리 717-6,0507-1441-8942,10:00/12:30-21:00,매주 월요일,"성인 13000원, 소인 11000원",있음,전화문의,"시설이 깔끔해요, 공간이 넓어요, 친절해요, 휴게공간이 잘 되어있어요, 주차하기 편해요"
286,더핏,"뉴텍 핀머신,토크 라인으로 기구세팅 , 3D렉 설치, 천국의계단 스텝밀 , 런닝머신...",부산 남구 신선로 566 상가동 116호,부산 남구 신선로 566,부산 남구 용호동 197,0507-1363-8566,06:00/08:00 - 17:00/23:59,전화문의,전화문의,있음,전화문의,"친절해요, 시설이 깔끔해요, 가격이 합리적이에요, 기구가 다양해요, 자세를 꼼꼼히 ..."
357,데이핏,데이핏은 체계적인 바디 트레이닝 시스템을 갖춘 퍼스널 트레이닝 전문센터입니다. 가격...,부산 부산진구 서전로 12 3층,부산 부산진구 서전로 12,부산 부산진구 부전동 153-1,0507-1312-1980,09:00-18:00/23:00,매주 일요일,전화문의,없음,없음,"수업이 체계적이에요, 자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 시설이 깔끔해..."
409,다인핏,"60평대 규모 1대1 전문, 프리미엄 머신, 최고급 시설, 수건대여, 주차가능합니다...",부산 해운대구 좌동순환로 506 403호,부산 해운대구 좌동순환로 506,부산 해운대구 중동 1766-6,0507-1362-1057,07:00/09:00 - 18:00/23:00,매주 일요일,전화문의,있음,PT,"자세를 꼼꼼히 봐주세요, 수업이 체계적이에요, 시설이 깔끔해요, 친절해요, 맞춤 케..."
420,영롤러스케이트장,"부산 사하구 괴정동에 위치한 아동 실내놀이문화 놀이터로 놀거리, 먹거리, 볼거리 있...",부산 사하구 장평로 440 골드그린빌딩 2층 영롤러스케이트장,부산 사하구 장평로 440,부산 사하구 괴정동 554-5,0507-1372-8855,10:00/13:00-19:00/21:00,전화문의,"대인 15000원, 소인10000원",있음,전화문의,"친절해요, 시설이 깔끔해요, 대여장비 상태가 좋아요, 안전하게 관리해요, 편의시설이..."
433,바름체EMS트레이닝 낙민점,"동래역 2번 출구, 한일유앤아이아파트, 동래구청, 수민동행정복지센터, 우성아파트, ...",부산 동래구 온천천로339번길 28 한일유앤아이아파트 상가 1층 117호,부산 동래구 온천천로339번길 28,부산 동래구 낙민동 77-1,0507-1354-4264,10:00 - 13:00/21:30,매주 일요일,100000원,있음,PT,"시설이 깔끔해요, 자세를 꼼꼼히 봐주세요, 수업이 체계적이에요, 친절해요, 맞춤 케..."
437,몽키몽키롤러장,부산 최대 300여평규모의 롤러장입니다. 커플부터 가족거기다 단체 모임까지 가능한 ...,부산 강서구 명지국제1로 56-1 9층,부산 강서구 명지국제1로 56-1,부산 강서구 명지동 3598-2,051-294-2242,10:00/14:00-20:00/22:00,전화문의,"대인 13000원, 소인 11000원",있음,전화문의,"시설이 깔끔해요, 친절해요, 주차하기 편해요, 공간이 넓어요, 휴게공간이 잘 되어있어요"
445,핏핏바디트레이닝 구서점,"핏핏바디트레이닝만의 특장점 20가지 부산 양산 최초의 프라이빗 퍼스널트레이닝 센터,...",부산 금정구 중앙대로1873번길 14 3층,부산 금정구 중앙대로1873번길 14,부산 금정구 구서동 248-26,0507-1415-5818,08:00 - 14:00/22:00,매주 일요일,전화문의,있음,PT,"자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 친절해요, 수업이 체계적이에요, 시..."
486,벨라임 P.T 스튜디오,벨라임 퍼스널트레이닝 스튜디오는 운동을 통한 신체의 변화 뿐만 아니라 삶의 변화까...,부산 해운대구 해운대로570번길 23 지하 1층,부산 해운대구 해운대로570번길 23,부산 해운대구 우동 644-2,0507-1497-3023,09:00 - 17:00/22:00,전화문의,20000원,있음,PT,"맞춤 케어를 잘해줘요, 자세를 꼼꼼히 봐주세요, 수업이 체계적이에요, 시설이 깔끔해..."
490,프렌즈스크린,세븐일레븐이 인접해 있습니다.,부산 강서구 명지국제6로 21 플러스시티 5층,부산 강서구 명지국제6로 21,부산 강서구 명지동 3589-9,0507-1399-8852,00:00-24:00,없음,전화문의,있음,없음,"시설이 깔끔해요, 친절해요, 최신 장비를 사용해요, 주차하기 편해요, 가격이 합리적이에요"
503,크라운스트라이크,"부산대역 3번 출구가 인접해 있습니다. 라퓨타아일랜드, 메가박스 부산대가 인접해 있...",부산 금정구 장전로12번길 55 지하 1층,부산 금정구 장전로12번길 55,부산 금정구 장전동 292-4,051-518-7544,12:00 ~ 02:00,없음,"일반 4000원, 청소년 3000원",없음,볼링,"시설이 깔끔해요, 레인이 많아요, 가격이 합리적이에요, 음악이 좋아요, 놀거리가 많아요"
566,디톡스핏,부산 최고의 1 대 1 퍼스널트레이닝 전문센터 입니다. 1000여명이 넘는 회원님을...,부산 동래구 문화로 9-8 1층~2층,부산 동래구 문화로 9-8,부산 동래구 명륜동 174-35,0507-1486-1091,09:00~18:00/23:00,"매주 일요일, 공휴일",전화문의,있음,PT,"맞춤 케어를 잘해줘요, 수업이 체계적이에요, 상담이 자세해요, 친절해요, 주차하기 편해요"
613,웨이브락 클라이밍 광안리점,상세한 이용 정보는 웨이브락 공식 홈페이지에서 확인하실 수 있습니다. 광안역 2번출...,부산 수영구 장대골로 41,부산 수영구 장대골로 41,부산 수영구 광안동 569-19,0507-1416-4226,10:00/12:00 - 21:00/22:30,전화문의,전화문의,있음,클라이밍,"친절해요, 시설이 깔끔해요, 문제가 다양해요, 안전하게 관리해요, 공간이 넓어요"
619,락오디세이 클라이밍 동래점,"주말 아웃도어 클라이밍, 캠핑 등 다양한 아읏도어 활동에 참가 가능합니다. 안락역 ...",부산 동래구 안남로31번길 6,부산 동래구 안남로31번길 6,부산 동래구 낙민동 91-3,0507-1393-8802,11:00 - 20:00/22:30,전화문의,20000원,있음,클라이밍,"초보자에게도 적합해요, 강습 받기 좋아요, 친절해요, 안전하게 관리해요, 시설이 깔끔해요"
653,구구롤러스케이트 금곡점,금곡동 농협하나로클럽 2층에 위치합니다. 주차는 농협하나로클럽 주차장을 항시 무료로...,부산 북구 금곡대로 469 농협하나로클럽 2층,부산 북구 금곡대로 469,부산 북구 금곡동 1874-3,0507-1347-4000,10:00/11:00-21:00/22:00,매주 월요일,"성인 11000원, 소인 9000원",있음,전화문의,"시설이 깔끔해요, 친절해요, 대여장비 상태가 좋아요, 주차하기 편해요, 휴게공간이 ..."
654,인핏퍼스널트레이닝,"부산 북구에 위치한 스포츠시설. 뉴코아아울렛, 덕천역 10번 출구가 인접해 있습니다.",부산 북구 기찰로 3 유니다로얄 상가건물 4층,부산 북구 기찰로 3,부산 북구 덕천동 348-2,0507-1374-5020,08:00 - 18:00/23:30,매주 일요일,1대1PT 50000원,있음,전화문의,"시설이 깔끔해요, 친절해요, 자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 수업이..."
753,웨이브락 클라이밍 서면점,"가장 즐거운 클라이밍의 경험 친구, 연인, 가족들과 함께 웨이브락 클라이밍에서 시작...",부산 부산진구 서전로9번길 20 혜도인파크에비뉴 오피스텔 상가 3층,부산 부산진구 서전로9번길 20,부산 부산진구 부전동 117-1,051-728-7170,10:00 - 21:00/22:30,전화문의,20000원,있음,클라이밍,"시설이 깔끔해요, 친절해요, 공간이 넓어요, 안전하게 관리해요, 수업이 체계적이에요"
963,BSJ body studio,원장직강으로 진행하고 있는 체형교정과 바른몸을 만들어 가는 공간 입니다. 그렇게 되...,부산 동래구 석사로 24 2층,부산 동래구 석사로 24,부산 동래구 사직동 72-23,0507-1380-9374,09:00~22:00,없음,전화문의,없음,필라테스,"자세를 꼼꼼히 봐주세요, 수업이 체계적이에요, 친절해요, 시설이 깔끔해요, 맞춤 케..."
1021,핏핏바디트레이닝 본점,"핏핏바디트레이닝만의 특장점 20가지 입니다. 1, 부산 양산 최초의 프라이빗 퍼스널...",부산 금정구 금샘로 387-1 2층,부산 금정구 금샘로 387-1,부산 금정구 구서동 1022-7,0507-1410-5868,08:00 - 14:00/22:00,매주 일요일,전화문의,있음,전화문의,"자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 친절해요, 수업이 체계적이에요, 시..."
1062,블로썸핏,"날마다 강하고, 섹시해지는 사람들이 다니는 블로썸핏 입니다. 하단역 7번 출구, 서...",부산 사하구 낙동대로 491 7층,부산 사하구 낙동대로 491,부산 사하구 하단동 511-7,0507-1408-0660,09:00 - 15:00/23:00,매주 일요일,110000원,있음,PT,"친절해요, 자세를 꼼꼼히 봐주세요, 맞춤 케어를 잘해줘요, 시설이 깔끔해요, 상담이..."
1101,체육시간,"높은 층고, 70평 규모의 팀트레이닝 전문 공간입니다 3개월 이상부터 수강권 휴회 ...",부산 해운대구 좌동로 96,부산 해운대구 좌동로 96,부산 해운대구 좌동 1461-3,0507-1396-1359,07:00/09:00 - 14:00/22:00,"매주 일요일, 공휴일",전화문의,있음,크로스핏,"시설이 깔끔해요, 수업이 체계적이에요, 자세를 꼼꼼히 봐주세요, 친절해요, 상담이 ..."
1142,락오디세이 클라이밍 동의대점,"성인, 청소년, 어린이 체험 환영합니다. 동의대역 2번출구, 온우드, 교육연수실에 ...",부산 부산진구 가야대로563번길 31,부산 부산진구 가야대로563번길 31,부산 부산진구 가야동 60-26,0507-1340-4592,11:00 - 20:00/22:30,전화문의,일일체험 20000원,있음,클라이밍,"강습 받기 좋아요, 초보자에게도 적합해요, 친절해요, 안전하게 관리해요, 가격이 합..."
1152,진리트레이너엔터테인먼트 수영점,"수영역 17번출구, 도미노피자, 다인빌에 인접해 있습니다.",부산 수영구 수영로 642 3층,부산 수영구 수영로 642,부산 수영구 광안동 99-10,010-4703-0092,00:00 - 24:00,없음,420000원,있음,PT,"친절해요, 상담이 자세해요, 수업이 체계적이에요, 자세를 꼼꼼히 봐주세요, 맞춤 케..."
1197,명륜저스트무브,"자세체크, 체형체크, 통증체크 등 다양한 바디컨디션 체크가 가능 합니다. 운동목적은...",부산 동래구 시실로 34 2층,부산 동래구 시실로 34,부산 동래구 명륜동 10-2,0507-1469-0183,09:00~23:00,"매주 토요일, 일요일",그룹PT 180000원,있음,그룹PT,"자세를 꼼꼼히 봐주세요, 친절해요, 맞춤 케어를 잘해줘요, 시설이 깔끔해요, 수업이..."
1217,고투 주례점,내가 운동을 할수 있을까라고 고민하는 고객님들께 고투 주례점만의 특별한 서비스 무료...,"부산 사상구 가야대로 256 주례한빛빌딩 6,7층 고투 주례점",부산 사상구 가야대로 256,부산 사상구 주례동 1162-1,051-312-6464,06:00/08:00/10:00 - 20:00/23:00,"둘째,넷째 일요일","PT 1000원, 헬스 25000원",있음,PT,"친절해요. 자세를 꼼꼼히 봐주세요, 상담이 자세해요, 시설이 깔끔해요, 수업이 체계..."
1287,구구롤러스케이트장,부산진구 전포동 서면에 위치한 500평 규모의 롤러스케이트장 입니다. 명절연휴 공휴...,부산 부산진구 서전로37번길 25-9 예일프라자,부산 부산진구 서전로37번길 25-9,부산 부산진구 전포동 661-2,0507-1396-0235,10:00/13:00-22:00,전화문의,"성인 11000원, 소인 9000원",있음,전화문의,"시설이 깔끔해요, 공간이 넓어요, 친절해요, 대여장비 상태가 좋아요, 휴게공간이 잘..."
1308,브로스클라이밍,"처음 클라이밍을 접하시는 분들도 쉽게 즐기실 수 있습니다. 전포역 7번출구, 에듀윌...",부산 부산진구 전포대로199번길 19 전포 예원빌딩 지하1층 브로스클라이밍,부산 부산진구 전포대로199번길 19,부산 부산진구 전포동 690-5,0507-1355-4799,14:00 - 20:00/22:30,전화문의,20000원,있음,클라이밍,"친절해요, 안전하게 관리해요, 시설이 깔끔해요, 가격이 합리적이에요, 수업이 체계적이에요"