In [ ]:
from datasets import load_dataset
from transformers import AutoTokenizer
import matplotlib.pyplot as plt
import pandas as pd


pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [2]:
import glob
import pandas as pd
import os

file_list = glob.glob('./data/220-1.관광 KVQA 데이터(동부권)/01-1.정식개방데이터/Training/01.원천데이터/TS_트리플_동부권_부산_숙박/*.csv')

rows = []

for file_path in file_list:
    try:
        temp_df = pd.read_csv(file_path, encoding='utf-8')
        row_dict = temp_df.set_index('관광타입')['숙박'].to_dict()
        rows.append(row_dict)
    except Exception as e:
        print(f"Error parsing {file_path}: {e}")

df = pd.DataFrame(rows)

cols = ['업소명'] + [c for c in df.columns if c not in ['업소명']]
df = df[cols]

print(f"총 {len(df)}개의 데이터가 정리되었습니다.")
df.head()

총 1582개의 데이터가 정리되었습니다.

,업소명,개요,주소,대표번호,입실시간,퇴실시간,홈페이지 주소,리뷰키워드,주소(도로명),주소(지번주소)
0,에어비앤비-MK게스트하우스,"부산 중구 부평동에 위치한 게스트하우스입니다. 자갈치시장, 감천문화마을, 용두산공원, 국제시장, 깡통야시장, 송도해수욕장등 다양한 관광지가 있고, 부산 전역을 손쉽게 대중교통으로 이동할 수 있는 교통의 요지입니다. 대나무집, 하마포차가 인접해 있다.",부산시 중구 흑교로11번길,없음,13:00,11:00,https://www.airbnb.co.kr//rooms/18200162?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
1,깐느모텔 2,"자갈치역 1번 출구가 인접해 있습니다. 시네모텔, 이데아가 인접해 있습니다.",부산 서구 구덕로114번길 30,010-2587-8836,15:00,12:00,https://place-site.yanolja.com/places/3008178?menu=pay&trackcode=rm,없음,부산 서구 구덕로114번길 30,부산 서구 충무동1가 7-19
2,에어비앤비-Sasang ALL FOR YOU house,"사상역, 사상서부시외버스터미널이 인접해 있다.",부산시 사상구,없음,15:00,11:00,https://www.airbnb.co.kr//rooms/20132840?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
3,에어비앤비-UH 플랫,"다년간 생활숙박시설을 운영하며 쌓아온 노하우로 도심속 공간에서 완벽한 휴식을 선물합니다. 최고급 호텔식 침구와 매트리스로 편안하고 안락한 잠자리를 제공합니다. 주차무료이용가능합니다. 전기차충전 가능합니다. 카페220볼트, 셰프뮤지엄718이 인접해 있습니다.",부산 기장 정관면,없음,16:00,11:00,https://www.airbnb.co.kr//rooms/786546708712319545?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
4,에어비앤비-뮤탄트 스누즈,"송정역, 라이크어바다가 인접해 있다.",부산시 해운대구,없음,15:00,12:00,https://www.airbnb.co.kr//rooms/634612823001527670?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN

In [ ]:
# 부산시만
df = df[df['주소'].str.contains('부산', na=False)]

print(f"{len(df)}")
df.head()

# 다 부산

1582

,업소명,개요,주소,대표번호,입실시간,퇴실시간,홈페이지 주소,리뷰키워드,주소(도로명),주소(지번주소)
0,에어비앤비-MK게스트하우스,"부산 중구 부평동에 위치한 게스트하우스입니다. 자갈치시장, 감천문화마을, 용두산공원, 국제시장, 깡통야시장, 송도해수욕장등 다양한 관광지가 있고, 부산 전역을 손쉽게 대중교통으로 이동할 수 있는 교통의 요지입니다. 대나무집, 하마포차가 인접해 있다.",부산시 중구 흑교로11번길,없음,13:00,11:00,https://www.airbnb.co.kr//rooms/18200162?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
1,깐느모텔 2,"자갈치역 1번 출구가 인접해 있습니다. 시네모텔, 이데아가 인접해 있습니다.",부산 서구 구덕로114번길 30,010-2587-8836,15:00,12:00,https://place-site.yanolja.com/places/3008178?menu=pay&trackcode=rm,없음,부산 서구 구덕로114번길 30,부산 서구 충무동1가 7-19
2,에어비앤비-Sasang ALL FOR YOU house,"사상역, 사상서부시외버스터미널이 인접해 있다.",부산시 사상구,없음,15:00,11:00,https://www.airbnb.co.kr//rooms/20132840?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
3,에어비앤비-UH 플랫,"다년간 생활숙박시설을 운영하며 쌓아온 노하우로 도심속 공간에서 완벽한 휴식을 선물합니다. 최고급 호텔식 침구와 매트리스로 편안하고 안락한 잠자리를 제공합니다. 주차무료이용가능합니다. 전기차충전 가능합니다. 카페220볼트, 셰프뮤지엄718이 인접해 있습니다.",부산 기장 정관면,없음,16:00,11:00,https://www.airbnb.co.kr//rooms/786546708712319545?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN
4,에어비앤비-뮤탄트 스누즈,"송정역, 라이크어바다가 인접해 있다.",부산시 해운대구,없음,15:00,12:00,https://www.airbnb.co.kr//rooms/634612823001527670?check_in=2023-01-08&check_out=2023-01-09&previous_page_section_name=1000,없음,NaN,NaN

In [4]:
df = df[df['리뷰키워드'] != '없음'].copy()

df = df[df['리뷰키워드'] != '없음']
df = df[df['리뷰키워드'].str.len() > 5].copy()

print(f"after filtering: {len(df)}")

after filtering: 295

In [5]:
df.sample(5)

,업소명,개요,주소,대표번호,입실시간,퇴실시간,홈페이지 주소,리뷰키워드,주소(도로명),주소(지번주소)
713,H에비뉴호텔 미남역점 2,"미남역 8번 출구가 인접해 있습니다. 아모르빌, 투유모텔이 인접해 있습니다.",부산 동래구 충렬대로92번길 21,0507-1360-3955,전화문의,전화문의,없음,"깨끗해요, 침구가 좋아요, 주차하기 편해요, 조용히 쉬기 좋아요, 친절해요",부산 동래구 충렬대로92번길 21,부산 동래구 온천동 1424-2
1229,에어스카이관광호텔 2,"에어스카이 호텔은 김해공항과 전국에서 가장 가까운 호텔로서 자부심과 책임감을 가지고 2019년 2월1일에 개관 하였습니다. 에어스카이 호텔은 럭셔리한 디자인과 모더니즘적 인테리어를 가미하여 삶의여유와 품격을 한층 높여 드릴것을 약속드립니다. 귀중한 분들과의 추억을 저희 호텔에어스카이에서 만들어 드리겠습니다. 감사합니다. 서부산 유통지구역 1번 출구가 인접해 있습니다. 컴포즈커피, 에어부산 신사옥이 인접해 있습니다.",부산 강서구 유통단지1로57번길 2,0507-1336-0093,15:00,12:00,https://www.goodchoice.kr/product/detail?ano=57850&adcno=2&sel_date=2022-10-11&sel_date2=2022-10-12,"친절해요, 깨끗해요, 조용히 쉬기 좋아요, 침구가 좋아요, 대중교통이 편해요",부산 강서구 유통단지1로57번길 2,부산 강서구 대저2동 3148-9
1421,타워힐 호텔,"타워힐호텔은 편리한 교통, 안락한 침구, 친절한 서비스로 편안한 쉼터를 추구합니다. 타워힐호텔은 과거와 현재와 미래가 공존하는 남포동을 사랑합니다. 타워힐호텔은 남포동의 공간을 여러분과 함께 공유합니다. 중앙역 1번 출구, 롯데백화점, 참치사랑애, 이마트24가 인접해 있습니다.",부산 중구 백산길 20 타워호텔,051-250-6100,15:00,11:00,http://www.towerhill.co.kr/,"친절해요, 침구가 좋아요, 깨끗해요, 조용히 쉬기 좋아요, 인테리어가 멋져요",부산 중구 백산길 20,부산 중구 동광동3가 20
37,르컬렉티브 부산역 2,"르 컬렉티브는 어반스테이가 런칭한 프리미엄 스테이 브랜드로, 함께하는 분들과의 특별한 시간을 위해 공간 내 모든 경험을 세심하게 collective 하였습니다. 부산역 6번 출구가 인접해 있습니다. 탐앤탐스, 비케이월삼이 인접해 있습니다.",부산 동구 충장대로 160,1644-7694,전화문의,전화문의,https://urbanstay.co.kr/lecollectiveg7,"깨끗해요, 뷰가 좋아요, 침구가 좋아요, 냉난방이 잘돼요, 조용히 쉬기 좋아요",부산 동구 충장대로 160,부산 동구 초량동 1185-64
999,코오롱 씨클라우드 호텔 2,"코오롱 씨클라우드호텔은 부산 최초의 레지던스 호텔로, 지상 30층 고층에서 바라보는 해운대 바다 풍경이 장관이다.",부산 해운대구 해운대해변로 287,051-933-1000,15:00,11:00,https://seacloudhotel.com,"뷰가 좋아요, 친절해요, 침구가 좋아요, 깨끗해요, 조용히 쉬기 좋아요",부산 해운대구 해운대해변로 287,NaN

In [6]:
# 리뷰 길이
df_sorted = df.sort_values(by='리뷰키워드', key=lambda x: x.str.len(), ascending=True)
df_sorted.head(10)

,업소명,개요,주소,대표번호,입실시간,퇴실시간,홈페이지 주소,리뷰키워드,주소(도로명),주소(지번주소)
564,투헤븐 모텔 2,"우수가든, 부산가든이 인접해 있습니다.",부산 북구 만덕고개길 74,051-333-8181,18:00/19:00,12:00/13:00,https://place-site.yanolja.com/places/3008542?menu=pay&trackcode=rm,"친절해요, 깨끗해요, 조용히 쉬기 좋아요, 주차하기 편해요",부산 북구 만덕고개길 74,부산 북구 만덕동 73-16
1441,호텔밴드 2,서면역 11번 출구가 인접해 있습니다.춘하추동과 사미헌이 인접해 있습니다.,부산 부산진구 새싹로29번길 14-9,0507-1427-0900,18:00,12:00,https://www.goodchoice.kr/product/detail?ano=67551&kcode=yp_na_namp_67551&msId=5&url=https%3A%2F%2Fwww.goodchoice.kr%2Fproduct%2Fdetail%3Fano%3D67551&,"깨끗해요,침구가좋아요,조용히쉬기좋아요,친절해요,주차하기편해요",부산 부산진구 새싹로29번길 14-9,부산 부산진구 부전동 403-30
1527,호텔밴드,서면역 11번 출구가 인접해 있습니다.춘하추동과 사미헌이 인접해 있습니다.,부산 부산진구 새싹로29번길 14-9,0507-1427-0900,18:00,12:00,https://www.goodchoice.kr/product/detail?ano=67551&kcode=yp_na_namp_67551&msId=5&url=https%3A%2F%2Fwww.goodchoice.kr%2Fproduct%2Fdetail%3Fano%3D67551&,"깨끗해요,침구가좋아요,조용히쉬기좋아요,친절해요,주차하기편해요",부산 부산진구 새싹로29번길 14-9,부산 부산진구 부전동 403-30
1175,언플랜드88 2,"광안리 해수욕장 30초 거리에 위치하고 있으며, 명소로 떠오르는 수변공원과도 10분]거리에 위치하고 있습니다. 횟집 편의점 등 편의시설도 가깝습니다. 아정모텔, GS25가 인접해 있습니다.",부산 수영구 민락수변로 15 4층 언플랜드88 게스트하우스,0507-1313-6713,15:00,11:00,https://blog.naver.com/idalsrms,"뷰가 좋아요, 침구가 좋아요, 친절해요, 깨끗해요, 파티가 재밌어요",부산 수영구 민락수변로 15,부산 수영구 민락동 181-145
536,마린뷰 호텔 2,"안녕하세요, 부산 광안리 마린뷰입니다. 저희 마린뷰는 언제나 쾌적하고 포근한 객실로 고객님들을 맞이하고 있습니다. 최고의 객실과 최고의 서비스가 있는 마린뷰에서 특별한 추억을 남겨보세요. 설빙, 비어팩토리가 인접해 있습니다.","부산 수영구 광안해변로278번길 42 오션브릿지 B동 11, 12층 마린뷰호텔",0507-1396-3133,17:00,13:00,https://marineview.modoo.at,"뷰가 좋아요, 친절해요, 깨끗해요, 침구가 좋아요, 주차하기 편해요",부산 수영구 광안해변로278번길 42,부산 수영구 민락동 181-154
847,브라운도트 호텔 명지점 2,"일인 일실주차가능 바다전망 깔끔한 인테리어 김해공항 가까운 호텔, 시설좋고 뷰도 좋아. 대마등, 명진수산이 인접해 있습니다.",부산 강서구 르노삼성대로 576-6,051-271-3777,17:00,12:00,http://wnhotels.com/browndot/myungji,"깨끗해요, 친절해요, 침구가 좋아요, 뷰가 좋아요, 냉난방이 잘돼요",부산 강서구 르노삼성대로 576-6,부산 강서구 명지동 1526-3
684,에이치에비뉴 호텔 광안리점 2,"호텔에서는 고객님의 안전을 최우선으로 생각하여, 주기적으로 소독진행 및 방역에 힘쓰고 있습니다. 고객님께서도 자주 손 씻기, 마스크 착용 등 거리두기 규제 준수 부탁드립니다.",부산 수영구 민락수변로 29,0507-1300-1340,16:00,12:00,https://havenuehotel.modoo.at,"뷰가 좋아요, 친절해요, 침구가 좋아요, 깨끗해요, 조식이 맛있어요",부산 수영구 민락수변로 29,부산 수영구 민락동 181-223
1529,오즈모텔 2,"저희 오즈모텔은 기장읍 대변리 대변항에 위치해 있고 송정과 해운대에 인접해 있으며 대형 주차장이 완비되어 있습니다. 창문 밖으로 기장 대변항의 야경을 감상할 수 있습니다. 최신 시설과 합리적인 가격으로 즐겁고 편안한 여행이 되도록 최선을 다하겠습니다. 대도횟집, IW호텔이 인접해 있습니다.",부산 기장군 기장읍 기장해안로 530,051-722-9030,16:00,13:00,https://bsoz.modoo.at,"깨끗해요, 침구가 좋아요, 친절해요, 주차하기 편해요, 뷰가 좋아요",부산 기장군 기장읍 기장해안로 530,부산 기장군 기장읍 대변리 277-1
678,1872팡시온펜션 2,"그리스 산토리니 컨셉으로 모던한 인테리어의 객실, 깔끔한객실, 파티를 가능한 파티룸 별도로 있습니다. 1년 365일 언제나 예약 가능 합니다. 전산가든, 메르송하우스가 인접해 있습니다.",부산 기장군 일광읍 학리길 20-1,0507-1343-2614,15:00,11:00,http://www.1872pangsion.com/,"깨끗해요, 뷰가 좋아요, 침구가 좋아요, 냉난방이 잘돼요, 친절해요",부산 기장군 일광읍 학리길 20-1,부산 기장군 일광읍 학리 187-2
1428,해운대엘시티더샵랜드마크타워 2,"중동역 7번 출구가 인접해 있습니다. 세븐일레븐, CU가 인접해 있습니다.",부산 해운대구 달맞이길 30,없음,상황에 따라 다름,상황에 따라 다름,없음,"친절해요, 깨끗해요, 침구가 좋아요, 냉난방이 잘돼요, 뷰가 좋아요",부산 해운대구 달맞이길 30,부산 해운대구 중동 1829