In [19]:
import pandas as pd
from collections import Counter
import numpy as np
from transformers import AutoTokenizer
import matplotlib.pyplot as plt
import re

In [2]:
df = pd.read_csv('/data/ephemeral/pro-nlp-finalproject-nlp-13/data/persona_data/AiHub_multiturn_3window.csv',usecols=['res','req'])

In [3]:
for col in df.columns:
    df[col] = df[col].str.replace('\n', ' ')

In [4]:
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen3-4B')

In [ ]:
def quick_token_analysis(df, text_column='res'):
    texts = df[text_column].dropna().astype(str).tolist()
    
    # 전체 토큰화
    all_tokens = []
    for text in texts:
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    print(f"=== {text_column} 컬럼 토큰 분석 ===")
    print(f"총 샘플 수: {len(texts):,}")
    print(f"총 토큰 수: {len(all_tokens):,}")
    print(f"고유 토큰 수: {len(token_counts):,}")
    print(f"다양성 비율: {len(token_counts)/len(all_tokens)*100:.2f}%")
    
    # 집중도
    total = len(all_tokens)
    top10 = sum([cnt for _, cnt in token_counts.most_common(10)]) / total
    top100 = sum([cnt for _, cnt in token_counts.most_common(100)]) / total
    
    print(f"\n상위 10개 토큰 집중도: {top10*100:.2f}%")
    print(f"상위 100개 토큰 집중도: {top100*100:.2f}%")
    
    # 상위 토큰들
    print(f"\n가장 많이 사용된 토큰 20개:")
    for token_id, count in token_counts.most_common(20):
        token_str = tokenizer.decode([token_id])
        print(f"  '{token_str}': {count:,}회 ({count/total*100:.2f}%)")
    
    return token_counts

# 둘 다 분석
print("=" * 60)
print("응답(res) 분석")
print("=" * 60)
res_tokens = quick_token_analysis(df, 'res')

print("\n" + "=" * 60)
print("요청(req) 분석")
print("=" * 60)
req_tokens = quick_token_analysis(df, 'req')

============================================================
응답(res) 분석
============================================================
=== res 컬럼 토큰 분석 ===
총 샘플 수: 500,707
총 토큰 수: 10,180,639
고유 토큰 수: 7,242
다양성 비율: 0.07%

상위 10개 토큰 집중도: 13.44%
상위 100개 토큰 집중도: 47.25%

가장 많이 사용된 토큰 20개:
  '!': 212,473회 (2.09%)
  '.': 174,155회 (1.71%)
  '이': 158,335회 (1.56%)
  '?': 148,080회 (1.45%)
  '도': 138,257회 (1.36%)
  '을': 126,073회 (1.24%)
  '야': 111,902회 (1.10%)
  '아': 109,757회 (1.08%)
  '어': 96,570회 (0.95%)
  ',': 93,040회 (0.91%)
  ' �': 88,371회 (0.87%)
  ' ': 87,224회 (0.86%)
  '가': 81,173회 (0.80%)
  '에': 80,085회 (0.79%)
  ' 가': 74,600회 (0.73%)
  '지': 71,757회 (0.70%)
  ' 수': 71,625회 (0.70%)
  '는': 68,726회 (0.68%)
  '은': 68,719회 (0.67%)
  ' 거': 66,350회 (0.65%)

============================================================
요청(req) 분석
============================================================
=== req 컬럼 토큰 분석 ===
총 샘플 수: 500,707
총 토큰 수: 30,368,734
고유 토큰 수: 7,609
다양성 비율: 0.03%

상위 10개 토큰 집중도: 13.48%
상위 100개 토큰 집중도: 46.82%

가장 많이 사용된 토큰 20개:
  '!': 563,025회 (1.85%)
  '?': 543,293회 (1.79%)
  '.': 502,337회 (1.65%)
  '이': 488,330회 (1.61%)
  '도': 396,579회 (1.31%)
  '을': 347,675회 (1.14%)
  '야': 328,249회 (1.08%)
  ' ': 327,386회 (1.08%)
  ' �': 300,042회 (0.99%)
  '어': 297,797회 (0.98%)
  ',': 280,875회 (0.92%)
  '아': 280,223회 (0.92%)
  '가': 249,915회 (0.82%)
  '에': 239,420회 (0.79%)
  ' 가': 212,191회 (0.70%)
  ' 수': 205,424회 (0.68%)
  '는': 201,387회 (0.66%)
  '은': 201,274회 (0.66%)
  '지': 199,253회 (0.66%)
  ' 거': 199,232회 (0.66%)

In [6]:
def check_ngram_patterns(df, text_column='res', n=2, top_k=15):
    ngrams = []
    
    for text in df[text_column].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        
        for i in range(len(tokens) - n + 1):
            ngram = tuple(tokens[i:i+n])
            ngrams.append(ngram)
    
    ngram_counts = Counter(ngrams)
    
    print(f"\n=== {n}-gram 패턴 (상위 {top_k}개) ===")
    print(f"총 {n}-gram: {len(ngrams):,}")
    print(f"고유 {n}-gram: {len(ngram_counts):,}")
    print(f"다양성: {len(ngram_counts)/len(ngrams)*100:.2f}%\n")
    
    for pattern, count in ngram_counts.most_common(top_k):
        decoded = tokenizer.decode(list(pattern))
        print(f"'{decoded}': {count:,}회")

In [65]:
check_ngram_patterns(df, 'res', n=2, top_k=10)
check_ngram_patterns(df, 'res', n=3, top_k=10)
check_ngram_patterns(df, 'res', n=5, top_k=10)
check_ngram_patterns(df, 'res', n=6, top_k=10)

=== 2-gram 패턴 (상위 10개) ===
총 2-gram: 9,679,932
고유 2-gram: 332,646
다양성: 3.44%

'아!': 35,964회
'맞아': 35,652회
' 거야': 33,135회
'ㅋㅋ': 29,163회
' 같아': 28,805회
'야?': 25,966회
' 것 같': 25,933회
'이야': 24,987회
' �': 23,243회
' 1': 20,199회

=== 3-gram 패턴 (상위 10개) ===
총 3-gram: 9,179,226
고유 3-gram: 1,714,574
다양성: 18.68%

' 것 같아': 25,143회
'맞아!': 24,545회
' 레': 15,268회
' 거야?': 14,731회
' 꼭': 12,686회
' ㅋㅋ': 10,849회
'그러면': 10,445회
' 곳이': 10,129회
' 볼 수': 9,787회
' 싶어': 9,581회

=== 5-gram 패턴 (상위 10개) ===
총 5-gram: 8,178,171
고유 5-gram: 4,460,998
다양성: 54.55%

' 좋을 것 같아': 5,430회
' 레알루': 3,672회
'��알루다가': 3,672회
' 렬루다가': 3,580회
' 꼭 가봐': 3,267회
' 레게노': 3,234회
' 수 있을 것 같아': 3,230회
'�� 가봐야': 2,928회
' 가보고 싶어': 2,922회
' 흥미로': 2,881회

=== 6-gram 패턴 (상위 10개) ===
총 6-gram: 7,678,217
고유 6-gram: 5,145,729
다양성: 67.02%

' 레알루다가': 3,672회
' 꼭 가봐야': 2,928회
' 레게노다': 2,833회
' 즐거운 시간 보내': 1,987회
' 흥미로워': 1,881회
' 맛있는 음식': 1,677회
'�거운 시간 보내자': 1,608회
'�� 가봐야겠다': 1,514회
' 가보고 싶어!': 1,506회
'면 좋을 것 같아': 1,424회

In [8]:
exact_dupes = df.duplicated(subset=['res'], keep=False)
n_exact_dupes = exact_dupes.sum()

print(f"전체 샘플: {len(df):,}개")
print(f"중복된 샘플: {n_exact_dupes:,}개 ({n_exact_dupes/len(df)*100:.2f}%)")
print(f"고유 샘플: {df['res'].nunique():,}개")

전체 샘플: 500,707개
중복된 샘플: 85,646개 (17.11%)
고유 샘플: 452,634개

In [9]:
df[exact_dupes].res

1080                      스쿠버다이빙은 3만원, 프리다이빙이랑 스노쿨링은 1만원이야.
2608      사우디아라비아 수도인 리야드와 기암괴석을 볼 수 있는 알 울라, 성지 메디나, 항구...
3452           국내 최고 모래조각 작가인 최지훈, 홍성렬 작가와 중국 장저우 작가가 제작했대.
3572                      스쿠버다이빙은 3만원, 프리다이빙이랑 스노쿨링은 1만원이야.
7329                                코레일관광개발 사이트에서 예약할 수 있어!
                                ...
498644                                      그렇게 말하니까 더 기대돼!
498652                                  짜짜? 그러면 나도 한 번 봐야겠다
498699                                              어떤 책이야?
498703                                            꼭 읽어봐야겠다!
500000                                     우리금융아트홀이 어디에 있어?
Name: res, Length: 85646, dtype: object

In [11]:
df[df.req=='오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자']

                                               req                 res
12993   오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자    토요일은 날씨가 좋을 것 같아
22561   오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자    토요일은 날씨가 좋을 것 같아
40046   오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자  수성동계곡에는 석교와 목교가 있어
42282   오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자   토요일에는 날씨가 좋을 것 같아
450237  오 굿굿! 언제 가자? 주말에 가면 좋을 것 같아 그래! 그럼 토요일에 가자           토요일에 만나자!

In [44]:
df[df.res=='어떤 책이야?']

                                                      req      res   entropy
270190                               헬롱! 헬롱! 뭐해? 책을 읽고 있어  어떤 책이야?  1.791759
352098  훈민정음에 대해 들어봄? 응, 한글 만든 거지? 맞아! 그리고 최근에 훈민정음과 관...  어떤 책이야?  1.791759
386151               오늘 뉴스 들었음? 응, 뭐 있었어? 한양대 교수가 책을 출간했대  어떤 책이야?  1.791759
389701                 영화 어떤 거? 액션 영화야! 너는? 나는 책 읽고 있어 ㅋㅋ  어떤 책이야?  1.791759
390207        세계 뉴스 이해 어려워 맞아 ㅠㅠ 어렵게 느껴져 그런데 이번에 나온 책 알아?  어떤 책이야?  1.791759
394742        미술은 짜짜 어려워 나도 그렇게 생각해 그런데 최근에 미술 수업 책을 발견했어  어떤 책이야?  1.791759
400461          더위가 물러가서 다행이야 맞아 8월 장맛비로 시원해졌어 그래서 책을 꺼냈어  어떤 책이야?  1.791759
420820              그 작가는 만화가이기도 해 와 짜짜? 멋있네! 얼마 전에 책을 냈어  어떤 책이야?  1.791759
498699  한번 바꿔보면 기분이 좋아져! 레알? 나도 해봐야겠다 ㅎㅎ 그리고 이 책을 읽으면 ...  어떤 책이야?  1.791759

In [13]:
len(tokenizer)

151669

In [21]:
import re

def count_korean_number_special(tokenizer):
    """한글, 숫자, 특수문자만 세기"""
    
    vocab = tokenizer.get_vocab()
    total = len(vocab)
    
    # 카테고리별 카운트
    counts = {
        '한글_완성형': 0,      # 가-힣 포함
        '한글_자모': 0,        # ㄱ-ㅎ, ㅏ-ㅣ만
        '숫자': 0,
        '특수문자': 0,
        '공백/개행': 0,
        '바이트토큰': 0,       # <0xXX>
        '특수토큰': 0,         # <|endoftext|> 등
        '기타': 0
    }
    
    # 샘플 저장
    samples = {k: [] for k in counts.keys()}
    
    for token_str, token_id in vocab.items():
        try:
            decoded = tokenizer.decode([token_id])
        except:
            decoded = token_str
        
        categorized = False
        
        # 1. 특수 토큰
        if token_str.startswith('<') and token_str.endswith('>'):
            if '0x' in token_str:
                counts['바이트토큰'] += 1
                if len(samples['바이트토큰']) < 10:
                    samples['바이트토큰'].append((token_id, token_str, decoded))
            else:
                counts['특수토큰'] += 1
                if len(samples['특수토큰']) < 10:
                    samples['특수토큰'].append((token_id, token_str, decoded))
            categorized = True
        
        # 2. 공백/개행
        elif decoded.strip() == '' or decoded in ['\n', '\t', ' ']:
            counts['공백/개행'] += 1
            if len(samples['공백/개행']) < 10:
                samples['공백/개행'].append((token_id, token_str, repr(decoded)))
            categorized = True
        
        if not categorized:
            has_complete = bool(re.search(r'[가-힣]', decoded))
            has_jamo = bool(re.search(r'[ㄱ-ㅎㅏ-ㅣ]', decoded))
            
            # 3. 한글
            if has_complete:
                counts['한글_완성형'] += 1
                if len(samples['한글_완성형']) < 10:
                    samples['한글_완성형'].append((token_id, token_str, decoded))
                categorized = True
            
            elif has_jamo:
                counts['한글_자모'] += 1
                if len(samples['한글_자모']) < 10:
                    samples['한글_자모'].append((token_id, token_str, decoded))
                categorized = True
        
        # 4. 숫자만 (영어/한글 없이)
        if not categorized:
            if re.match(r'^[0-9\s]+$', decoded.strip()) and re.search(r'[0-9]', decoded):
                counts['숫자'] += 1
                if len(samples['숫자']) < 10:
                    samples['숫자'].append((token_id, token_str, decoded))
                categorized = True
        
        # 5. 특수문자만 (한글, 영어, 숫자, 공백 제외)
        if not categorized:
            if re.match(r'^[^\w가-힣ㄱ-ㅎㅏ-ㅣ\s]+$', decoded.strip()):
                counts['특수문자'] += 1
                if len(samples['특수문자']) < 10:
                    samples['특수문자'].append((token_id, token_str, decoded))
                categorized = True
        
        # 6. 기타
        if not categorized:
            counts['기타'] += 1
            if len(samples['기타']) < 10:
                samples['기타'].append((token_id, token_str, decoded))
    
    # 결과 출력
    print("=" * 80)
    print(f"Qwen Tokenizer Vocab 분석 (한글/숫자/특수문자)")
    print("=" * 80)
    print(f"\n전체 vocab 크기: {total:,}개\n")
    
    # 한글 합계
    korean_total = counts['한글_완성형'] + counts['한글_자모']
    
    print(f"{'한글 (전체)':15s}: {korean_total:7,}개 ({korean_total/total*100:5.2f}%)")
    print(f"  {'- 완성형':13s}: {counts['한글_완성형']:7,}개 ({counts['한글_완성형']/total*100:5.2f}%)")
    print(f"  {'- 자모':13s}: {counts['한글_자모']:7,}개 ({counts['한글_자모']/total*100:5.2f}%)")
    print(f"{'숫자':15s}: {counts['숫자']:7,}개 ({counts['숫자']/total*100:5.2f}%)")
    print(f"{'특수문자':15s}: {counts['특수문자']:7,}개 ({counts['특수문자']/total*100:5.2f}%)")
    print(f"{'공백/개행':15s}: {counts['공백/개행']:7,}개 ({counts['공백/개행']/total*100:5.2f}%)")
    print(f"{'바이트토큰':15s}: {counts['바이트토큰']:7,}개 ({counts['바이트토큰']/total*100:5.2f}%)")
    print(f"{'특수토큰':15s}: {counts['특수토큰']:7,}개 ({counts['특수토큰']/total*100:5.2f}%)")
    print(f"{'기타':15s}: {counts['기타']:7,}개 ({counts['기타']/total*100:5.2f}%)")
    
    # 샘플 출력
    print("\n" + "=" * 80)
    print("각 카테고리별 샘플")
    print("=" * 80)
    
    for category in ['한글_완성형', '한글_자모', '숫자', '특수문자']:
        sample_list = samples[category]
        if sample_list:
            print(f"\n[{category}] {counts[category]:,}개")
            for token_id, token_str, decoded in sample_list:
                print(f"  ID {token_id:6d}: '{decoded}'")
    
    return counts, samples

# 실행
counts, samples = count_korean_number_special(tokenizer)

================================================================================
Qwen Tokenizer Vocab 분석 (한글/숫자/특수문자)
================================================================================

전체 vocab 크기: 151,669개

한글 (전체)        :   3,532개 ( 2.33%)
  - 완성형        :   3,495개 ( 2.30%)
  - 자모         :      37개 ( 0.02%)
숫자             :      10개 ( 0.01%)
특수문자           :   9,322개 ( 6.15%)
공백/개행          :     441개 ( 0.29%)
바이트토큰          :       0개 ( 0.00%)
특수토큰           :      33개 ( 0.02%)
기타             : 138,331개 (91.21%)

================================================================================
각 카테고리별 샘플
================================================================================

[한글_완성형] 3,495개
  ID 136414: '행위'
  ID 133830: '생활'
  ID 151046: '챃'
  ID 144286: '큐'
  ID 126551: '는데'
  ID 126445: '프'
  ID 145229: '렙'
  ID 144042: '짐'
  ID 145455: '깍'
  ID 151024: '좐'

[한글_자모] 37개
  ID 149068: 'ㅔ'
  ID 147783: 'ㅃ'
  ID 146076: 'ㄲ'
  ID 144065: 'ㅠ'
  ID 151604: 'ㅖ'
  ID 145039: 'ㄷ'
  ID 146636: 'ㅗ'
  ID 145898: 'ㅉ'
  ID 145951: 'ㅌ'
  ID 145017: 'ㄱ'

[숫자] 10개
  ID     19: '4'
  ID     16: '1'
  ID     17: '2'
  ID     24: '9'
  ID     15: '0'
  ID     23: '8'
  ID     21: '6'
  ID     22: '7'
  ID     18: '3'
  ID     20: '5'

[특수문자] 9,322개
  ID    532: '}
'
  ID  54538: ' ..
'
  ID 147923: '🏨'
  ID  83777: '"]=$'
  ID  44908: '==============='
  ID  85390: '+=''
  ID 146619: '〗'
  ID  53614: '('&'
  ID  30799: ' ////'
  ID  99160: '�'

In [24]:
def full_breakdown_with_english(df, text_col='res'):
    """영어 포함 전체 분류"""
    
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    used_tokens = set(all_tokens)
    
    korean = 0
    english = 0
    digit = 0
    special = 0
    space = 0
    etc = 0
    
    korean_samples = []
    english_samples = []
    
    for token_id in used_tokens:
        decoded = tokenizer.decode([token_id])
        
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        has_digit = bool(re.search(r'[0-9]', decoded))
        has_special = bool(re.search(r'[^\w가-힣ㄱ-ㅎㅏ-ㅣ\s]', decoded))
        
        categorized = False
        
        # 공백
        if decoded.strip() == '':
            space += 1
            categorized = True
        
        # 한글
        elif has_korean:
            korean += 1
            if len(korean_samples) < 20:
                korean_samples.append((token_id, decoded))
            categorized = True
        
        # 영어
        elif has_english and not has_korean:
            english += 1
            if len(english_samples) < 20:
                english_samples.append((token_id, decoded))
            categorized = True
        
        # 숫자
        elif has_digit and not has_korean and not has_english:
            digit += 1
            categorized = True
        
        # 특수문자
        elif has_special and not has_korean and not has_english:
            special += 1
            categorized = True
        
        if not categorized:
            etc += 1
    
    total = len(used_tokens)
    
    print(f"=== 사용된 토큰 전체 분류 ===")
    print(f"총 사용 토큰: {total:,}개\n")
    print(f"{'한글':10s}: {korean:5,}개 ({korean/total*100:5.2f}%)")
    print(f"{'영어':10s}: {english:5,}개 ({english/total*100:5.2f}%)")
    print(f"{'숫자':10s}: {digit:5,}개 ({digit/total*100:5.2f}%)")
    print(f"{'특수문자':10s}: {special:5,}개 ({special/total*100:5.2f}%)")
    print(f"{'공백':10s}: {space:5,}개 ({space/total*100:5.2f}%)")
    print(f"{'기타':10s}: {etc:5,}개 ({etc/total*100:5.2f}%)")
    
    print(f"\n검증: {korean+english+digit+special+space+etc} = {total}")
    
    # 샘플 확인
    print(f"\n=== 한글 토큰 샘플 20개 ===")
    for token_id, decoded in korean_samples:
        print(f"  ID {token_id:6d}: '{decoded}'")
    
    print(f"\n=== 영어 토큰 샘플 20개 ===")
    for token_id, decoded in english_samples:
        print(f"  ID {token_id:6d}: '{decoded}'")
    
    return {
        'korean': korean,
        'english': english,
        'digit': digit,
        'special': special,
        'space': space,
        'etc': etc
    }

# 실행
breakdown = full_breakdown_with_english(df, 'res')

=== 사용된 토큰 전체 분류 ===
총 사용 토큰: 7,242개

한글        : 2,610개 (36.04%)
영어        : 4,013개 (55.41%)
숫자        :    10개 ( 0.14%)
특수문자      :   453개 ( 6.26%)
공백        :     3개 ( 0.04%)
기타        :   153개 ( 2.11%)

검증: 7242 = 7242

=== 한글 토큰 샘플 20개 ===
  ID 131097: '새'
  ID 131110: '회사'
  ID 131120: '총'
  ID  98358: ' 종'
  ID 131131: '티'
  ID  32831: '성'
  ID 131137: '처럼'
  ID 131180: ' 여기'
  ID 131196: '브'
  ID 131193: '사항'
  ID 131219: ' 정도'
  ID 131226: '북'
  ID 131277: ' 내가'
  ID 131293: '림'
  ID 131303: '줄'
  ID 131342: '처리'
  ID 131344: '친'
  ID 131347: '충'
  ID 131355: '어요'
  ID 131366: ' 이러'

=== 영어 토큰 샘플 20개 ===
  ID     32: 'A'
  ID     33: 'B'
  ID     34: 'C'
  ID     35: 'D'
  ID     38: 'G'
  ID     36: 'E'
  ID     41: 'J'
  ID     42: 'K'
  ID     43: 'L'
  ID     44: 'M'
  ID     45: 'N'
  ID     46: 'O'
  ID     47: 'P'
  ID     49: 'R'
  ID     50: 'S'
  ID     51: 'T'
  ID     52: 'U'
  ID     53: 'V'
  ID     54: 'W'
  ID     56: 'Y'

In [25]:
# 영어 토큰 상위 빈도 확인
def check_english_tokens(df, text_col='res'):
    """영어 토큰이 뭔지 자세히 보기"""
    
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    # 영어 토큰만 필터링
    english_tokens = []
    for token_id, count in token_counts.items():
        decoded = tokenizer.decode([token_id])
        
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        
        if has_english and not has_korean:
            english_tokens.append((token_id, decoded, count))
    
    # 빈도순 정렬
    english_tokens.sort(key=lambda x: x[2], reverse=True)
    
    print(f"=== 영어 토큰 상위 30개 ===")
    print(f"총 영어 토큰: {len(english_tokens):,}개\n")
    
    for i, (token_id, decoded, count) in enumerate(english_tokens[:30], 1):
        print(f"{i:2d}. ID {token_id:6d}: '{decoded:20s}' - {count:,}회")
    
    # 영어 토큰 총 사용 횟수
    total_english_count = sum(x[2] for x in english_tokens)
    total_tokens = len(all_tokens)
    
    print(f"\n영어 토큰 사용 빈도: {total_english_count:,}회 ({total_english_count/total_tokens*100:.2f}%)")

check_english_tokens(df, 'res')

=== 영어 토큰 상위 30개 ===
총 영어 토큰: 4,013개

 1. ID    730: ' K                  ' - 1,049회
 2. ID     38: 'G                   ' - 1,033회
 3. ID    479: ' G                  ' - 952회
 4. ID  14978: 'BJ                  ' - 876회
 5. ID     57: 'Z                   ' - 609회
 6. ID    386: ' M                  ' - 503회
 7. ID  16017: 'km                  ' - 470회
 8. ID     53: 'V                   ' - 465회
 9. ID     42: 'K                   ' - 448회
10. ID     76: 'm                   ' - 411회
11. ID   6159: ' CG                 ' - 336회
12. ID    328: ' S                  ' - 257회
13. ID    362: ' A                  ' - 253회
14. ID     35: 'D                   ' - 248회
15. ID  20192: ' DM                 ' - 221회
16. ID    451: ' N                  ' - 216회
17. ID   5487: 'ICE                 ' - 177회
18. ID   3994: 'FT                  ' - 175회
19. ID  96988: 'MZ                  ' - 173회
20. ID    425: ' B                  ' - 164회
21. ID  15653: 'TV                  ' - 164회
22. ID  21387: ' DJ                 ' - 154회
23. ID  15235: ' AI                 ' - 141회
24. ID     44: 'M                   ' - 130회
25. ID   5883: ' TV                 ' - 129회
26. ID  22867: 'TX                  ' - 128회
27. ID     32: 'A                   ' - 127회
28. ID     37: 'F                   ' - 122회
29. ID   8798: 'CG                  ' - 122회
30. ID     55: 'X                   ' - 122회

영어 토큰 사용 빈도: 29,406회 (0.29%)

In [ ]:
# 이 토큰들이 어떤 맥락에서 쓰이는지 보기
def check_token_context(df, text_col='res', token_id=730):
    """특정 토큰이 쓰인 문장들 확인"""
    
    samples = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        if token_id in tokens:
            samples.append(text)
            if len(samples) >= 10:
                break
    
    decoded_token = tokenizer.decode([token_id])
    print(f"=== Token ID {token_id} ('{decoded_token}')이 사용된 문장들 ===\n")
    
    for i, text in enumerate(samples, 1):
        print(f"{i:2d}. {text}")

# 상위 토큰들 확인
print("=" * 80)
check_token_context(df, 'res', token_id=730)   # ' K'
print("\n" + "=" * 80)
check_token_context(df, 'res', token_id=38)    # 'G'
print("\n" + "=" * 80)
check_token_context(df, 'res', token_id=14978) # 'BJ'
print("\n" + "=" * 80)
check_token_context(df, 'res', token_id=57) # 'BJ'
print("\n" + "=" * 80)
check_token_context(df, 'res', token_id=53) # 'BJ'
print("\n" + "=" * 80)
check_token_context(df, 'res', token_id=76) # 'BJ'

================================================================================
=== Token ID 730 (' K')이 사용된 문장들 ===

 1. 그러게. 심지어 이거 서울 뿐만 아니라 대구나 인천 이런 지역에도 꽤 있나봐. 요즘 K한옥 다시 재조명받는듯.
 2. 맞아. 서귀포 K POP 문화축제 같은 지역 축제랑 같이 하기도 하고 한다네. 그쪽은 진짜 초대박 예정이지. ㅎㅎ
 3. 당근이지 ㅋㅋ. 이번에 K-트래블 발전을 지원할 계획이라고 했대. 앞으로 다양한 지역 관광 혜택이 나올 것 같아. 야놀자 50% 숙박할인 받으면 진짜 가성비 최고일듯!
 4. 응. 그래서 서귀포 K-POP 문화축제 같은 지역 K-컬쳐 행사랑 연계해서 관광전세편도 유치할 계획이래.
 5. 무대행사, 부대행사, 프린지 페스티벌, K-POP 콘서트도 열린대!
 6. 헐, 진짜? K-POP 콘서트는 언제 열리는데? 그날만 갈까?
 7. 현재존은 K팝 콘서트나 퍼레이드 같은 공연 행사가 많아.
 8. 널 위한 K공포 축제가 있어. 한국 민속촌에서 하는 심야공포촌이라고 못 들어봤어?
 9. 와 처음에 분장을 너무 리얼하게 하신 분들이 많아서 놀랬음. Kijul 무섭게 느껴졌던 부분도 있었고 ㅠㅠ. 여기까지만 말함 ㅋㅋ. 더 말하면 완전 스포야! 직접 가서 보라고!ㅎㅎ
10. 와! 완전 K-공포 문화잖아? 너무 재밌겠는데? 나 벌써부터 막 떨린다. 입장료는 얼마야?

================================================================================
=== Token ID 38 ('G')이 사용된 문장들 ===

 1. G마켓이나 옥션에서 항공권을 구매하면 더 할인 받을 수 있어?
 2. 피렌체의 피렌체 대성당과 피사의 사원도 GBJG
 3. 사우디아라비아로 여행 GBJG!
 4. GOLD 회원권은 2,700만원, VIP 회원권은 5,000만원이야
 5. 맞아! 그리고 독립기념관도 있는데, 한 번 GBJG!
 6. 그래! 일단 대둔산과 월영산 출렁다리부터 GBJG
 7. 응! 꽃들이 만개한 국립세종수목원도 GBJG!
 8. 맞아! 청양 알품스도 GBJG
 9. 한 번 GBJG!
10. 그리고 묵호항 주변에 있는 도째비골스카이밸리도 GBJG!

================================================================================
=== Token ID 14978 ('BJ')이 사용된 문장들 ===

 1. 피렌체의 피렌체 대성당과 피사의 사원도 GBJG
 2. 사우디아라비아로 여행 GBJG!
 3. 맞아! 그리고 독립기념관도 있는데, 한 번 GBJG!
 4. 그래! 일단 대둔산과 월영산 출렁다리부터 GBJG
 5. 응! 꽃들이 만개한 국립세종수목원도 GBJG!
 6. 맞아! 청양 알품스도 GBJG
 7. 한 번 GBJG!
 8. 그리고 묵호항 주변에 있는 도째비골스카이밸리도 GBJG!
 9. 나중에 일정 잡고 가자! 꼭 GBJG!
10. 발왕산? 그럼 거기로 GBJG!

================================================================================
=== Token ID 57 ('Z')이 사용된 문장들 ===

 1. 올~완전 MZ한데? 가성비가 좋으면서도 편안하게 즐길 수 있는 여행이구나 ㅋㅋ. 그러면 보통 코지미엄 여행객들이 많이 찾는 나라는 어디야?
 2. 치트키마다 갤럭시Z 플립5, BBQ 황금 올리브 치킨같은 경품이 걸려있고 마지막 미션에 응모하면 하와이 2인 에어텔, 에어팟 맥스, 신라호텔 50만원도 추첨해서 준대.
 3. ㅇㅇ, 추첨으로 비비큐 황금올리브 치킨이나 삼성 갤럭시Z 플립5 받을 수도 있음!
 4. 각 미션에 따라 추첨해서 삼성 갤럭시Z 플립5, BBQ 황금올리브 치킨을 준다고 하더라.
 5. 일단 첫 번째 미션인 하나투어 앱 설치하기만 해도 무적권 비타500을 증정하고 있고, 다른 미션들 역시 추첨을 통해 삼성 갤럭시Z 플립, BBQ 황금 올리브 치킨같이 다양한 선물들을 증정할 예정이래!
 6. 경험도 중요시하고 합리적인 소비를 좋아하는 MZ세대들이 좋아하겠당.
 7. ㅇㅇ. 마지막 미션은 '걸어서 세계속으로'라는 이벤트에 참여해서 1만보 이상 걸으면 되는거래. 일단 쉬운 3개라도 먼저 ㄱㄱ하라구. 당첨되면 치킨이랑 갤럭시 갤Z플립도 받을 수 있다구. 미션 4개 다 한사람 한명은 세계여행 시켜준대! 당첨되면 좋겠다...
 8. 이욜ㅋㅋ. 트렌드를 따라갈 줄 아는 MZ세대의 왕세자님이시네ㅋㅋ. 그럼 직항으로 바로 간거야?
 9. 맞아. 요즘 MZ세대들이 자신이 경험하지 못했던 기성세대의 놀이 문화와 먹거리에 재미를 느껴서 옛날의 추억과 감성을 느끼려고 농촌을 찾는대. 그래서 뉴트로 관광이야.
10. 가을에 열리는 DMZ 평화i랜드 뮤직페스티벌이 있어. 교동화개정원 일원에서 열린대. 그리고 화개정원 축제도 열리고!

================================================================================
=== Token ID 53 ('V')이 사용된 문장들 ===

 1. ㅇㅋ 메모 완료! 덕분에 편하게 여행을 즐길 수 있을 것 같아 ㅎㅎ. H워월V~.
 2. VACAY는 서울의 다양한 콘텐츠를 깊이 다루는 거래
 3. VACAY는 해외 지역도 다룰 예정이래. 다음 호는 어디를 다룰까?
 4. 텐센트 위챗, 페루 수출관광진흥위원회 위챗, 저장 OTV 플랫폼을 통해 중국 시청자들에게 페루의 아름다운 경치와 문화를 소개했어.
 5. ATV도 좋은 선택이야
 6. ATV는 사륜오토바이라고도 불리지
 7. 프로덕티비티 포드에는 밝기와 각도 조절이 가능한 독서등과 220V 전원 공급, USB 포트 등이 있어.
 8. V-랜드 물놀이장? 첨 들어봤는데 재미있을까?
 9. V-랜드는 물놀이장뿐 아니라 다른 볼거리도 많아!
10. V-랜드는 관정에서 끌어올린 물로 채워진 풀장이 있어

In [34]:
check_token_context(df, 'res', token_id=76)

=== Token ID 76 ('m')이 사용된 문장들 ===

 1. 미래도시, 과학도시 하면 또 대전이잖아ㅋㅋ. 나노반도체, 우주항공, 바이오헬스, 국방산업 등 4대 핵심산업을 몰입형 실감 미디어 아트로 표현한 쇼가 있었대. 그리고 18m짜리 꿈돌이도 만들었음ㅋㅋ.
 2. 운전경력 2년 이상에 2종 보통면허증 있음 암오케지. 너희 부부는 운전 다 가능하잖냐. 대여 때 운전하기로 계약된 사람에 한해 보험 적용되고 여러 명이 운전할 경우 사전에 고지해야 함. 본인 차량을 화물차, 높이 3m로 설정하고 네비 이용해야 차량이 통과할 수 있는 구간으로 안내받으니 참고해.
 3. 루프탑 인피니티 풀이 있는 리조트야. 길이 20m, 폭 4.5m의 온수풀이 있어
 4. 지상 40m에서 미끄럼틀도 탈 수 있고, 디지털 아트세계도 볼 수 있어
 5. 시드니 하버브리지 클라이밍이라는 체험도 있던데, 134m 꼭대기까지 오르는 거래
 6. 산악지역 구릉형 코스로 해발 700m에 위치해 있어
 7. 시코쓰의 칼데라 호수는 깊이가 363m나 되는 거래
 8. 마나이 폭포는 높이가 17m로 박력이 있어!
 9. 그래! 그리고 제주 드림타워 복합리조트는 최고층이 62m야!
10. 응! 8초에 한 번씩 2.4m 파도타기도 가능해!

In [27]:
def check_space_prefix_tokens(df, text_col='res'):
    """공백으로 시작하는 토큰 분석"""
    
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    used_tokens = set(all_tokens)
    
    # 공백으로 시작하는 토큰들
    space_prefix_korean = []
    space_prefix_english = []
    space_prefix_digit = []
    space_prefix_special = []
    
    for token_id in used_tokens:
        decoded = tokenizer.decode([token_id])
        
        # 공백으로 시작하는지 확인
        if decoded.startswith(' '):
            rest = decoded[1:]  # 공백 제거
            
            if re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', rest):
                space_prefix_korean.append((token_id, decoded, token_counts[token_id]))
            elif re.search(r'[a-zA-Z]', rest):
                space_prefix_english.append((token_id, decoded, token_counts[token_id]))
            elif re.search(r'[0-9]', rest):
                space_prefix_digit.append((token_id, decoded, token_counts[token_id]))
            else:
                space_prefix_special.append((token_id, decoded, token_counts[token_id]))
    
    # 정렬 (빈도순)
    space_prefix_korean.sort(key=lambda x: x[2], reverse=True)
    space_prefix_english.sort(key=lambda x: x[2], reverse=True)
    
    print("=" * 80)
    print("공백 접두어 토큰 분석")
    print("=" * 80)
    
    print(f"\n공백+한글: {len(space_prefix_korean):,}개")
    print("상위 30개:")
    for token_id, decoded, count in space_prefix_korean[:30]:
        print(f"  ID {token_id:6d}: '{decoded:20s}' - {count:,}회")
    
    print(f"\n공백+영어: {len(space_prefix_english):,}개")
    print("상위 30개:")
    for token_id, decoded, count in space_prefix_english[:30]:
        print(f"  ID {token_id:6d}: '{decoded:20s}' - {count:,}회")
    
    print(f"\n공백+숫자: {len(space_prefix_digit):,}개")
    if space_prefix_digit:
        for token_id, decoded, count in space_prefix_digit[:10]:
            print(f"  ID {token_id:6d}: '{decoded:20s}' - {count:,}회")
    
    # 재분류
    print("\n" + "=" * 80)
    print("재분류 결과")
    print("=" * 80)
    
    print(f"공백+한글: {len(space_prefix_korean):,}개")
    print(f"공백+영어: {len(space_prefix_english):,}개")
    print(f"공백+숫자: {len(space_prefix_digit):,}개")
    print(f"공백+기타: {len(space_prefix_special):,}개")
    
    return {
        'space_korean': space_prefix_korean,
        'space_english': space_prefix_english,
        'space_digit': space_prefix_digit
    }

# 실행
space_tokens = check_space_prefix_tokens(df, 'res')

================================================================================
공백 접두어 토큰 분석
================================================================================

공백+한글: 651개
상위 30개:
  ID  35509: ' 가                  ' - 74,600회
  ID  28733: ' 수                  ' - 71,625회
  ID 126352: ' 거                  ' - 66,350회
  ID 127353: ' 있어                 ' - 50,453회
  ID  60716: ' 해                  ' - 32,491회
  ID  78374: ' 같                  ' - 30,408회
  ID  54116: ' 기                  ' - 29,571회
  ID  71108: ' 것                  ' - 28,737회
  ID  54825: ' 그                  ' - 27,523회
  ID  35339: ' 있                  ' - 26,485회
  ID 142815: ' 여행                 ' - 26,425회
  ID  73518: ' 나                  ' - 24,421회
  ID 129273: ' 어떤                 ' - 22,940회
  ID 125953: ' 좋                  ' - 22,416회
  ID  56419: ' 전                  ' - 21,475회
  ID  64521: ' 있는                 ' - 20,834회
  ID 125466: ' 공                  ' - 20,703회
  ID  63332: ' 보                  ' - 20,128회
  ID 126366: ' 더                  ' - 18,754회
  ID  95617: ' 예                  ' - 18,337회
  ID 131050: ' 같이                 ' - 18,187회
  ID  55673: ' 주                  ' - 17,951회
  ID  53900: ' 하                  ' - 17,703회
  ID  60960: ' 대                  ' - 16,559회
  ID 141357: ' 그럼                 ' - 16,511회
  ID  48408: ' 아                  ' - 16,331회
  ID  23084: ' 이                  ' - 15,946회
  ID 130689: ' 있을                 ' - 15,479회
  ID  44518: ' 시                  ' - 15,408회
  ID  95002: ' 할                  ' - 15,290회

공백+영어: 1,928개
상위 30개:
  ID    730: ' K                  ' - 1,049회
  ID    479: ' G                  ' - 952회
  ID    386: ' M                  ' - 503회
  ID   6159: ' CG                 ' - 336회
  ID    328: ' S                  ' - 257회
  ID    362: ' A                  ' - 253회
  ID  20192: ' DM                 ' - 221회
  ID    451: ' N                  ' - 216회
  ID    425: ' B                  ' - 164회
  ID  21387: ' DJ                 ' - 154회
  ID  15235: ' AI                 ' - 141회
  ID   5883: ' TV                 ' - 129회
  ID  19168: ' VR                 ' - 117회
  ID    431: ' R                  ' - 116회
  ID  35069: ' VIP                ' - 116회
  ID    422: ' D                  ' - 113회
  ID    468: ' E                  ' - 109회
  ID  13113: ' LED                ' - 105회
  ID  23403: ' LG                 ' - 105회
  ID    647: ' V                  ' - 102회
  ID  38699: ' QR                 ' - 94회
  ID    356: ' C                  ' - 88회
  ID    444: ' L                  ' - 84회
  ID  82068: ' BTS                ' - 84회
  ID  93301: ' OST                ' - 81회
  ID    547: ' U                  ' - 79회
  ID   8700: ' IT                 ' - 79회
  ID    304: ' in                 ' - 77회
  ID    384: ' e                  ' - 75회
  ID  23463: ' SF                 ' - 75회

공백+숫자: 0개

================================================================================
재분류 결과
================================================================================
공백+한글: 651개
공백+영어: 1,928개
공백+숫자: 0개
공백+기타: 129개

In [28]:
def analyze_vocab_space_korean(tokenizer):
    """전체 vocab에서 공백+한국어 토큰 분석"""
    
    vocab = tokenizer.get_vocab()
    total_vocab = len(vocab)
    
    # 카테고리별 분류
    space_korean = []      # ' 가', ' 한국' 등
    space_english = []     # ' K', ' the' 등
    pure_korean = []       # '가', '한국' (공백 없이)
    pure_english = []      # 'K', 'the' (공백 없이)
    
    for token_str, token_id in vocab.items():
        try:
            decoded = tokenizer.decode([token_id])
        except:
            decoded = token_str
        
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        starts_with_space = decoded.startswith(' ')
        
        # 공백으로 시작하는 경우
        if starts_with_space:
            if has_korean:
                space_korean.append((token_id, token_str, decoded))
            elif has_english:
                space_english.append((token_id, token_str, decoded))
        # 공백 없이 시작
        else:
            if has_korean and not has_english:
                pure_korean.append((token_id, token_str, decoded))
            elif has_english and not has_korean:
                pure_english.append((token_id, token_str, decoded))
    
    # 결과 출력
    print("=" * 80)
    print("전체 Vocab 분석: 공백 접두어 기준")
    print("=" * 80)
    print(f"\n전체 vocab: {total_vocab:,}개\n")
    
    print(f"{'공백+한글':20s}: {len(space_korean):6,}개 ({len(space_korean)/total_vocab*100:5.2f}%)")
    print(f"{'순수 한글':20s}: {len(pure_korean):6,}개 ({len(pure_korean)/total_vocab*100:5.2f}%)")
    print(f"{'한글 전체':20s}: {len(space_korean)+len(pure_korean):6,}개 ({(len(space_korean)+len(pure_korean))/total_vocab*100:5.2f}%)")
    print()
    print(f"{'공백+영어':20s}: {len(space_english):6,}개 ({len(space_english)/total_vocab*100:5.2f}%)")
    print(f"{'순수 영어':20s}: {len(pure_english):6,}개 ({len(pure_english)/total_vocab*100:5.2f}%)")
    print(f"{'영어 전체':20s}: {len(space_english)+len(pure_english):6,}개 ({(len(space_english)+len(pure_english))/total_vocab*100:5.2f}%)")
    
    # 샘플 출력
    print("\n" + "=" * 80)
    print("공백+한글 샘플 30개")
    print("=" * 80)
    for token_id, token_str, decoded in space_korean[:30]:
        print(f"  ID {token_id:6d}: '{decoded}'")
    
    print("\n" + "=" * 80)
    print("순수 한글 샘플 30개")
    print("=" * 80)
    for token_id, token_str, decoded in pure_korean[:30]:
        print(f"  ID {token_id:6d}: '{decoded}'")
    
    return {
        'space_korean': len(space_korean),
        'pure_korean': len(pure_korean),
        'space_english': len(space_english),
        'pure_english': len(pure_english),
        'total_korean': len(space_korean) + len(pure_korean),
        'total_english': len(space_english) + len(pure_english)
    }

# 실행
vocab_stats = analyze_vocab_space_korean(tokenizer)

================================================================================
전체 Vocab 분석: 공백 접두어 기준
================================================================================

전체 vocab: 151,669개

공백+한글               :    667개 ( 0.44%)
순수 한글               :  2,865개 ( 1.89%)
한글 전체               :  3,532개 ( 2.33%)

공백+영어               : 45,201개 (29.80%)
순수 영어               : 48,687개 (32.10%)
영어 전체               : 93,888개 (61.90%)

================================================================================
공백+한글 샘플 30개
================================================================================
  ID 125640: ' 또'
  ID 139495: ' 작업'
  ID  81058: ' 처리'
  ID 128605: ' 대한'
  ID 137119: ' 있다고'
  ID 134808: ' 아닌'
  ID 126423: ' 실'
  ID 142180: ' 가운데'
  ID  75232: ' 객체'
  ID 129242: ' 재'
  ID  71015: ' 로'
  ID  45563: ' 값'
  ID 138098: ' 참여'
  ID 124830: ' 우리'
  ID 137769: ' 먼저'
  ID 136105: ' 모르'
  ID 130679: ' 위한'
  ID 141693: ' 겁'
  ID 126523: ' 아니'
  ID 141258: ' 있지만'
  ID 139764: ' 사진'
  ID 124973: ' 국'
  ID 142179: ' 가운'
  ID 135839: ' 받아'
  ID 143333: ' 국회'
  ID  83596: ' 받'
  ID 124657: ' 우'
  ID 139484: ' 그것을'
  ID 143522: ' 컴퓨터'
  ID 134583: ' 새'

================================================================================
순수 한글 샘플 30개
================================================================================
  ID 136559: '주시'
  ID 146057: '쏴'
  ID 150870: '깸'
  ID 144033: '칼'
  ID 145955: '앳'
  ID 148341: '븅'
  ID 145075: '왈'
  ID 145140: '딛'
  ID 149459: '밢'
  ID 145184: '컫'
  ID 150998: '얠'
  ID 138108: '훈'
  ID 144079: '춘'
  ID 149245: '뀨'
  ID 144163: '슴'
  ID 141142: '붙'
  ID 147135: 'ㅓ'
  ID 151437: '뻅'
  ID 133215: '이고'
  ID 146321: '슛'
  ID 145472: '뻘'
  ID 145951: 'ㅌ'
  ID 149104: '쥑'
  ID 144145: '벤'
  ID 144147: '흡'
  ID 144617: '쌀'
  ID 147013: '뒈'
  ID 149778: '왤'
  ID 135229: '되면'
  ID 151104: '햘'

In [31]:
def count_all_korean_tokens(df, text_col='res'):
    """자음/모음 포함한 전체 한글 토큰"""
    
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    used_tokens = set(all_tokens)
    
    # 4가지로 분류
    space_complete = 0  # ' 가', ' 한글' (공백+완성형)
    pure_complete = 0   # '가', '한글' (완성형만)
    space_jamo = 0      # ' ㄱ', ' ㅋ' (공백+자모)
    pure_jamo = 0       # 'ㄱ', 'ㅋ' (자모만)
    
    space_complete_list = []
    pure_complete_list = []
    space_jamo_list = []
    pure_jamo_list = []
    
    for token_id in used_tokens:
        decoded = tokenizer.decode([token_id])
        
        has_complete = bool(re.search(r'[가-힣]', decoded))
        has_jamo = bool(re.search(r'[ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        starts_with_space = decoded.startswith(' ')
        
        # 영어 섞인 건 제외
        if has_english:
            continue
        
        # 완성형 한글
        if has_complete:
            if starts_with_space:
                space_complete += 1
                space_complete_list.append((token_id, decoded))
            else:
                pure_complete += 1
                pure_complete_list.append((token_id, decoded))
        
        # 자모만 (완성형 없이)
        elif has_jamo:
            if starts_with_space:
                space_jamo += 1
                space_jamo_list.append((token_id, decoded))
            else:
                pure_jamo += 1
                pure_jamo_list.append((token_id, decoded))
    
    # 합계
    total_complete = space_complete + pure_complete
    total_jamo = space_jamo + pure_jamo
    total_korean = total_complete + total_jamo
    
    print("=" * 80)
    print("전체 한글 토큰 (자음/모음 포함)")
    print("=" * 80)
    print(f"\n총 사용 토큰: {len(used_tokens):,}개\n")
    
    print(f"{'완성형 한글':20s}: {total_complete:5,}개 ({total_complete/len(used_tokens)*100:5.2f}%)")
    print(f"  {'- 공백+완성형':18s}: {space_complete:5,}개")
    print(f"  {'- 순수 완성형':18s}: {pure_complete:5,}개")
    print()
    print(f"{'자음/모음':20s}: {total_jamo:5,}개 ({total_jamo/len(used_tokens)*100:5.2f}%)")
    print(f"  {'- 공백+자모':18s}: {space_jamo:5,}개")
    print(f"  {'- 순수 자모':18s}: {pure_jamo:5,}개")
    print()
    print(f"{'한글 전체':20s}: {total_korean:5,}개 ({total_korean/len(used_tokens)*100:5.2f}%)")
    
    # 샘플 출력
    print("\n" + "=" * 80)
    print("자음/모음 토큰 샘플")
    print("=" * 80)
    
    if space_jamo_list:
        print("\n공백+자모 샘플:")
        for token_id, decoded in space_jamo_list[:20]:
            print(f"  ID {token_id:6d}: '{decoded}'")
    
    if pure_jamo_list:
        print("\n순수 자모 샘플:")
        for token_id, decoded in pure_jamo_list[:20]:
            print(f"  ID {token_id:6d}: '{decoded}'")
    
    return {
        'space_complete': space_complete,
        'pure_complete': pure_complete,
        'space_jamo': space_jamo,
        'pure_jamo': pure_jamo,
        'total_korean': total_korean
    }

# 실행
korean_full = count_all_korean_tokens(df, 'res')

================================================================================
전체 한글 토큰 (자음/모음 포함)
================================================================================

총 사용 토큰: 7,242개

완성형 한글              : 2,585개 (35.69%)
  - 공백+완성형          :   651개
  - 순수 완성형          : 1,934개

자음/모음               :    25개 ( 0.35%)
  - 공백+자모           :     0개
  - 순수 자모           :    25개

한글 전체               : 2,610개 (36.04%)

================================================================================
자음/모음 토큰 샘플
================================================================================

순수 자모 샘플:
  ID 144030: 'ㅎ'
  ID 144065: 'ㅠ'
  ID 144410: 'ㅋ'
  ID 144579: 'ㅜ'
  ID 144681: 'ㅇ'
  ID 144724: 'ㅡ'
  ID 145017: 'ㄱ'
  ID 145039: 'ㄷ'
  ID 145089: 'ㄴ'
  ID 145162: 'ㅣ'
  ID 145220: 'ㅅ'
  ID 145417: 'ㅁ'
  ID 145442: 'ㄹ'
  ID 145506: 'ㅂ'
  ID 145697: 'ㅈ'
  ID 145826: 'ㅍ'
  ID 145898: 'ㅉ'
  ID 145951: 'ㅌ'
  ID 146076: 'ㄲ'
  ID 146457: 'ㅊ'

In [36]:
def analyze_top_frequent_korean(df, text_col='res', top_n=100):
    """상위 빈도 토큰 중 한국어 비율 (공백+한국어 포함)"""
    
    # 모든 토큰 수집
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    # 상위 N개
    top_tokens = token_counts.most_common(top_n)
    
    # 카테고리 분류
    korean_tokens = []
    english_tokens = []
    digit_tokens = []
    special_tokens = []
    etc_tokens = []
    
    for token_id, count in top_tokens:
        decoded = tokenizer.decode([token_id])
        
        # 한글 (완성형 + 자모)
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        has_digit = bool(re.search(r'[0-9]', decoded))
        
        # 한글 포함 (공백 상관없이, 영어 없으면 한글로 분류)
        if has_korean and not has_english:
            korean_tokens.append((token_id, decoded, count))
        elif has_english and not has_korean:
            english_tokens.append((token_id, decoded, count))
        elif has_digit:
            digit_tokens.append((token_id, decoded, count))
        elif re.match(r'^[^\w가-힣ㄱ-ㅎㅏ-ㅣ\s]+$', decoded.strip()):
            special_tokens.append((token_id, decoded, count))
        else:
            etc_tokens.append((token_id, decoded, count))
    
    # 빈도 합계
    korean_freq = sum(x[2] for x in korean_tokens)
    english_freq = sum(x[2] for x in english_tokens)
    digit_freq = sum(x[2] for x in digit_tokens)
    special_freq = sum(x[2] for x in special_tokens)
    etc_freq = sum(x[2] for x in etc_tokens)
    
    total_top_freq = sum(x[1] for x in top_tokens)
    total_all_tokens = len(all_tokens)
    
    print("=" * 80)
    print(f"상위 {top_n}개 빈도 토큰 분석 (공백+한국어 포함)")
    print("=" * 80)
    
    print(f"\n=== 토큰 종류 개수 ===")
    print(f"한글      : {len(korean_tokens):3d}개 ({len(korean_tokens)/top_n*100:5.1f}%)")
    print(f"영어      : {len(english_tokens):3d}개 ({len(english_tokens)/top_n*100:5.1f}%)")
    print(f"숫자      : {len(digit_tokens):3d}개 ({len(digit_tokens)/top_n*100:5.1f}%)")
    print(f"특수문자   : {len(special_tokens):3d}개 ({len(special_tokens)/top_n*100:5.1f}%)")
    print(f"기타      : {len(etc_tokens):3d}개 ({len(etc_tokens)/top_n*100:5.1f}%)")
    
    print(f"\n=== 실제 사용 빈도 (상위 {top_n}개 토큰의 총 출현 횟수) ===")
    print(f"한글      : {korean_freq:10,}회 ({korean_freq/total_top_freq*100:5.2f}%)")
    print(f"영어      : {english_freq:10,}회 ({english_freq/total_top_freq*100:5.2f}%)")
    print(f"숫자      : {digit_freq:10,}회 ({digit_freq/total_top_freq*100:5.2f}%)")
    print(f"특수문자   : {special_freq:10,}회 ({special_freq/total_top_freq*100:5.2f}%)")
    print(f"기타      : {etc_freq:10,}회 ({etc_freq/total_top_freq*100:5.2f}%)")
    
    print(f"\n상위 {top_n}개 토큰이 전체의 {total_top_freq/total_all_tokens*100:.2f}% 차지")
    
    # 한글 토큰 상세
    print("\n" + "=" * 80)
    print(f"상위 {top_n}개 중 한글 토큰 전체 목록 ({len(korean_tokens)}개)")
    print("=" * 80)
    for i, (token_id, decoded, count) in enumerate(korean_tokens, 1):
        # 공백 표시
        display = decoded.replace(' ', '␣')
        print(f"{i:3d}. ID {token_id:6d}: '{display:20s}' - {count:,}회")
    
    # 영어 토큰도 출력
    print("\n" + "=" * 80)
    print(f"상위 {top_n}개 중 영어 토큰 전체 목록 ({len(english_tokens)}개)")
    print("=" * 80)
    if len(english_tokens) > 0:
        for i, (token_id, decoded, count) in enumerate(english_tokens, 1):
            display = decoded.replace(' ', '␣')
            print(f"{i:3d}. ID {token_id:6d}: '{display:20s}' - {count:,}회")
    else:
        print("(영어 토큰 없음)")
    
    # 특수문자도 출력
    print("\n" + "=" * 80)
    print(f"상위 {top_n}개 중 특수문자 토큰 ({len(special_tokens)}개)")
    print("=" * 80)
    if len(special_tokens) > 0:
        for i, (token_id, decoded, count) in enumerate(special_tokens, 1):
            display = repr(decoded)  # 특수문자는 repr로
            print(f"{i:3d}. ID {token_id:6d}: {display:20s} - {count:,}회")
    else:
        print("(특수문자 토큰 없음)")
    
    return {
        'korean_count': len(korean_tokens),
        'english_count': len(english_tokens),
        'korean_freq': korean_freq,
        'english_freq': english_freq,
        'korean_tokens': korean_tokens,
        'english_tokens': english_tokens,
        'special_tokens': special_tokens
    }

# 실행
result = analyze_top_frequent_korean(df, 'res', top_n=100)

================================================================================
상위 100개 빈도 토큰 분석 (공백+한국어 포함)
================================================================================

=== 토큰 종류 개수 ===
한글      :  74개 ( 74.0%)
영어      :   0개 (  0.0%)
숫자      :   3개 (  3.0%)
특수문자   :  22개 ( 22.0%)
기타      :   1개 (  1.0%)

=== 실제 사용 빈도 (상위 100개 토큰의 총 출현 횟수) ===
한글      :  3,365,983회 (69.97%)
영어      :          0회 ( 0.00%)
숫자      :     84,998회 ( 1.77%)
특수문자   :  1,272,291회 (26.45%)
기타      :     87,224회 ( 1.81%)

상위 100개 토큰이 전체의 47.25% 차지

================================================================================
상위 100개 중 한글 토큰 전체 목록 (74개)
================================================================================
  1. ID  12802: '이                   ' - 158,335회
  2. ID  47985: '도                   ' - 138,257회
  3. ID  17877: '을                   ' - 126,073회
  4. ID  89659: '야                   ' - 111,902회
  5. ID  52959: '아                   ' - 109,757회
  6. ID  31079: '어                   ' - 96,570회
  7. ID  19969: '가                   ' - 81,173회
  8. ID  19391: '에                   ' - 80,085회
  9. ID  35509: '␣가                  ' - 74,600회
 10. ID  21329: '지                   ' - 71,757회
 11. ID  28733: '␣수                  ' - 71,625회
 12. ID  16560: '는                   ' - 68,726회
 13. ID  33704: '은                   ' - 68,719회
 14. ID 126352: '␣거                  ' - 66,350회
 15. ID 144410: 'ㅋ                   ' - 64,701회
 16. ID  20401: '의                   ' - 59,836회
 17. ID  26698: '서                   ' - 58,874회
 18. ID  34395: '고                   ' - 58,605회
 19. ID  60315: '나                   ' - 58,598회
 20. ID  66845: '대                   ' - 56,851회
 21. ID  48606: '그                   ' - 56,150회
 22. ID  17380: '로                   ' - 55,471회
 23. ID  56475: '에서                  ' - 50,996회
 24. ID 127353: '␣있어                 ' - 50,453회
 25. ID  23573: '한                   ' - 49,986회
 26. ID  28002: '리                   ' - 48,355회
 27. ID  25715: '자                   ' - 47,747회
 28. ID  33883: '해                   ' - 45,817회
 29. ID  18411: '를                   ' - 44,967회
 30. ID  80573: '와                   ' - 41,949회
 31. ID 139772: '그래                  ' - 39,483회
 32. ID  32290: '면                   ' - 37,494회
 33. ID 144330: '맞                   ' - 36,146회
 34. ID  13146: '다                   ' - 35,705회
 35. ID  24897: '스                   ' - 35,226회
 36. ID  20487: '기                   ' - 34,787회
 37. ID  31328: '인                   ' - 34,759회
 38. ID  29326: '시                   ' - 34,654회
 39. ID  32077: '일                   ' - 34,067회
 40. ID  60716: '␣해                  ' - 32,491회
 41. ID 127816: '겠다                  ' - 31,428회
 42. ID  78374: '␣같                  ' - 30,408회
 43. ID  54116: '␣기                  ' - 29,571회
 44. ID  57801: '게                   ' - 29,440회
 45. ID  71108: '␣것                  ' - 28,737회
 46. ID 126730: '네                   ' - 28,494회
 47. ID  54825: '␣그                  ' - 27,523회
 48. ID  53680: '과                   ' - 26,858회
 49. ID  35339: '␣있                  ' - 26,485회
 50. ID 142815: '␣여행                 ' - 26,425회
 51. ID  47836: '할                   ' - 25,942회
 52. ID  60294: '러                   ' - 25,564회
 53. ID 125544: '마                   ' - 25,392회
 54. ID 131518: '응                   ' - 25,206회
 55. ID  28626: '트                   ' - 24,461회
 56. ID  73518: '␣나                  ' - 24,421회
 57. ID  53442: '래                   ' - 24,080회
 58. ID 124667: '까                   ' - 24,045회
 59. ID  56290: '화                   ' - 23,266회
 60. ID 124419: '데                   ' - 23,119회
 61. ID  88259: '구                   ' - 23,105회
 62. ID 129273: '␣어떤                 ' - 22,940회
 63. ID  54321: '원                   ' - 22,661회
 64. ID 126746: '루                   ' - 22,516회
 65. ID 125953: '␣좋                  ' - 22,416회
 66. ID  50340: '라                   ' - 22,046회
 67. ID  54330: '주                   ' - 22,008회
 68. ID  41671: '보                   ' - 21,657회
 69. ID 124923: '겠                   ' - 21,493회
 70. ID  56419: '␣전                  ' - 21,475회
 71. ID 126204: '하고                  ' - 21,441회
 72. ID  42039: '으로                  ' - 21,297회
 73. ID 144030: 'ㅎ                   ' - 20,993회
 74. ID  83036: '니                   ' - 20,973회

================================================================================
상위 100개 중 영어 토큰 전체 목록 (0개)
================================================================================
(영어 토큰 없음)

================================================================================
상위 100개 중 특수문자 토큰 (22개)
================================================================================
  1. ID      0: '!'                  - 212,473회
  2. ID     13: '.'                  - 174,155회
  3. ID     30: '?'                  - 148,080회
  4. ID     11: ','                  - 93,040회
  5. ID   5140: ' �'                 - 88,371회
  6. ID  10764: ' �'                 - 60,189회
  7. ID    120: '�'                  - 53,746회
  8. ID    230: '�'                  - 42,560회
  9. ID    254: '�'                  - 42,451회
 10. ID    112: '�'                  - 37,652회
 11. ID    238: '�'                  - 36,062회
 12. ID    250: '�'                  - 33,150회
 13. ID   3315: ' �'                 - 31,422회
 14. ID    105: '�'                  - 29,227회
 15. ID    116: '�'                  - 27,060회
 16. ID   8620: ' �'                 - 25,561회
 17. ID    222: '�'                  - 24,131회
 18. ID  28927: ' �'                 - 24,030회
 19. ID    234: '�'                  - 23,705회
 20. ID  45130: ' �'                 - 22,384회
 21. ID    246: '�'                  - 21,468회
 22. ID    242: '�'                  - 21,374회

In [37]:
result = analyze_top_frequent_korean(df, 'res', top_n=200)

================================================================================
상위 200개 빈도 토큰 분석 (공백+한국어 포함)
================================================================================

=== 토큰 종류 개수 ===
한글      : 146개 ( 73.0%)
영어      :   0개 (  0.0%)
숫자      :   4개 (  2.0%)
특수문자   :  49개 ( 24.5%)
기타      :   1개 (  0.5%)

=== 실제 사용 빈도 (상위 200개 토큰의 총 출현 횟수) ===
한글      :  4,519,969회 (70.56%)
영어      :          0회 ( 0.00%)
숫자      :     97,306회 ( 1.52%)
특수문자   :  1,701,310회 (26.56%)
기타      :     87,224회 ( 1.36%)

상위 200개 토큰이 전체의 62.92% 차지

================================================================================
상위 200개 중 한글 토큰 전체 목록 (146개)
================================================================================
  1. ID  12802: '이                   ' - 158,335회
  2. ID  47985: '도                   ' - 138,257회
  3. ID  17877: '을                   ' - 126,073회
  4. ID  89659: '야                   ' - 111,902회
  5. ID  52959: '아                   ' - 109,757회
  6. ID  31079: '어                   ' - 96,570회
  7. ID  19969: '가                   ' - 81,173회
  8. ID  19391: '에                   ' - 80,085회
  9. ID  35509: '␣가                  ' - 74,600회
 10. ID  21329: '지                   ' - 71,757회
 11. ID  28733: '␣수                  ' - 71,625회
 12. ID  16560: '는                   ' - 68,726회
 13. ID  33704: '은                   ' - 68,719회
 14. ID 126352: '␣거                  ' - 66,350회
 15. ID 144410: 'ㅋ                   ' - 64,701회
 16. ID  20401: '의                   ' - 59,836회
 17. ID  26698: '서                   ' - 58,874회
 18. ID  34395: '고                   ' - 58,605회
 19. ID  60315: '나                   ' - 58,598회
 20. ID  66845: '대                   ' - 56,851회
 21. ID  48606: '그                   ' - 56,150회
 22. ID  17380: '로                   ' - 55,471회
 23. ID  56475: '에서                  ' - 50,996회
 24. ID 127353: '␣있어                 ' - 50,453회
 25. ID  23573: '한                   ' - 49,986회
 26. ID  28002: '리                   ' - 48,355회
 27. ID  25715: '자                   ' - 47,747회
 28. ID  33883: '해                   ' - 45,817회
 29. ID  18411: '를                   ' - 44,967회
 30. ID  80573: '와                   ' - 41,949회
 31. ID 139772: '그래                  ' - 39,483회
 32. ID  32290: '면                   ' - 37,494회
 33. ID 144330: '맞                   ' - 36,146회
 34. ID  13146: '다                   ' - 35,705회
 35. ID  24897: '스                   ' - 35,226회
 36. ID  20487: '기                   ' - 34,787회
 37. ID  31328: '인                   ' - 34,759회
 38. ID  29326: '시                   ' - 34,654회
 39. ID  32077: '일                   ' - 34,067회
 40. ID  60716: '␣해                  ' - 32,491회
 41. ID 127816: '겠다                  ' - 31,428회
 42. ID  78374: '␣같                  ' - 30,408회
 43. ID  54116: '␣기                  ' - 29,571회
 44. ID  57801: '게                   ' - 29,440회
 45. ID  71108: '␣것                  ' - 28,737회
 46. ID 126730: '네                   ' - 28,494회
 47. ID  54825: '␣그                  ' - 27,523회
 48. ID  53680: '과                   ' - 26,858회
 49. ID  35339: '␣있                  ' - 26,485회
 50. ID 142815: '␣여행                 ' - 26,425회
 51. ID  47836: '할                   ' - 25,942회
 52. ID  60294: '러                   ' - 25,564회
 53. ID 125544: '마                   ' - 25,392회
 54. ID 131518: '응                   ' - 25,206회
 55. ID  28626: '트                   ' - 24,461회
 56. ID  73518: '␣나                  ' - 24,421회
 57. ID  53442: '래                   ' - 24,080회
 58. ID 124667: '까                   ' - 24,045회
 59. ID  56290: '화                   ' - 23,266회
 60. ID 124419: '데                   ' - 23,119회
 61. ID  88259: '구                   ' - 23,105회
 62. ID 129273: '␣어떤                 ' - 22,940회
 63. ID  54321: '원                   ' - 22,661회
 64. ID 126746: '루                   ' - 22,516회
 65. ID 125953: '␣좋                  ' - 22,416회
 66. ID  50340: '라                   ' - 22,046회
 67. ID  54330: '주                   ' - 22,008회
 68. ID  41671: '보                   ' - 21,657회
 69. ID 124923: '겠                   ' - 21,493회
 70. ID  56419: '␣전                  ' - 21,475회
 71. ID 126204: '하고                  ' - 21,441회
 72. ID  42039: '으로                  ' - 21,297회
 73. ID 144030: 'ㅎ                   ' - 20,993회
 74. ID  83036: '니                   ' - 20,973회
 75. ID 144681: 'ㅇ                   ' - 20,914회
 76. ID  65865: '전                   ' - 20,903회
 77. ID  64521: '␣있는                 ' - 20,834회
 78. ID 125466: '␣공                  ' - 20,703회
 79. ID 125568: '연                   ' - 20,573회
 80. ID  63332: '␣보                  ' - 20,128회
 81. ID 137771: '짜                   ' - 20,073회
 82. ID  16186: '하                   ' - 19,809회
 83. ID 126377: '에는                  ' - 19,227회
 84. ID  85057: '산                   ' - 18,943회
 85. ID 137613: '봐                   ' - 18,865회
 86. ID  56039: '미                   ' - 18,810회
 87. ID 126366: '␣더                  ' - 18,754회
 88. ID  76337: '식                   ' - 18,624회
 89. ID  40853: '장                   ' - 18,595회
 90. ID 144135: '알                   ' - 18,414회
 91. ID  95617: '␣예                  ' - 18,337회
 92. ID 131050: '␣같이                 ' - 18,187회
 93. ID 126253: '들이                  ' - 17,981회
 94. ID  55673: '␣주                  ' - 17,951회
 95. ID  92192: '거                   ' - 17,926회
 96. ID  72553: '만                   ' - 17,742회
 97. ID  53900: '␣하                  ' - 17,703회
 98. ID  42905: '하는                  ' - 17,696회
 99. ID  37087: '제                   ' - 17,663회
100. ID  29281: '정                   ' - 17,259회
101. ID  55054: '사                   ' - 17,235회
102. ID  85251: '진                   ' - 17,069회
103. ID  40281: '우                   ' - 16,933회
104. ID  55902: '상                   ' - 16,880회
105. ID  60960: '␣대                  ' - 16,559회
106. ID 141357: '␣그럼                 ' - 16,511회
107. ID 125894: '럼                   ' - 16,394회
108. ID  48408: '␣아                  ' - 16,331회
109. ID 125476: '려                   ' - 16,146회
110. ID  23084: '␣이                  ' - 15,946회
111. ID  29346: '드                   ' - 15,651회
112. ID 125199: '었                   ' - 15,599회
113. ID 130689: '␣있을                 ' - 15,479회
114. ID 130109: '워                   ' - 15,411회
115. ID  44518: '␣시                  ' - 15,408회
116. ID  95002: '␣할                  ' - 15,290회
117. ID  58677: '␣인                  ' - 15,024회
118. ID  57089: '동                   ' - 14,789회
119. ID  93672: '운                   ' - 14,733회
120. ID  92751: '␣관                  ' - 14,648회
121. ID  57026: '여                   ' - 14,641회
122. ID 128719: '␣그리고                ' - 14,290회
123. ID 126310: '␣유                  ' - 14,070회
124. ID  43590: '소                   ' - 14,029회
125. ID 124780: '관                   ' - 14,017회
126. ID  78125: '공                   ' - 13,988회
127. ID  57268: '오                   ' - 13,914회
128. ID 130105: '길                   ' - 13,891회
129. ID 128878: '까지                  ' - 13,879회
130. ID  61298: '␣한                  ' - 13,538회
131. ID 129034: '천                   ' - 13,473회
132. ID 126673: '레                   ' - 13,445회
133. ID 128514: '월                   ' - 13,319회
134. ID 124785: '국                   ' - 13,257회
135. ID 143586: '␣작품                 ' - 13,223회
136. ID  48431: '음                   ' - 13,040회
137. ID 126251: '물                   ' - 12,852회
138. ID  23259: '수                   ' - 12,755회
139. ID 126861: '광                   ' - 12,541회
140. ID 129392: '␣도                  ' - 12,394회
141. ID  65306: '경                   ' - 12,292회
142. ID  70582: '비                   ' - 12,228회
143. ID 129242: '␣재                  ' - 12,186회
144. ID  32831: '성                   ' - 12,101회
145. ID 126551: '는데                  ' - 12,060회
146. ID 132968: '␣좋은                 ' - 11,913회

================================================================================
상위 200개 중 영어 토큰 전체 목록 (0개)
================================================================================
(영어 토큰 없음)

================================================================================
상위 200개 중 특수문자 토큰 (49개)
================================================================================
  1. ID      0: '!'                  - 212,473회
  2. ID     13: '.'                  - 174,155회
  3. ID     30: '?'                  - 148,080회
  4. ID     11: ','                  - 93,040회
  5. ID   5140: ' �'                 - 88,371회
  6. ID  10764: ' �'                 - 60,189회
  7. ID    120: '�'                  - 53,746회
  8. ID    230: '�'                  - 42,560회
  9. ID    254: '�'                  - 42,451회
 10. ID    112: '�'                  - 37,652회
 11. ID    238: '�'                  - 36,062회
 12. ID    250: '�'                  - 33,150회
 13. ID   3315: ' �'                 - 31,422회
 14. ID    105: '�'                  - 29,227회
 15. ID    116: '�'                  - 27,060회
 16. ID   8620: ' �'                 - 25,561회
 17. ID    222: '�'                  - 24,131회
 18. ID  28927: ' �'                 - 24,030회
 19. ID    234: '�'                  - 23,705회
 20. ID  45130: ' �'                 - 22,384회
 21. ID    246: '�'                  - 21,468회
 22. ID    242: '�'                  - 21,374회
 23. ID  16751: ' �'                 - 20,653회
 24. ID    101: '�'                  - 20,634회
 25. ID    255: '�'                  - 20,071회
 26. ID    114: '�'                  - 19,889회
 27. ID    121: '�'                  - 19,819회
 28. ID    226: '�'                  - 19,701회
 29. ID 132376: ' �'                 - 19,280회
 30. ID    117: '�'                  - 19,075회
 31. ID    108: '�'                  - 18,366회
 32. ID    111: '�'                  - 17,488회
 33. ID    235: '�'                  - 17,290회
 34. ID  48364: ' �'                 - 16,265회
 35. ID  30520: ' �'                 - 16,140회
 36. ID    251: '�'                  - 16,025회
 37. ID  74884: ' �'                 - 14,804회
 38. ID    228: '�'                  - 14,196회
 39. ID    233: '�'                  - 13,443회
 40. ID    239: '�'                  - 13,428회
 41. ID     97: '�'                  - 13,333회
 42. ID  16778: ' �'                 - 13,281회
 43. ID  48108: ' �'                 - 13,153회
 44. ID  32985: ' �'                 - 12,660회
 45. ID    236: '�'                  - 12,208회
 46. ID 137767: ' �'                 - 12,069회
 47. ID    243: '�'                  - 11,984회
 48. ID  98734: '��'                 - 11,940회
 49. ID  36330: ' �'                 - 11,824회

In [39]:
# 한글 토큰의 빈도 분포 확인
def analyze_korean_token_distribution(df, text_col='res'):
    """한글 토큰들이 얼마나 골고루 쓰였는지 확인"""
    
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    # 한글 토큰만 추출
    korean_token_counts = []
    
    for token_id, count in token_counts.items():
        decoded = tokenizer.decode([token_id])
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        
        if has_korean and not has_english:
            korean_token_counts.append((token_id, decoded, count))
    
    # 빈도순 정렬
    korean_token_counts.sort(key=lambda x: x[2], reverse=True)
    
    total_korean_tokens = len(korean_token_counts)
    total_korean_freq = sum(x[2] for x in korean_token_counts)
    
    # 상위 N개가 차지하는 비율
    top10_freq = sum(x[2] for x in korean_token_counts[:10])
    top50_freq = sum(x[2] for x in korean_token_counts[:50])
    top100_freq = sum(x[2] for x in korean_token_counts[:100])
    top200_freq = sum(x[2] for x in korean_token_counts[:200])
    
    print("=" * 80)
    print("한글 토큰 빈도 집중도 분석")
    print("=" * 80)
    print(f"\n총 한글 토큰 종류: {total_korean_tokens:,}개")
    print(f"총 한글 토큰 빈도: {total_korean_freq:,}회\n")
    
    print(f"상위 10개 한글 토큰: {top10_freq:,}회 ({top10_freq/total_korean_freq*100:5.2f}%)")
    print(f"상위 50개 한글 토큰: {top50_freq:,}회 ({top50_freq/total_korean_freq*100:5.2f}%)")
    print(f"상위 100개 한글 토큰: {top100_freq:,}회 ({top100_freq/total_korean_freq*100:5.2f}%)")
    print(f"상위 200개 한글 토큰: {top200_freq:,}회 ({top200_freq/total_korean_freq*100:5.2f}%)")
    
    # 상위 한글 토큰 출력
    print("\n" + "=" * 80)
    print("가장 많이 사용된 한글 토큰 30개")
    print("=" * 80)
    for i, (token_id, decoded, count) in enumerate(korean_token_counts[:30], 1):
        display = decoded.replace(' ', '␣')
        print(f"{i:3d}. '{display:15s}' - {count:,}회 ({count/total_korean_freq*100:.2f}%)")
    
    # 하위 토큰들
    print("\n" + "=" * 80)
    print("거의 안 쓰인 한글 토큰 (1-5회만 사용)")
    print("=" * 80)
    
    rare_tokens = [x for x in korean_token_counts if x[2] <= 5]
    print(f"5회 이하 사용: {len(rare_tokens):,}개 ({len(rare_tokens)/total_korean_tokens*100:.1f}%)")
    
    if rare_tokens:
        print("\n예시 20개:")
        for token_id, decoded, count in rare_tokens[:20]:
            display = decoded.replace(' ', '␣')
            print(f"  '{display:15s}' - {count}회")
    
    return korean_token_counts

# 실행
korean_dist = analyze_korean_token_distribution(df, 'res')

================================================================================
한글 토큰 빈도 집중도 분석
================================================================================

총 한글 토큰 종류: 2,610개
총 한글 토큰 빈도: 7,702,061회

상위 10개 한글 토큰: 1,048,509회 (13.61%)
상위 50개 한글 토큰: 2,813,466회 (36.53%)
상위 100개 한글 토큰: 3,858,597회 (50.10%)
상위 200개 한글 토큰: 5,072,144회 (65.85%)

================================================================================
가장 많이 사용된 한글 토큰 30개
================================================================================
  1. '이              ' - 158,335회 (2.06%)
  2. '도              ' - 138,257회 (1.80%)
  3. '을              ' - 126,073회 (1.64%)
  4. '야              ' - 111,902회 (1.45%)
  5. '아              ' - 109,757회 (1.43%)
  6. '어              ' - 96,570회 (1.25%)
  7. '가              ' - 81,173회 (1.05%)
  8. '에              ' - 80,085회 (1.04%)
  9. '␣가             ' - 74,600회 (0.97%)
 10. '지              ' - 71,757회 (0.93%)
 11. '␣수             ' - 71,625회 (0.93%)
 12. '는              ' - 68,726회 (0.89%)
 13. '은              ' - 68,719회 (0.89%)
 14. '␣거             ' - 66,350회 (0.86%)
 15. 'ㅋ              ' - 64,701회 (0.84%)
 16. '의              ' - 59,836회 (0.78%)
 17. '서              ' - 58,874회 (0.76%)
 18. '고              ' - 58,605회 (0.76%)
 19. '나              ' - 58,598회 (0.76%)
 20. '대              ' - 56,851회 (0.74%)
 21. '그              ' - 56,150회 (0.73%)
 22. '로              ' - 55,471회 (0.72%)
 23. '에서             ' - 50,996회 (0.66%)
 24. '␣있어            ' - 50,453회 (0.66%)
 25. '한              ' - 49,986회 (0.65%)
 26. '리              ' - 48,355회 (0.63%)
 27. '자              ' - 47,747회 (0.62%)
 28. '해              ' - 45,817회 (0.59%)
 29. '를              ' - 44,967회 (0.58%)
 30. '와              ' - 41,949회 (0.54%)

================================================================================
거의 안 쓰인 한글 토큰 (1-5회만 사용)
================================================================================
5회 이하 사용: 300개 (11.5%)

예시 20개:
  '듦              ' - 5회
  '잖아요            ' - 5회
  '횐              ' - 5회
  '찼              ' - 5회
  '댜              ' - 5회
  '곘              ' - 5회
  '␣값을            ' - 5회
  '헙              ' - 5회
  '벵              ' - 5회
  '콸              ' - 5회
  '습니까            ' - 5회
  '껫              ' - 5회
  '첸              ' - 5회
  '껭              ' - 5회
  '왑              ' - 5회
  '춧              ' - 5회
  '뜯              ' - 5회
  '앜              ' - 5회
  '쳇              ' - 5회
  '칫              ' - 5회

In [42]:
def check_response_diversity(df, text_col='res'):
    """응답 다양성 확인"""
    
    total = len(df)
    unique = df[text_col].nunique()
    
    diversity_ratio = unique / total * 100
    avg_repeat = total / unique
    
    print("=" * 80)
    print("응답 다양성 분석")
    print("=" * 80)
    print(f"\n총 샘플: {total:,}개")
    print(f"고유 응답: {unique:,}개")
    print(f"다양성 비율: {diversity_ratio:.2f}%")
    print(f"평균 반복: {avg_repeat:.1f}회\n")
    
    # 가장 많이 반복된 응답
    print("가장 많이 반복된 응답 20개:")
    for i, (text, count) in enumerate(df[text_col].value_counts().head(20).items(), 1):
        print(f"{i:2d}. {count:4,}회: {text[:80]}")
    
    # 반복 횟수 분포
    repeat_counts = df[text_col].value_counts()
    
    once = (repeat_counts == 1).sum()
    twice_to_5 = ((repeat_counts >= 2) & (repeat_counts <= 5)).sum()
    six_to_10 = ((repeat_counts >= 6) & (repeat_counts <= 10)).sum()
    eleven_to_50 = ((repeat_counts >= 11) & (repeat_counts <= 50)).sum()
    over_50 = (repeat_counts > 50).sum()
    
    print(f"\n반복 횟수 분포:")
    print(f"  1회만: {once:,}개 ({once/unique*100:.1f}%)")
    print(f"  2-5회: {twice_to_5:,}개 ({twice_to_5/unique*100:.1f}%)")
    print(f"  6-10회: {six_to_10:,}개 ({six_to_10/unique*100:.1f}%)")
    print(f"  11-50회: {eleven_to_50:,}개 ({eleven_to_50/unique*100:.1f}%)")
    print(f"  50회 초과: {over_50:,}개 ({over_50/unique*100:.1f}%)")
    
    # 위험도 평가
    print("\n" + "=" * 80)
    print("과적합 위험도 평가")
    print("=" * 80)
    
    if diversity_ratio > 80:
        print("🟢 다양성 우수 (80%+)")
    elif diversity_ratio > 60:
        print("🟡 다양성 보통 (60-80%)")
    elif diversity_ratio > 40:
        print("🟠 다양성 낮음 (40-60%) - 중복 제거 권장")
    else:
        print("🔴 다양성 매우 낮음 (40% 미만) - 심각한 과적합 위험")
    
    if avg_repeat < 2:
        print("🟢 평균 반복 낮음")
    elif avg_repeat < 5:
        print("🟡 평균 반복 보통")
    elif avg_repeat < 10:
        print("🟠 평균 반복 높음")
    else:
        print("🔴 평균 반복 매우 높음 - 심각한 문제")
    
    return {
        'diversity_ratio': diversity_ratio,
        'avg_repeat': avg_repeat,
        'unique': unique
    }

# 실행
check_response_diversity(df, 'res')

================================================================================
응답 다양성 분석
================================================================================

총 샘플: 500,707개
고유 응답: 452,634개
다양성 비율: 90.40%
평균 반복: 1.1회

가장 많이 반복된 응답 20개:
 1.  128회: 너무 기대돼!
 2.  124회: 응! 기대돼!
 3.   99회: 잘 다녀와!
 4.   96회: ㅇㅋㅇㅋ 기대돼!
 5.   93회: 응, 기대돼!
 6.   92회: 그래! 기대돼!
 7.   85회: 기대돼!
 8.   82회: 그래! 같이 가자!
 9.   76회: 그래! 같이 가서 즐거운 시간 보내자!
10.   68회: 나도 기대해!
11.   61회: 나도 기대돼!
12.   61회: 그래! 같이 가자
13.   60회: 그럼 같이 가자!
14.   60회: 그 책은 어떤 내용이야?
15.   52회: 굿굿! 언제 가면 좋을까?
16.   47회: 그래! 그럼 토요일에 가자
17.   44회: 그럼 다음에 같이 가자!
18.   41회: 응, 꼭 가보는 걸 추천해!
19.   41회: 나도 같이 가자!
20.   41회: 안뇽!

반복 횟수 분포:
  1회만: 415,061개 (91.7%)
  2-5회: 36,891개 (8.2%)
  6-10회: 441개 (0.1%)
  11-50회: 226개 (0.0%)
  50회 초과: 15개 (0.0%)

================================================================================
과적합 위험도 평가
================================================================================
🟢 다양성 우수 (80%+)
🟢 평균 반복 낮음

{'diversity_ratio': 90.39897584815073,
 'avg_repeat': 1.1062072226125301,
 'unique': 452634}

In [43]:
from scipy.stats import entropy
from collections import Counter

def token_entropy_diverse_sampling(df, text_col='res', target_size=100000):
    """토큰 엔트로피 높은 샘플 우선 선택"""
    
    def calculate_entropy(text):
        """텍스트의 토큰 분포 엔트로피"""
        tokens = tokenizer.encode(text, add_special_tokens=False)
        if len(tokens) == 0:
            return 0
        
        token_counts = Counter(tokens)
        probs = np.array(list(token_counts.values())) / len(tokens)
        return entropy(probs)
    
    # 각 샘플의 엔트로피 계산
    print("엔트로피 계산 중...")
    df['entropy'] = df[text_col].apply(calculate_entropy)
    
    # 엔트로피 높은 순 정렬 (다양한 토큰 사용한 샘플)
    df_sorted = df.sort_values('entropy', ascending=False)
    
    # 상위 선택
    sampled = df_sorted.head(target_size)
    
    print(f"평균 엔트로피:")
    print(f"  원본: {df['entropy'].mean():.3f}")
    print(f"  샘플링 후: {sampled['entropy'].mean():.3f}")
    
    return sampled.drop('entropy', axis=1)

# 사용
diverse_df = token_entropy_diverse_sampling(df, target_size=100000)

엔트로피 계산 중...
평균 엔트로피:
  원본: 2.835
  샘플링 후: 3.415

In [45]:
diverse_df

,req,res
8929,"글쿤, 열차를 교통수단으로써뿐 아니라 특별하게 이용할 수 있어서 조흐네. 우주센터가...",숙박 코스별로 다른데 먼저 마리안느 앤 마가렛 나눔연수원은 힐링 체험 위주로 진행된...
476096,시간은 딱 좋네! 근데 나 클래식공연은 처음인데 조는 거 아닌가 몰라 이번 공연 컨...,"응, 첫 곡은 타악기와 금관악기의 사운드가 돋보이는 코플랜드의 보통 사람을 위한 팡..."
242040,"아 정말? 나 파랑새 진짜 좋아했는데, 그럼 파랑새 얘기를 리메이크 한건가? 아니,...",20여 년이 지난 뒤의 틸틸은 나이는 들었지만 조금도 어른이 되지 못한 청년이야. ...
484555,"몰랐는데, 진정한 스위트 홈이네. 하긴 주변 보니 홈루덴스족이 심심찮게 보이던데, ...","이젠 IT, 식품, 가전, 콘텐츠 등 다양한 업계들이 소비 트렌드를 주목하고 풀충 ..."
7965,와~ 과거 존이 갬성 폭발할 것 같네. 거긴 어떤 행사를 하나? 대전역부터 한방특화...,과거존 끝에서 하얀 안개가 뿜어져 나오는 원형 터널을 지나면 'D-컬쳐 꿀잼대전 2...
...,...,...
480220,맞아! 그리고 선정된 작품은 최대 3년간 다년도 연속 지원도 받을 수 있대 짜짜 멋...,맞아! 그러면 우리도 언젠가 전통예술을 감상하러 가보는 건 어떰?
159713,"렬루? 그렇게 많이 구매하다니 머단해! 응! 등산은 건강에도 좋고, 자연을 느낄 수...",그래! 봄철에는 꽃구경도 하면서 등산을 즐길 수 있어.
358731,과천관이라면 가까워서 좋겠다! 응! 내년 2월 13일까지 열리니까 시간 내서 꼭 가...,맞아! 그리고 이번 전시는 최욱경 작가의 작품과 문학이 연계되어 있대
428443,2020년 젊은작가상 수상 작가 장희원의 첫번째 소설집이에요. 제목은 '우리의 환대...,마음에 온기가 삭막한 이 시대에는 그런 소설이 필요할 것 같아.
486452,"흥미로워 보이는데, 그 책에서 어떤 이야기가 더 특별하게 다뤄지고 있어? 그 중에서...",나는 소명출판에서 구했어. 인터넷 서점에서도 판매하고 있을 거야!

In [ ]:
analyze_top_frequent_korean(diverse_df, 'res', top_n=200)

In [ ]:
quick_token_analysis(diverse_df, 'res')

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MiniBatchKMeans

def cluster_diverse_sampling(df, text_col='res', n_clusters=500, target_size=50000):
    """클러스터링으로 다양성 확보"""
    
    # TF-IDF
    vectorizer = TfidfVectorizer(max_features=3000, ngram_range=(1, 2))
    tfidf = vectorizer.fit_transform(df[text_col].astype(str))
    
    # 클러스터링
    kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42)
    df['cluster'] = kmeans.fit_predict(tfidf)
    
    # 각 클러스터에서 균등하게 샘플링
    samples_per_cluster = target_size // n_clusters
    
    sampled_dfs = []
    for cluster_id in range(n_clusters):
        cluster_df = df[df['cluster'] == cluster_id]
        n = min(samples_per_cluster, len(cluster_df))
        sampled_dfs.append(cluster_df.sample(n=n))
    
    result = pd.concat(sampled_dfs).drop('cluster', axis=1)
    
    print(f"클러스터 수: {n_clusters}")
    print(f"클러스터당: {samples_per_cluster}개")
    print(f"최종: {len(result):,}개")
    
    return result.reset_index(drop=True)

# 사용
df_cluster = cluster_diverse_sampling(df, n_clusters=500, target_size=50000)

클러스터 수: 500
클러스터당: 100개
최종: 49,908개

In [49]:
analyze_top_frequent_korean(df_cluster, 'res', top_n=200)

================================================================================
상위 200개 빈도 토큰 분석 (공백+한국어 포함)
================================================================================

=== 토큰 종류 개수 ===
한글      : 148개 ( 74.0%)
영어      :   0개 (  0.0%)
숫자      :   4개 (  2.0%)
특수문자   :  47개 ( 23.5%)
기타      :   1개 (  0.5%)

=== 실제 사용 빈도 (상위 200개 토큰의 총 출현 횟수) ===
한글      :    448,553회 (70.41%)
영어      :          0회 ( 0.00%)
숫자      :     10,487회 ( 1.65%)
특수문자   :    168,304회 (26.42%)
기타      :      9,719회 ( 1.53%)

상위 200개 토큰이 전체의 64.00% 차지

================================================================================
상위 200개 중 한글 토큰 전체 목록 (148개)
================================================================================
  1. ID  12802: '이                   ' - 15,593회
  2. ID  47985: '도                   ' - 13,852회
  3. ID  17877: '을                   ' - 11,606회
  4. ID  89659: '야                   ' - 11,543회
  5. ID  52959: '아                   ' - 9,743회
  6. ID  31079: '어                   ' - 9,477회
  7. ID  35509: '␣가                  ' - 8,424회
  8. ID  19391: '에                   ' - 8,060회
  9. ID  19969: '가                   ' - 7,582회
 10. ID  33704: '은                   ' - 6,984회
 11. ID  21329: '지                   ' - 6,971회
 12. ID  28733: '␣수                  ' - 6,774회
 13. ID  16560: '는                   ' - 6,559회
 14. ID 126352: '␣거                  ' - 6,472회
 15. ID  48606: '그                   ' - 6,292회
 16. ID 144410: 'ㅋ                   ' - 6,064회
 17. ID  60315: '나                   ' - 5,846회
 18. ID  34395: '고                   ' - 5,806회
 19. ID  26698: '서                   ' - 5,728회
 20. ID  66845: '대                   ' - 5,682회
 21. ID  17380: '로                   ' - 5,382회
 22. ID 127353: '␣있어                 ' - 5,373회
 23. ID  20401: '의                   ' - 5,363회
 24. ID  25715: '자                   ' - 5,178회
 25. ID  56475: '에서                  ' - 5,043회
 26. ID  23573: '한                   ' - 4,988회
 27. ID  28002: '리                   ' - 4,578회
 28. ID  80573: '와                   ' - 4,263회
 29. ID  33883: '해                   ' - 4,156회
 30. ID  32290: '면                   ' - 4,027회
 31. ID 139772: '그래                  ' - 4,004회
 32. ID  18411: '를                   ' - 3,947회
 33. ID  32077: '일                   ' - 3,831회
 34. ID  29326: '시                   ' - 3,678회
 35. ID  31328: '인                   ' - 3,414회
 36. ID  24897: '스                   ' - 3,359회
 37. ID  13146: '다                   ' - 3,344회
 38. ID  20487: '기                   ' - 3,243회
 39. ID  60716: '␣해                  ' - 3,132회
 40. ID 127816: '겠다                  ' - 3,110회
 41. ID  54825: '␣그                  ' - 3,056회
 42. ID 124667: '까                   ' - 3,035회
 43. ID  54116: '␣기                  ' - 3,031회
 44. ID 144330: '맞                   ' - 3,020회
 45. ID  57801: '게                   ' - 2,991회
 46. ID 129273: '␣어떤                 ' - 2,896회
 47. ID  60294: '러                   ' - 2,882회
 48. ID  78374: '␣같                  ' - 2,776회
 49. ID 126730: '네                   ' - 2,765회
 50. ID  35339: '␣있                  ' - 2,708회
 51. ID  71108: '␣것                  ' - 2,654회
 52. ID 142815: '␣여행                 ' - 2,577회
 53. ID  73518: '␣나                  ' - 2,575회
 54. ID  47836: '할                   ' - 2,521회
 55. ID 124419: '데                   ' - 2,463회
 56. ID 125544: '마                   ' - 2,419회
 57. ID  28626: '트                   ' - 2,388회
 58. ID  53680: '과                   ' - 2,381회
 59. ID 126746: '루                   ' - 2,355회
 60. ID 131518: '응                   ' - 2,324회
 61. ID 137771: '짜                   ' - 2,278회
 62. ID  53442: '래                   ' - 2,233회
 63. ID  54321: '원                   ' - 2,218회
 64. ID 131050: '␣같이                 ' - 2,207회
 65. ID  41671: '보                   ' - 2,199회
 66. ID 124923: '겠                   ' - 2,181회
 67. ID  64521: '␣있는                 ' - 2,136회
 68. ID 126204: '하고                  ' - 2,129회
 69. ID 144135: '알                   ' - 2,129회
 70. ID 125466: '␣공                  ' - 2,125회
 71. ID 125568: '연                   ' - 2,117회
 72. ID  56290: '화                   ' - 2,116회
 73. ID  88259: '구                   ' - 2,093회
 74. ID 144681: 'ㅇ                   ' - 2,084회
 75. ID  54330: '주                   ' - 2,079회
 76. ID  42039: '으로                  ' - 2,045회
 77. ID  50340: '라                   ' - 2,024회
 78. ID  65865: '전                   ' - 2,023회
 79. ID  56419: '␣전                  ' - 2,021회
 80. ID  63332: '␣보                  ' - 2,015회
 81. ID  85251: '진                   ' - 1,985회
 82. ID  83036: '니                   ' - 1,985회
 83. ID 125953: '␣좋                  ' - 1,974회
 84. ID 144030: 'ㅎ                   ' - 1,963회
 85. ID  55673: '␣주                  ' - 1,951회
 86. ID  53900: '␣하                  ' - 1,932회
 87. ID 125894: '럼                   ' - 1,930회
 88. ID  76337: '식                   ' - 1,920회
 89. ID  16186: '하                   ' - 1,920회
 90. ID  85057: '산                   ' - 1,870회
 91. ID 137613: '봐                   ' - 1,868회
 92. ID  56039: '미                   ' - 1,818회
 93. ID  92192: '거                   ' - 1,780회
 94. ID 126377: '에는                  ' - 1,776회
 95. ID 128514: '월                   ' - 1,754회
 96. ID 141357: '␣그럼                 ' - 1,737회
 97. ID  40853: '장                   ' - 1,712회
 98. ID  37087: '제                   ' - 1,706회
 99. ID  40281: '우                   ' - 1,683회
100. ID  95617: '␣예                  ' - 1,661회
101. ID 126366: '␣더                  ' - 1,650회
102. ID  55054: '사                   ' - 1,640회
103. ID 126253: '들이                  ' - 1,638회
104. ID  72553: '만                   ' - 1,615회
105. ID  55902: '상                   ' - 1,607회
106. ID 125476: '려                   ' - 1,605회
107. ID 128878: '까지                  ' - 1,594회
108. ID  60960: '␣대                  ' - 1,591회
109. ID  95002: '␣할                  ' - 1,574회
110. ID 128719: '␣그리고                ' - 1,573회
111. ID  29346: '드                   ' - 1,538회
112. ID  93672: '운                   ' - 1,532회
113. ID  48408: '␣아                  ' - 1,529회
114. ID 130689: '␣있을                 ' - 1,518회
115. ID  58677: '␣인                  ' - 1,502회
116. ID  29281: '정                   ' - 1,488회
117. ID  57268: '오                   ' - 1,481회
118. ID  23084: '␣이                  ' - 1,469회
119. ID 126310: '␣유                  ' - 1,459회
120. ID 125199: '었                   ' - 1,445회
121. ID  42905: '하는                  ' - 1,436회
122. ID 126673: '레                   ' - 1,419회
123. ID 130109: '워                   ' - 1,408회
124. ID  44518: '␣시                  ' - 1,382회
125. ID 124780: '관                   ' - 1,378회
126. ID  61298: '␣한                  ' - 1,366회
127. ID  57089: '동                   ' - 1,365회
128. ID 135243: '␣그러면                ' - 1,338회
129. ID 143586: '␣작품                 ' - 1,335회
130. ID  48431: '음                   ' - 1,331회
131. ID 129034: '천                   ' - 1,328회
132. ID  92751: '␣관                  ' - 1,312회
133. ID  43590: '소                   ' - 1,294회
134. ID  78125: '공                   ' - 1,291회
135. ID  57026: '여                   ' - 1,281회
136. ID 126558: '부터                  ' - 1,254회
137. ID  23259: '수                   ' - 1,245회
138. ID 126251: '물                   ' - 1,244회
139. ID 129242: '␣재                  ' - 1,231회
140. ID 126551: '는데                  ' - 1,221회
141. ID  65306: '경                   ' - 1,217회
142. ID  79632: '명                   ' - 1,213회
143. ID  95218: '내                   ' - 1,190회
144. ID 130105: '길                   ' - 1,162회
145. ID  43115: '␣경                  ' - 1,162회
146. ID 129392: '␣도                  ' - 1,156회
147. ID 129471: '박                   ' - 1,147회
148. ID 124785: '국                   ' - 1,134회

================================================================================
상위 200개 중 영어 토큰 전체 목록 (0개)
================================================================================
(영어 토큰 없음)

================================================================================
상위 200개 중 특수문자 토큰 (47개)
================================================================================
  1. ID      0: '!'                  - 21,808회
  2. ID     30: '?'                  - 17,328회
  3. ID     13: '.'                  - 16,421회
  4. ID     11: ','                  - 9,100회
  5. ID   5140: ' �'                 - 8,948회
  6. ID  10764: ' �'                 - 5,394회
  7. ID    120: '�'                  - 5,341회
  8. ID    230: '�'                  - 4,372회
  9. ID    254: '�'                  - 4,293회
 10. ID    112: '�'                  - 3,636회
 11. ID    238: '�'                  - 3,329회
 12. ID    250: '�'                  - 3,031회
 13. ID   3315: ' �'                 - 2,964회
 14. ID    105: '�'                  - 2,765회
 15. ID  28927: ' �'                 - 2,589회
 16. ID   8620: ' �'                 - 2,545회
 17. ID    116: '�'                  - 2,404회
 18. ID  45130: ' �'                 - 2,397회
 19. ID    234: '�'                  - 2,348회
 20. ID    114: '�'                  - 2,187회
 21. ID    222: '�'                  - 2,165회
 22. ID  16751: ' �'                 - 2,132회
 23. ID    101: '�'                  - 2,122회
 24. ID    255: '�'                  - 2,064회
 25. ID    242: '�'                  - 2,048회
 26. ID    246: '�'                  - 1,970회
 27. ID    111: '�'                  - 1,942회
 28. ID    226: '�'                  - 1,885회
 29. ID    121: '�'                  - 1,874회
 30. ID  48364: ' �'                 - 1,873회
 31. ID    117: '�'                  - 1,858회
 32. ID    233: '�'                  - 1,747회
 33. ID 132376: ' �'                 - 1,735회
 34. ID  48108: ' �'                 - 1,708회
 35. ID    108: '�'                  - 1,702회
 36. ID  30520: ' �'                 - 1,634회
 37. ID    235: '�'                  - 1,520회
 38. ID  74884: ' �'                 - 1,483회
 39. ID  98734: '��'                 - 1,468회
 40. ID    251: '�'                  - 1,466회
 41. ID    228: '�'                  - 1,348회
 42. ID  16778: ' �'                 - 1,300회
 43. ID 137767: ' �'                 - 1,285회
 44. ID  32985: ' �'                 - 1,257회
 45. ID     97: '�'                  - 1,250회
 46. ID    239: '�'                  - 1,145회
 47. ID    243: '�'                  - 1,123회

{'korean_count': 148,
 'english_count': 0,
 'korean_freq': 448553,
 'english_freq': 0,
 'korean_tokens': [(12802, '이', 15593),
  (47985, '도', 13852),
  (17877, '을', 11606),
  (89659, '야', 11543),
  (52959, '아', 9743),
  (31079, '어', 9477),
  (35509, ' 가', 8424),
  (19391, '에', 8060),
  (19969, '가', 7582),
  (33704, '은', 6984),
  (21329, '지', 6971),
  (28733, ' 수', 6774),
  (16560, '는', 6559),
  (126352, ' 거', 6472),
  (48606, '그', 6292),
  (144410, 'ㅋ', 6064),
  (60315, '나', 5846),
  (34395, '고', 5806),
  (26698, '서', 5728),
  (66845, '대', 5682),
  (17380, '로', 5382),
  (127353, ' 있어', 5373),
  (20401, '의', 5363),
  (25715, '자', 5178),
  (56475, '에서', 5043),
  (23573, '한', 4988),
  (28002, '리', 4578),
  (80573, '와', 4263),
  (33883, '해', 4156),
  (32290, '면', 4027),
  (139772, '그래', 4004),
  (18411, '를', 3947),
  (32077, '일', 3831),
  (29326, '시', 3678),
  (31328, '인', 3414),
  (24897, '스', 3359),
  (13146, '다', 3344),
  (20487, '기', 3243),
  (60716, ' 해', 3132),
  (127816, '겠다', 3110),
  (54825, ' 그', 3056),
  (124667, '까', 3035),
  (54116, ' 기', 3031),
  (144330, '맞', 3020),
  (57801, '게', 2991),
  (129273, ' 어떤', 2896),
  (60294, '러', 2882),
  (78374, ' 같', 2776),
  (126730, '네', 2765),
  (35339, ' 있', 2708),
  (71108, ' 것', 2654),
  (142815, ' 여행', 2577),
  (73518, ' 나', 2575),
  (47836, '할', 2521),
  (124419, '데', 2463),
  (125544, '마', 2419),
  (28626, '트', 2388),
  (53680, '과', 2381),
  (126746, '루', 2355),
  (131518, '응', 2324),
  (137771, '짜', 2278),
  (53442, '래', 2233),
  (54321, '원', 2218),
  (131050, ' 같이', 2207),
  (41671, '보', 2199),
  (124923, '겠', 2181),
  (64521, ' 있는', 2136),
  (126204, '하고', 2129),
  (144135, '알', 2129),
  (125466, ' 공', 2125),
  (125568, '연', 2117),
  (56290, '화', 2116),
  (88259, '구', 2093),
  (144681, 'ㅇ', 2084),
  (54330, '주', 2079),
  (42039, '으로', 2045),
  (50340, '라', 2024),
  (65865, '전', 2023),
  (56419, ' 전', 2021),
  (63332, ' 보', 2015),
  (85251, '진', 1985),
  (83036, '니', 1985),
  (125953, ' 좋', 1974),
  (144030, 'ㅎ', 1963),
  (55673, ' 주', 1951),
  (53900, ' 하', 1932),
  (125894, '럼', 1930),
  (76337, '식', 1920),
  (16186, '하', 1920),
  (85057, '산', 1870),
  (137613, '봐', 1868),
  (56039, '미', 1818),
  (92192, '거', 1780),
  (126377, '에는', 1776),
  (128514, '월', 1754),
  (141357, ' 그럼', 1737),
  (40853, '장', 1712),
  (37087, '제', 1706),
  (40281, '우', 1683),
  (95617, ' 예', 1661),
  (126366, ' 더', 1650),
  (55054, '사', 1640),
  (126253, '들이', 1638),
  (72553, '만', 1615),
  (55902, '상', 1607),
  (125476, '려', 1605),
  (128878, '까지', 1594),
  (60960, ' 대', 1591),
  (95002, ' 할', 1574),
  (128719, ' 그리고', 1573),
  (29346, '드', 1538),
  (93672, '운', 1532),
  (48408, ' 아', 1529),
  (130689, ' 있을', 1518),
  (58677, ' 인', 1502),
  (29281, '정', 1488),
  (57268, '오', 1481),
  (23084, ' 이', 1469),
  (126310, ' 유', 1459),
  (125199, '었', 1445),
  (42905, '하는', 1436),
  (126673, '레', 1419),
  (130109, '워', 1408),
  (44518, ' 시', 1382),
  (124780, '관', 1378),
  (61298, ' 한', 1366),
  (57089, '동', 1365),
  (135243, ' 그러면', 1338),
  (143586, ' 작품', 1335),
  (48431, '음', 1331),
  (129034, '천', 1328),
  (92751, ' 관', 1312),
  (43590, '소', 1294),
  (78125, '공', 1291),
  (57026, '여', 1281),
  (126558, '부터', 1254),
  (23259, '수', 1245),
  (126251, '물', 1244),
  (129242, ' 재', 1231),
  (126551, '는데', 1221),
  (65306, '경', 1217),
  (79632, '명', 1213),
  (95218, '내', 1190),
  (130105, '길', 1162),
  (43115, ' 경', 1162),
  (129392, ' 도', 1156),
  (129471, '박', 1147),
  (124785, '국', 1134)],
 'english_tokens': [],
 'special_tokens': [(0, '!', 21808),
  (30, '?', 17328),
  (13, '.', 16421),
  (11, ',', 9100),
  (5140, ' �', 8948),
  (10764, ' �', 5394),
  (120, '�', 5341),
  (230, '�', 4372),
  (254, '�', 4293),
  (112, '�', 3636),
  (238, '�', 3329),
  (250, '�', 3031),
  (3315, ' �', 2964),
  (105, '�', 2765),
  (28927, ' �', 2589),
  (8620, ' �', 2545),
  (116, '�', 2404),
  (45130, ' �', 2397),
  (234, '�', 2348),
  (114, '�', 2187),
  (222, '�', 2165),
  (16751, ' �', 2132),
  (101, '�', 2122),
  (255, '�', 2064),
  (242, '�', 2048),
  (246, '�', 1970),
  (111, '�', 1942),
  (226, '�', 1885),
  (121, '�', 1874),
  (48364, ' �', 1873),
  (117, '�', 1858),
  (233, '�', 1747),
  (132376, ' �', 1735),
  (48108, ' �', 1708),
  (108, '�', 1702),
  (30520, ' �', 1634),
  (235, '�', 1520),
  (74884, ' �', 1483),
  (98734, '��', 1468),
  (251, '�', 1466),
  (228, '�', 1348),
  (16778, ' �', 1300),
  (137767, ' �', 1285),
  (32985, ' �', 1257),
  (97, '�', 1250),
  (239, '�', 1145),
  (243, '�', 1123)]}

In [50]:
quick_token_analysis(df_cluster, 'res')

=== res 컬럼 토큰 분석 ===
총 샘플 수: 49,908
총 토큰 수: 995,346
고유 토큰 수: 3,564
다양성 비율: 0.36%

상위 10개 토큰 집중도: 13.77%
상위 100개 토큰 집중도: 48.11%

가장 많이 사용된 토큰 20개:
  '!': 21,808회 (2.19%)
  '?': 17,328회 (1.74%)
  '.': 16,421회 (1.65%)
  '이': 15,593회 (1.57%)
  '도': 13,852회 (1.39%)
  '을': 11,606회 (1.17%)
  '야': 11,543회 (1.16%)
  '아': 9,743회 (0.98%)
  ' ': 9,719회 (0.98%)
  '어': 9,477회 (0.95%)
  ',': 9,100회 (0.91%)
  ' �': 8,948회 (0.90%)
  ' 가': 8,424회 (0.85%)
  '에': 8,060회 (0.81%)
  '가': 7,582회 (0.76%)
  '은': 6,984회 (0.70%)
  '지': 6,971회 (0.70%)
  ' 수': 6,774회 (0.68%)
  '는': 6,559회 (0.66%)
  ' 거': 6,472회 (0.65%)

Counter({0: 21808,
         30: 17328,
         13: 16421,
         12802: 15593,
         47985: 13852,
         17877: 11606,
         89659: 11543,
         52959: 9743,
         220: 9719,
         31079: 9477,
         11: 9100,
         5140: 8948,
         35509: 8424,
         19391: 8060,
         19969: 7582,
         33704: 6984,
         21329: 6971,
         28733: 6774,
         16560: 6559,
         126352: 6472,
         48606: 6292,
         144410: 6064,
         60315: 5846,
         34395: 5806,
         26698: 5728,
         66845: 5682,
         10764: 5394,
         17380: 5382,
         127353: 5373,
         20401: 5363,
         120: 5341,
         25715: 5178,
         56475: 5043,
         23573: 4988,
         28002: 4578,
         230: 4372,
         254: 4293,
         80573: 4263,
         33883: 4156,
         32290: 4027,
         139772: 4004,
         18411: 3947,
         32077: 3831,
         29326: 3678,
         112: 3636,
         15: 3431,
         31328: 3414,
         24897: 3359,
         13146: 3344,
         238: 3329,
         16: 3276,
         20487: 3243,
         60716: 3132,
         127816: 3110,
         54825: 3056,
         124667: 3035,
         250: 3031,
         54116: 3031,
         144330: 3020,
         57801: 2991,
         3315: 2964,
         129273: 2896,
         60294: 2882,
         78374: 2776,
         126730: 2765,
         105: 2765,
         35339: 2708,
         71108: 2654,
         28927: 2589,
         142815: 2577,
         73518: 2575,
         8620: 2545,
         47836: 2521,
         124419: 2463,
         125544: 2419,
         17: 2408,
         116: 2404,
         45130: 2397,
         28626: 2388,
         53680: 2381,
         126746: 2355,
         234: 2348,
         131518: 2324,
         137771: 2278,
         53442: 2233,
         54321: 2218,
         131050: 2207,
         41671: 2199,
         114: 2187,
         124923: 2181,
         222: 2165,
         64521: 2136,
         16751: 2132,
         126204: 2129,
         144135: 2129,
         125466: 2125,
         101: 2122,
         125568: 2117,
         56290: 2116,
         88259: 2093,
         144681: 2084,
         54330: 2079,
         255: 2064,
         242: 2048,
         42039: 2045,
         50340: 2024,
         65865: 2023,
         56419: 2021,
         63332: 2015,
         85251: 1985,
         83036: 1985,
         125953: 1974,
         246: 1970,
         144030: 1963,
         55673: 1951,
         111: 1942,
         53900: 1932,
         125894: 1930,
         76337: 1920,
         16186: 1920,
         226: 1885,
         121: 1874,
         48364: 1873,
         85057: 1870,
         137613: 1868,
         117: 1858,
         56039: 1818,
         92192: 1780,
         126377: 1776,
         128514: 1754,
         233: 1747,
         141357: 1737,
         132376: 1735,
         40853: 1712,
         48108: 1708,
         37087: 1706,
         108: 1702,
         40281: 1683,
         95617: 1661,
         126366: 1650,
         55054: 1640,
         126253: 1638,
         30520: 1634,
         72553: 1615,
         55902: 1607,
         125476: 1605,
         128878: 1594,
         60960: 1591,
         95002: 1574,
         128719: 1573,
         29346: 1538,
         93672: 1532,
         48408: 1529,
         235: 1520,
         130689: 1518,
         58677: 1502,
         29281: 1488,
         74884: 1483,
         57268: 1481,
         23084: 1469,
         98734: 1468,
         251: 1466,
         126310: 1459,
         125199: 1445,
         42905: 1436,
         126673: 1419,
         130109: 1408,
         44518: 1382,
         124780: 1378,
         18: 1372,
         61298: 1366,
         57089: 1365,
         228: 1348,
         135243: 1338,
         143586: 1335,
         48431: 1331,
         129034: 1328,
         92751: 1312,
         16778: 1300,
         43590: 1294,
         78125: 1291,
         137767: 1285,
         57026: 1281,
         32985: 1257,
         126558: 1254,
         97: 1250,
         23259: 1245,
         126251: 1244,
         129242: 1231,
         126551: 1221,
         65306: 1217,
         79632: 1213,
         95218: 1190,
         130105: 1162,
         43115: 1162,
         129392: 1156,
         129471: 1147,
         239: 1145,
         124785: 1134,
         243: 1123,
         135448: 1122,
         32831: 1119,
         130454: 1103,
         249: 1094,
         126861: 1093,
         132968: 1088,
         70582: 1088,
         20: 1086,
         130966: 1077,
         144796: 1075,
         136398: 1074,
         124934: 1073,
         36330: 1071,
         133738: 1066,
         130847: 1057,
         97143: 1050,
         127284: 1046,
         126844: 1044,
         125716: 1039,
         139740: 1037,
         130270: 1029,
         63089: 1026,
         142703: 1024,
         236: 1023,
         62071: 1015,
         125880: 1013,
         44680: 1011,
         61741: 1009,
         244: 1007,
         63154: 1006,
         24: 1003,
         23872: 1002,
         144065: 998,
         64805: 988,
         53435: 986,
         138779: 985,
         46832: 981,
         128753: 976,
         126735: 969,
         126559: 961,
         130217: 959,
         130626: 946,
         19: 946,
         135392: 942,
         35711: 939,
         77002: 935,
         126216: 932,
         139958: 929,
         49367: 926,
         125068: 921,
         124528: 919,
         126246: 905,
         38523: 895,
         57835: 894,
         77353: 889,
         125548: 887,
         125341: 886,
         125580: 886,
         134312: 878,
         74361: 863,
         124685: 860,
         125519: 860,
         81718: 858,
         93701: 848,
         126893: 843,
         70943: 831,
         109: 829,
         129865: 829,
         127452: 828,
         90711: 826,
         32129: 822,
         125054: 820,
         73077: 816,
         125866: 813,
         141571: 813,
         89940: 813,
         131893: 807,
         364: 803,
         59698: 801,
         83556: 801,
         84255: 801,
         126291: 800,
         125144: 800,
         6: 799,
         85403: 798,
         128646: 798,
         227: 797,
         129616: 797,
         130647: 791,
         131042: 791,
         138001: 788,
         37195: 784,
         126345: 783,
         58034: 781,
         223: 780,
         22042: 778,
         131131: 777,
         252: 776,
         89235: 776,
         126002: 776,
         98: 772,
         126429: 772,
         129889: 771,
         79207: 770,
         129676: 769,
         81133: 768,
         58777: 766,
         125052: 762,
         23: 756,
         126322: 755,
         83291: 754,
         139627: 754,
         130108: 753,
         93: 750,
         231: 738,
         240: 736,
         130262: 729,
         47911: 727,
         21: 727,
         34143: 726,
         128772: 716,
         127121: 716,
         129330: 713,
         95170: 707,
         68232: 702,
         22: 698,
         65510: 692,
         52300: 691,
         247: 689,
         62275: 688,
         132183: 686,
         66790: 685,
         125118: 683,
         127165: 678,
         83596: 677,
         143862: 675,
         129901: 671,
         126591: 670,
         129875: 668,
         73986: 667,
         95577: 666,
         94: 665,
         125522: 660,
         128808: 659,
         79716: 658,
         125535: 654,
         41429: 651,
         127820: 651,
         64850: 650,
         125615: 650,
         59761: 650,
         62618: 649,
         125678: 648,
         125714: 646,
         66136: 643,
         130612: 641,
         129900: 640,
         129423: 640,
         124781: 638,
         80901: 638,
         33861: 638,
         65291: 635,
         144671: 635,
         51588: 635,
         64577: 633,
         62107: 633,
         62099: 628,
         69192: 627,
         73669: 625,
         129254: 617,
         129835: 614,
         131961: 610,
         128533: 608,
         47324: 606,
         137116: 606,
         81173: 601,
         84621: 596,
         128618: 591,
         20136: 590,
         67511: 587,
         96137: 586,
         132920: 585,
         129359: 585,
         123: 580,
         64795: 578,
         144388: 577,
         126254: 576,
         125149: 575,
         126402: 574,
         126445: 573,
         125214: 572,
         92817: 572,
         128555: 570,
         36055: 569,
         129296: 568,
         94203: 566,
         128841: 566,
         135889: 564,
         124830: 563,
         129548: 563,
         144308: 563,
         129264: 560,
         125160: 559,
         45104: 557,
         129807: 555,
         76497: 553,
         57132: 553,
         126932: 552,
         24485: 546,
         136849: 545,
         127483: 542,
         131529: 540,
         126720: 540,
         132236: 540,
         57160: 538,
         130092: 537,
         131793: 534,
         26699: 533,
         127085: 532,
         125625: 531,
         130213: 530,
         129125: 524,
         73523: 523,
         129439: 521,
         125496: 521,
         79004: 517,
         128901: 514,
         81650: 514,
         131293: 512,
         129150: 512,
         131611: 510,
         130861: 510,
         125722: 509,
         54070: 508,
         126346: 507,
         131655: 505,
         130271: 503,
         123927: 503,
         126440: 502,
         142353: 501,
         129381: 500,
         129413: 498,
         126524: 498,
         134133: 498,
         126616: 495,
         126793: 495,
         80968: 494,
         124632: 494,
         128956: 493,
         127324: 492,
         133914: 491,
         16235: 491,
         129283: 490,
         46682: 490,
         126702: 489,
         98927: 482,
         83518: 481,
         102: 481,
         49543: 480,
         138098: 478,
         134663: 475,
         131196: 474,
         129547: 474,
         124517: 473,
         128677: 470,
         76435: 469,
         127027: 468,
         125674: 467,
         47665: 467,
         136905: 461,
         225: 460,
         125624: 460,
         77596: 459,
         47818: 458,
         144210: 457,
         85413: 455,
         95996: 451,
         141551: 450,
         129360: 448,
         133267: 448,
         139962: 448,
         53618: 445,
         36978: 445,
         241: 445,
         124889: 443,
         141836: 443,
         139764: 443,
         82528: 441,
         142209: 441,
         129704: 441,
         129695: 438,
         132876: 438,
         126835: 438,
         144131: 436,
         127906: 435,
         113: 434,
         130345: 430,
         126886: 429,
         40771: 428,
         125932: 424,
         125511: 422,
         126563: 421,
         104: 421,
         140968: 415,
         148068: 415,
         124873: 414,
         138630: 412,
         130229: 409,
         130898: 409,
         83277: 408,
         133016: 406,
         42044: 406,
         142451: 406,
         126896: 404,
         136499: 404,
         136608: 403,
         130902: 403,
         136125: 402,
         125166: 396,
         126321: 395,
         126712: 394,
         144337: 394,
         139188: 393,
         131891: 392,
         125512: 391,
         130939: 391,
         132330: 388,
         47455: 387,
         69441: 387,
         118: 386,
         92031: 386,
         137676: 379,
         131866: 377,
         129321: 376,
         63256: 375,
         135990: 373,
         144007: 370,
         55838: 370,
         126327: 370,
         128739: 368,
         136448: 368,
         85997: 367,
         128792: 366,
         127042: 365,
         140026: 364,
         64119: 364,
         127579: 362,
         126333: 361,
         144145: 361,
         28754: 359,
         129615: 359,
         127969: 357,
         93721: 357,
         229: 356,
         53189: 356,
         125086: 353,
         126970: 353,
         134521: 351,
         133553: 350,
         126614: 350,
         106: 348,
         129534: 345,
         95351: 345,
         128732: 344,
         127454: 344,
         129567: 344,
         141767: 344,
         132537: 340,
         130572: 336,
         1112: 336,
         115: 335,
         135807: 333,
         131417: 333,
         126299: 332,
         144104: 331,
         127048: 330,
         132029: 330,
         69923: 329,
         89860: 329,
         124459: 327,
         130127: 326,
         124973: 325,
         129378: 323,
         97834: 321,
         81676: 319,
         124546: 315,
         126615: 315,
         140888: 314,
         74808: 313,
         131303: 312,
         127559: 311,
         128909: 311,
         139822: 311,
         140577: 310,
         143146: 309,
         129400: 309,
         56983: 308,
         129624: 308,
         27767: 307,
         54969: 306,
         132185: 303,
         97929: 302,
         129293: 302,
         142852: 301,
         97172: 299,
         124982: 297,
         132184: 297,
         127475: 296,
         138667: 296,
         129882: 294,
         134108: 293,
         72509: 293,
         134563: 292,
         96: 291,
         130263: 291,
         132269: 290,
         71015: 290,
         131508: 289,
         129093: 289,
         65722: 289,
         126667: 288,
         127864: 288,
         45710: 288,
         126337: 285,
         53989: 284,
         144531: 284,
         131937: 284,
         128605: 283,
         142374: 283,
         126317: 283,
         98869: 283,
         130508: 282,
         131582: 281,
         89095: 281,
         128993: 281,
         125569: 281,
         136293: 280,
         137666: 279,
         129044: 278,
         134745: 278,
         94315: 278,
         130974: 277,
         138669: 277,
         144121: 276,
         144213: 276,
         129262: 276,
         92120: 275,
         134794: 274,
         132751: 274,
         51391: 274,
         125640: 273,
         125120: 273,
         129062: 273,
         132028: 271,
         126488: 271,
         139737: 271,
         77226: 270,
         132812: 270,
         65553: 270,
         125746: 269,
         63757: 269,
         133507: 269,
         49664: 267,
         66425: 266,
         130638: 265,
         74209: 264,
         86372: 262,
         91043: 262,
         131226: 260,
         82965: 260,
         142510: 260,
         138704: 259,
         125489: 259,
         125822: 259,
         126781: 256,
         136133: 256,
         129804: 255,
         134798: 255,
         130095: 255,
         129924: 254,
         125590: 254,
         141526: 253,
         45881: 252,
         130094: 250,
         131587: 249,
         79302: 249,
         232: 249,
         133196: 248,
         138038: 247,
         126414: 246,
         133120: 246,
         126537: 246,
         50696: 245,
         136633: 245,
         126641: 243,
         18585: 241,
         126423: 241,
         138449: 241,
         87425: 240,
         135379: 237,
         131219: 237,
         124657: 234,
         131411: 234,
         143788: 233,
         83315: 232,
         126588: 231,
         40720: 231,
         131978: 231,
         144137: 231,
         132466: 230,
         133692: 229,
         37064: 229,
         129027: 229,
         73859: 228,
         33509: 228,
         110: 228,
         128747: 228,
         245: 225,
         87608: 225,
         130472: 225,
         138081: 225,
         86038: 225,
         127840: 225,
         126407: 225,
         144179: 224,
         131777: 224,
         138268: 223,
         496: 223,
         142642: 222,
         43866: 222,
         132125: 220,
         125545: 220,
         129382: 220,
         137266: 219,
         131522: 219,
         130728: 218,
         126742: 218,
         144400: 217,
         129502: 217,
         135032: 216,
         130000: 215,
         144130: 214,
         237: 214,
         72344: 214,
         131498: 213,
         127166: 212,
         126923: 211,
         135854: 209,
         142309: 208,
         134013: 207,
         127819: 206,
         38150: 206,
         119: 205,
         138666: 205,
         134585: 205,
         132182: 205,
         90486: 205,
         86034: 204,
         134310: 203,
         130137: 203,
         138659: 203,
         131766: 202,
         130039: 201,
         135152: 199,
         125703: 198,
         130507: 197,
         134445: 197,
         134771: 197,
         138660: 197,
         135968: 196,
         138037: 195,
         135818: 195,
         132618: 195,
         130408: 195,
         129419: 195,
         136108: 194,
         136233: 194,
         60039: 193,
         144661: 193,
         130679: 192,
         128911: 192,
         144017: 191,
         143497: 190,
         84667: 190,
         142654: 190,
         128552: 189,
         131565: 189,
         131396: 189,
         137298: 188,
         133627: 187,
         126550: 186,
         125786: 186,
         132526: 185,
         130887: 185,
         126952: 185,
         130778: 184,
         132044: 183,
         135354: 183,
         139139: 183,
         138609: 182,
         126596: 182,
         4: 182,
         142509: 181,
         128844: 180,
         86831: 179,
         131277: 179,
         141185: 179,
         144208: 179,
         132772: 178,
         129007: 178,
         98005: 176,
         139604: 175,
         144143: 175,
         135562: 174,
         137119: 174,
         143861: 174,
         127621: 173,
         136239: 173,
         12: 172,
         144036: 171,
         143230: 171,
         134828: 171,
         98987: 171,
         135628: 170,
         140568: 170,
         134644: 170,
         138329: 169,
         143863: 169,
         144333: 169,
         145091: 169,
         127919: 169,
         138724: 168,
         142506: 167,
         142655: 167,
         133215: 166,
         129510: 165,
         126523: 164,
         135420: 164,
         143467: 164,
         134582: 164,
         90686: 164,
         130737: 164,
         125686: 163,
         144071: 163,
         130999: 163,
         144089: 162,
         66019: 162,
         141231: 161,
         133864: 161,
         137352: 160,
         142496: 160,
         134836: 159,
         126365: 158,
         137571: 158,
         139217: 158,
         130593: 157,
         134952: 157,
         136111: 156,
         126629: 156,
         98358: 155,
         135944: 155,
         140891: 155,
         128036: 154,
         132947: 154,
         136541: 153,
         137078: 153,
         23894: 153,
         132872: 153,
         41902: 153,
         138924: 152,
         132311: 152,
         129985: 152,
         130237: 152,
         126898: 151,
         141875: 150,
         128100: 150,
         128061: 149,
         130766: 149,
         130729: 148,
         129082: 148,
         129709: 148,
         129147: 148,
         132264: 147,
         77953: 147,
         38: 146,
         131170: 146,
         129885: 146,
         138903: 144,
         137601: 144,
         134929: 143,
         140585: 143,
         135402: 143,
         124905: 143,
         141274: 142,
         132488: 142,
         125991: 142,
         107: 141,
         131837: 141,
         130609: 140,
         144038: 140,
         144120: 140,
         479: 139,
         142067: 139,
         144032: 139,
         145165: 139,
         136275: 138,
         248: 137,
         144108: 136,
         125713: 136,
         145479: 136,
         139963: 134,
         57852: 134,
         144062: 134,
         27757: 134,
         85322: 132,
         34992: 132,
         135940: 132,
         143802: 131,
         132513: 131,
         130653: 131,
         125206: 131,
         136286: 130,
         130864: 130,

In [51]:
full_breakdown_with_english(df_cluster, 'res')

=== 사용된 토큰 전체 분류 ===
총 사용 토큰: 3,564개

한글        : 2,267개 (63.61%)
영어        :   947개 (26.57%)
숫자        :    10개 ( 0.28%)
특수문자      :   318개 ( 8.92%)
공백        :     3개 ( 0.08%)
기타        :    19개 ( 0.53%)

검증: 3564 = 3564

=== 한글 토큰 샘플 20개 ===
  ID 139269: '통신'
  ID 139274: ' 앞'
  ID 139287: '널'
  ID 131097: '새'
  ID 139293: ' 다만'
  ID 131110: '회사'
  ID 131120: '총'
  ID  98358: ' 종'
  ID 131131: '티'
  ID 139325: '었던'
  ID  32831: '성'
  ID 139328: '마다'
  ID 131137: '처럼'
  ID 139327: ' 만약'
  ID 147547: 'ㄳ'
  ID 131170: ' 다시'
  ID 131196: '브'
  ID 131193: '사항'
  ID 139393: ' 수행'
  ID  73859: ' 확인'

=== 영어 토큰 샘플 20개 ===
  ID     32: 'A'
  ID  98332: ' Choir'
  ID     35: 'D'
  ID     33: 'B'
  ID     37: 'F'
  ID     38: 'G'
  ID  65576: ' ASM'
  ID     41: 'J'
  ID     42: 'K'
  ID     43: 'L'
  ID     44: 'M'
  ID     45: 'N'
  ID     46: 'O'
  ID     39: 'H'
  ID     49: 'R'
  ID     48: 'Q'
  ID     51: 'T'
  ID     53: 'V'
  ID     55: 'X'
  ID     56: 'Y'

{'korean': 2267,
 'english': 947,
 'digit': 10,
 'special': 318,
 'space': 3,
 'etc': 19}

In [52]:
df_cluster

,req,res,entropy
0,"응, 가봤어! 한복을 입고 나온 바이올렛 씨가 인상적이었어. 한복을 입고 나왔다고?...",와 짜짜 머박이네! 나도 한국에 가보고 싶다.,2.995732
1,맞아! 그리고 합천막걸리도 핫해! 막걸리도 마시면서 맛있는 음식을 먹으면 완내스야!...,한과와 떡도 먹어보고 싶다!,2.708050
2,사람들이 밀면 빛도 내면서 울리는 이끼들이 있는 거래. 와... 신기하다! 날씨에 ...,나도 가보고 싶다! 언제 가야 될까?,2.540036
3,일정도 원하는 대로 선택할 수 있어 봄 여행에 딱이네 ㅎㅎ 일본은 오사카가 인기 1위래,나도 가보고 싶다 ㅠㅠ,2.163956
4,길이 짧고 거리도 가까워서 편할 것 같아 그래서 어떤 명소가 있는데? 오백년소나무가...,우와! 그 소나무 찾아보고 싶다,2.484907
...,...,...,...
49903,그래? 언제 시작해? 5월 15일 오후 5시부터 시작이래! 공연 내용은 무슨 이야기야?,조선 후기 풍속화 '대쾌도'를 모티브로 한 연희극이래!,3.258097
49904,"응, 가봤는데 왕실의례 전시실은 첨 들어봤어 그러면 이번에 보잠발기 전시도 GBJG...",조선 왕실 의례 때 사용한 비녀 목록을 적은 기록물이래,3.028029
49905,오우예 씨몬이네! 어떤 장식이 돋보였어? 창덕궁 인정문에서 보이는 조선 후기 기와 ...,맞아! 이건 조선 전기 왕실 관련 건축물 세부모습에 대한 실질적 고증이 가능한 유일...,3.564623
49906,그리고 경품도 푸짐하대! 경품 뽑으러 가야지 연휴에 진행되는 대표적인 행사들도 알아...,용인 한국민속촌에서 사또와 조선 캐릭터 잔치도 열려!,3.178054
49907,와 대규모 전시회라니 기대되네 웅웅 우리나라 난 시기와 이건희 컬렉션의 참모습을 한...,"선사시대 유물인 국보 '청동방울 일괄'부터 조선 후기의 도자기와 책장, 민화까지 포함돼",3.506503

In [53]:
# 혹시 안 해봤다면:
def quick_response_check(df, text_col='res'):
    total = len(df)
    unique = df[text_col].nunique()
    diversity = unique / total * 100
    
    print(f"총 샘플: {total:,}개")
    print(f"고유 응답: {unique:,}개")
    print(f"다양성: {diversity:.1f}%")
    print(f"평균 반복: {total/unique:.1f}회")

quick_response_check(df_cluster)

총 샘플: 49,908개
고유 응답: 48,339개
다양성: 96.9%
평균 반복: 1.0회

In [54]:
# 어떤 영어가 남았는지
def check_remaining_english(df, text_col='res'):
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    english_tokens = []
    for token_id, count in token_counts.items():
        decoded = tokenizer.decode([token_id])
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        
        if has_english and not has_korean:
            english_tokens.append((token_id, decoded, count))
    
    english_tokens.sort(key=lambda x: x[2], reverse=True)
    
    print(f"=== 영어 토큰 상위 30개 ===")
    for i, (tid, text, count) in enumerate(english_tokens[:30], 1):
        display = text.replace(' ', '␣')
        print(f"{i:2d}. '{display:15s}' - {count:,}회")
    
    # GBJG, K- 남았는지 확인
    gbjg_tokens = [x for x in english_tokens if 'GBJG' in x[1] or 'BJ' in x[1]]
    k_tokens = [x for x in english_tokens if x[1].startswith('K-') or x[1].startswith(' K-')]
    
    print(f"\nGBJG 관련: {len(gbjg_tokens)}개")
    print(f"K- 관련: {len(k_tokens)}개")

check_remaining_english(df_cluster)

=== 영어 토큰 상위 30개 ===
 1. 'G              ' - 146회
 2. '␣G             ' - 139회
 3. 'BJ             ' - 129회
 4. '␣K             ' - 94회
 5. 'km             ' - 61회
 6. 'Z              ' - 58회
 7. 'K              ' - 46회
 8. '␣M             ' - 45회
 9. 'm              ' - 39회
10. '␣S             ' - 36회
11. 'V              ' - 34회
12. '␣A             ' - 30회
13. '␣DM            ' - 26회
14. '␣CG            ' - 24회
15. 'D              ' - 22회
16. '␣N             ' - 22회
17. 'FT             ' - 19회
18. 'R              ' - 18회
19. 'TV             ' - 17회
20. '␣OST           ' - 16회
21. 'BS             ' - 15회
22. 'ICE            ' - 15회
23. '␣DJ            ' - 15회
24. 'NS             ' - 14회
25. '␣D             ' - 14회
26. '␣R             ' - 14회
27. 'F              ' - 13회
28. '␣LED           ' - 13회
29. 'X              ' - 13회
30. 'M              ' - 13회

GBJG 관련: 1개
K- 관련: 0개

In [55]:
# 한글 2,267개가 뭔지 확인
def analyze_korean_tokens_detail(df, text_col='res'):
    all_tokens = []
    for text in df[text_col].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)
    
    token_counts = Counter(all_tokens)
    
    korean_tokens = []
    for token_id, count in token_counts.items():
        decoded = tokenizer.decode([token_id])
        has_korean = bool(re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', decoded))
        has_english = bool(re.search(r'[a-zA-Z]', decoded))
        
        if has_korean and not has_english:
            korean_tokens.append((token_id, decoded, count))
    
    korean_tokens.sort(key=lambda x: x[2], reverse=True)
    
    print(f"=== 한글 토큰 상위 50개 ===")
    for i, (tid, text, count) in enumerate(korean_tokens[:50], 1):
        display = text.replace(' ', '␣')
        print(f"{i:2d}. '{display:15s}' - {count:,}회")

analyze_korean_tokens_detail(df_cluster)

=== 한글 토큰 상위 50개 ===
 1. '이              ' - 15,593회
 2. '도              ' - 13,852회
 3. '을              ' - 11,606회
 4. '야              ' - 11,543회
 5. '아              ' - 9,743회
 6. '어              ' - 9,477회
 7. '␣가             ' - 8,424회
 8. '에              ' - 8,060회
 9. '가              ' - 7,582회
10. '은              ' - 6,984회
11. '지              ' - 6,971회
12. '␣수             ' - 6,774회
13. '는              ' - 6,559회
14. '␣거             ' - 6,472회
15. '그              ' - 6,292회
16. 'ㅋ              ' - 6,064회
17. '나              ' - 5,846회
18. '고              ' - 5,806회
19. '서              ' - 5,728회
20. '대              ' - 5,682회
21. '로              ' - 5,382회
22. '␣있어            ' - 5,373회
23. '의              ' - 5,363회
24. '자              ' - 5,178회
25. '에서             ' - 5,043회
26. '한              ' - 4,988회
27. '리              ' - 4,578회
28. '와              ' - 4,263회
29. '해              ' - 4,156회
30. '면              ' - 4,027회
31. '그래             ' - 4,004회
32. '를              ' - 3,947회
33. '일              ' - 3,831회
34. '시              ' - 3,678회
35. '인              ' - 3,414회
36. '스              ' - 3,359회
37. '다              ' - 3,344회
38. '기              ' - 3,243회
39. '␣해             ' - 3,132회
40. '겠다             ' - 3,110회
41. '␣그             ' - 3,056회
42. '까              ' - 3,035회
43. '␣기             ' - 3,031회
44. '맞              ' - 3,020회
45. '게              ' - 2,991회
46. '␣어떤            ' - 2,896회
47. '러              ' - 2,882회
48. '␣같             ' - 2,776회
49. '네              ' - 2,765회
50. '␣있             ' - 2,708회

In [67]:
check_ngram_patterns(df_cluster, 'res', n=3, top_k=20)

=== 3-gram 패턴 (상위 20개) ===
총 3-gram: 895,530
고유 3-gram: 350,816
다양성: 39.17%

' 것 같아': 2,303회
'맞아!': 2,054회
' 거야?': 1,847회
' 레': 1,746회
' 꼭': 1,390회
'그러면': 1,291회
' 곳이': 1,237회
' 싶어': 1,099회
' ㅋㅋ': 1,093회
'��알': 1,012회
' 볼 수': 989회
' 가자!': 913회
' 멋진': 883회
'고 싶': 856회
' 있을까?': 847회
'보고 싶': 825회
'이야.': 806회
' 렬': 782회
'��루': 782회
' 음식': 741회

In [58]:
check_ngram_patterns(df_cluster, 'res', n=10,top_k=20)

=== 10-gram 패턴 (상위 20개) ===
총 10-gram: 550,423
고유 10-gram: 529,834
다양성: 96.26%

' 가서 즐거운 시간 보내자!': 110회
' 꼭 가서 돈쭐내야': 87회
'�� 가서 돈쭐내야지': 87회
' 같이 가서 즐거운 시간 보내자': 83회
' 멋진 경험이 될 것 같아': 77회
' 맛있는 음식도 먹고': 74회
' 특별한 경험이 될 것 같아': 66회
'! 같이 가서 즐거운 시간 보내': 63회
'�있는 음식도 먹고 �': 45회
'있는 음식도 먹고 싶': 45회
' 꼭 읽어봐야겠어': 40회
'은 레알루다가 멋진': 36회
' 레알루다가 멋진 �': 32회
'��알루다가 멋진 곳': 32회
'�진 경험이 될 것 같아!': 32회
'� 가서 돈쭐내야지!': 31회
'에서 맛있는 음식도 먹': 30회
' 꼭 보러 가야겠어!': 29회
' 음식도 먹고 싶어': 29회
'도 꼭 읽어봐야겠': 29회

In [59]:
# 더 짧은 n-gram 분석
for n in [2, 3, 5]:
    ngrams = []
    for text in df_cluster['res'].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        for i in range(len(tokens) - n + 1):
            ngrams.append(tuple(tokens[i:i+n]))
    
    ngram_counts = Counter(ngrams)
    
    print(f"\n=== {n}-gram ===")
    print(f"다양성: {len(ngram_counts)/len(ngrams)*100:.2f}%")
    print(f"\n상위 20개:")
    for pattern, count in ngram_counts.most_common(20):
        decoded = tokenizer.decode(list(pattern))
        print(f"  '{decoded}': {count:,}회")

=== 2-gram ===
다양성: 12.55%

상위 20개:
  ' 거야': 3,471회
  '야?': 3,273회
  '아!': 3,167회
  '맞아': 2,971회
  'ㅋㅋ': 2,752회
  ' 같아': 2,644회
  '이야': 2,613회
  ' �': 2,571회
  '까?': 2,544회
  ' 것 같': 2,363회
  ' 1': 2,187회
  '자!': 2,133회
  ' 싶': 2,052회
  ' 수 있어': 2,024회
  '그래!': 2,014회
  ' 곳': 1,912회
  '그럼': 1,885회
  '야.': 1,828회
  '��': 1,746회
  ' 즐': 1,628회

=== 3-gram ===
다양성: 39.17%

상위 20개:
  ' 것 같아': 2,303회
  '맞아!': 2,054회
  ' 거야?': 1,847회
  ' 레': 1,746회
  ' 꼭': 1,390회
  '그러면': 1,291회
  ' 곳이': 1,237회
  ' 싶어': 1,099회
  ' ㅋㅋ': 1,093회
  '��알': 1,012회
  ' 볼 수': 989회
  ' 가자!': 913회
  ' 멋진': 883회
  '고 싶': 856회
  ' 있을까?': 847회
  '보고 싶': 825회
  '이야.': 806회
  ' 렬': 782회
  '��루': 782회
  ' 음식': 741회

=== 5-gram ===
다양성: 74.71%

상위 20개:
  ' 레알루': 393회
  '��알루다가': 393회
  ' 렬루다가': 363회
  ' 좋을 것 같아': 362회
  ' 즐거운 시간': 359회
  ' 레게노': 342회
  ' 꼭 가봐': 337회
  '��게노다': 307회
  '�� 가봐야': 294회
  ' 맛있는 음': 283회
  '�있는 음식': 281회
  ' 흥미로': 279회
  '�거운 시간 보내': 277회
  ' 가보고 싶어': 269회
  ' 수 있을 것 같아': 245회
  ' 읽어봐야': 238회
  ',000원': 235회
  '루다가 멋진': 225회
  '서 즐거운': 221회
  '거운 시간 보내자': 221회

In [60]:
singleturn_df = pd.read_csv('/data/ephemeral/pro-nlp-finalproject-nlp-13/data/persona_data/AllData.csv')

In [61]:
singleturn_df

                        req                            res
0           너 좋아하는 차 종류 있어?              무슨 차? 자동차? 마시는 차?
1           ㅋㅋ 마시는 차 말한 거야!         아하 나 둥글레, 옥수수, 보리차 좋아해
2            완전 곡물류 좋아하네 ㅋㅋ             야쓰 끓이기 귀찮아서 냉침해 먹어
3             그럼 오래 걸리지 않아?           끓이는 것보다는 훨씬 오래 걸리지 ㅠ
4       근데 냉침 하는 것도 귀찮겠다 ㅜㅠ          응! 그래서 매일은 안 먹고 가끔 마셔
...                     ...                            ...
88969         아르바이트 면접 언제야?                 내일 아르바이트 면접이야!
88970        무슨 아르바이트 지원했어?                나 카페 아르바이트 지원했어
88971       카페는 경력자 원하지 않아?  맞아 나 전에 카페 경력 일년 정도 있어서 괜찮을걸?
88972     아 맞네 ㅋㅋ 너 카페 일했었네        응 근데 까먹었긴 한데 일 배우면 또 다해
88973  맞아 그렇긴하지 내일 면접 잘 보고와                    응 붙으면 말해줄게!

[88974 rows x 2 columns]

In [62]:
analyze_top_frequent_korean(singleturn_df,'res', top_n=200)

================================================================================
상위 200개 빈도 토큰 분석 (공백+한국어 포함)
================================================================================

=== 토큰 종류 개수 ===
한글      : 149개 ( 74.5%)
영어      :   0개 (  0.0%)
숫자      :   0개 (  0.0%)
특수문자   :  50개 ( 25.0%)
기타      :   1개 (  0.5%)

=== 실제 사용 빈도 (상위 200개 토큰의 총 출현 횟수) ===
한글      :    721,415회 (72.87%)
영어      :          0회 ( 0.00%)
숫자      :          0회 ( 0.00%)
특수문자   :    242,411회 (24.49%)
기타      :     26,208회 ( 2.65%)

상위 200개 토큰이 전체의 65.30% 차지

================================================================================
상위 200개 중 한글 토큰 전체 목록 (149개)
================================================================================
  1. ID 144410: 'ㅋ                   ' - 42,872회
  2. ID  52959: '아                   ' - 23,209회
  3. ID  12802: '이                   ' - 21,705회
  4. ID  47985: '도                   ' - 20,812회
  5. ID  31079: '어                   ' - 19,678회
  6. ID  16560: '는                   ' - 16,304회
  7. ID  60315: '나                   ' - 15,562회
  8. ID  21329: '지                   ' - 14,969회
  9. ID  19969: '가                   ' - 14,551회
 10. ID  34395: '고                   ' - 12,852회
 11. ID  89659: '야                   ' - 12,837회
 12. ID 144065: 'ㅠ                   ' - 10,883회
 13. ID  19391: '에                   ' - 10,797회
 14. ID  48606: '그                   ' - 9,971회
 15. ID  26698: '서                   ' - 9,165회
 16. ID 126352: '␣거                  ' - 8,706회
 17. ID  33704: '은                   ' - 8,518회
 18. ID 124419: '데                   ' - 8,434회
 19. ID  92192: '거                   ' - 8,288회
 20. ID  16186: '하                   ' - 8,062회
 21. ID  53900: '␣하                  ' - 7,981회
 22. ID  17877: '을                   ' - 7,314회
 23. ID  73518: '␣나                  ' - 7,242회
 24. ID  28002: '리                   ' - 7,094회
 25. ID  95170: '␣안                  ' - 7,092회
 26. ID  13146: '다                   ' - 7,041회
 27. ID  57801: '게                   ' - 6,939회
 28. ID  20487: '기                   ' - 6,818회
 29. ID  33883: '해                   ' - 6,725회
 30. ID  83036: '니                   ' - 6,712회
 31. ID  54825: '␣그                  ' - 6,705회
 32. ID  32290: '면                   ' - 6,452회
 33. ID  35509: '␣가                  ' - 6,431회
 34. ID  88259: '구                   ' - 6,069회
 35. ID 126730: '네                   ' - 6,014회
 36. ID 131518: '응                   ' - 5,606회
 37. ID  17380: '로                   ' - 5,441회
 38. ID  60716: '␣해                  ' - 5,400회
 39. ID  25715: '자                   ' - 5,041회
 40. ID 144330: '맞                   ' - 4,975회
 41. ID  78374: '␣같                  ' - 4,965회
 42. ID 137771: '짜                   ' - 4,917회
 43. ID  23573: '한                   ' - 4,732회
 44. ID 126551: '는데                  ' - 4,707회
 45. ID  72553: '만                   ' - 4,475회
 46. ID  49367: '␣다                  ' - 4,296회
 47. ID  57268: '오                   ' - 4,111회
 48. ID 126616: '␣진                  ' - 4,052회
 49. ID 144579: 'ㅜ                   ' - 4,011회
 50. ID  63332: '␣보                  ' - 3,949회
 51. ID 126720: '␣잘                  ' - 3,901회
 52. ID  50340: '라                   ' - 3,864회
 53. ID 125199: '었                   ' - 3,832회
 54. ID 125953: '␣좋                  ' - 3,777회
 55. ID  48408: '␣아                  ' - 3,721회
 56. ID  32077: '일                   ' - 3,712회
 57. ID 124923: '겠                   ' - 3,658회
 58. ID 125716: '니까                  ' - 3,583회
 59. ID 142703: '더라                  ' - 3,566회
 60. ID  66845: '대                   ' - 3,524회
 61. ID 125476: '려                   ' - 3,445회
 62. ID  64850: '들                   ' - 3,277회
 63. ID  60294: '러                   ' - 3,273회
 64. ID  46682: '␣없                  ' - 3,243회
 65. ID  24897: '스                   ' - 3,204회
 66. ID 127816: '겠다                  ' - 3,182회
 67. ID 125544: '마                   ' - 3,176회
 68. ID  35711: '요                   ' - 3,174회
 69. ID 130966: '␣많이                 ' - 3,127회
 70. ID  31328: '인                   ' - 3,104회
 71. ID  71108: '␣것                  ' - 3,083회
 72. ID  40281: '우                   ' - 3,079회
 73. ID  65865: '전                   ' - 3,056회
 74. ID 138779: '␣좋아                 ' - 3,028회
 75. ID  53442: '래                   ' - 2,961회
 76. ID  28733: '␣수                  ' - 2,957회
 77. ID 139772: '그래                  ' - 2,921회
 78. ID 124685: '␣어                  ' - 2,914회
 79. ID 133507: '긴                   ' - 2,856회
 80. ID 133267: '␣너무                 ' - 2,842회
 81. ID  54330: '주                   ' - 2,834회
 82. ID 133738: '랑                   ' - 2,819회
 83. ID 131417: '␣맞                  ' - 2,805회
 84. ID  56475: '에서                  ' - 2,758회
 85. ID  32129: '␣사                  ' - 2,706회
 86. ID 142309: '잖아                  ' - 2,664회
 87. ID  55054: '사                   ' - 2,629회
 88. ID 125722: '근                   ' - 2,604회
 89. ID  97143: '␣되                  ' - 2,603회
 90. ID  29326: '시                   ' - 2,558회
 91. ID  98927: '␣게                  ' - 2,552회
 92. ID  73077: '␣오                  ' - 2,529회
 93. ID 127353: '␣있어                 ' - 2,507회
 94. ID  41671: '보                   ' - 2,506회
 95. ID  61298: '␣한                  ' - 2,468회
 96. ID 126254: '␣말                  ' - 2,398회
 97. ID  48431: '음                   ' - 2,376회
 98. ID 126615: '␣그런                 ' - 2,357회
 99. ID  42905: '하는                  ' - 2,357회
100. ID  18411: '를                   ' - 2,356회
101. ID  89940: '으면                  ' - 2,351회
102. ID 130109: '워                   ' - 2,319회
103. ID  80573: '와                   ' - 2,313회
104. ID 126366: '␣더                  ' - 2,293회
105. ID  53618: '␣때                  ' - 2,286회
106. ID 137613: '봐                   ' - 2,277회
107. ID 127085: '너                   ' - 2,204회
108. ID 124667: '까                   ' - 2,199회
109. ID 130572: '␣좀                  ' - 2,194회
110. ID  85251: '진                   ' - 2,191회
111. ID 124873: '건                   ' - 2,188회
112. ID 125615: '던                   ' - 2,167회
113. ID  35339: '␣있                  ' - 2,146회
114. ID  54321: '원                   ' - 2,137회
115. ID 129293: '␣못                  ' - 2,121회
116. ID 144308: '웅                   ' - 2,117회
117. ID 128646: '␣생각                 ' - 2,099회
118. ID 126523: '␣아니                 ' - 2,095회
119. ID  29281: '정                   ' - 2,084회
120. ID  23084: '␣이                  ' - 2,072회
121. ID 126588: '난                   ' - 2,049회
122. ID  73986: '␣비                  ' - 2,039회
123. ID  59698: '치                   ' - 2,031회
124. ID 126735: '␣많                  ' - 2,017회
125. ID  47836: '할                   ' - 1,999회
126. ID  28626: '트                   ' - 1,985회
127. ID 129242: '␣재                  ' - 1,984회
128. ID  55673: '␣주                  ' - 1,980회
129. ID 129254: '라고                  ' - 1,972회
130. ID 125118: '청                   ' - 1,963회
131. ID  42039: '으로                  ' - 1,959회
132. ID  20401: '의                   ' - 1,942회
133. ID 130270: '␣건                  ' - 1,935회
134. ID  23259: '수                   ' - 1,932회
135. ID 125511: '히                   ' - 1,932회
136. ID 128956: '␣하는                 ' - 1,931회
137. ID 131866: '때                   ' - 1,928회
138. ID  64577: '␣자                  ' - 1,927회
139. ID 140891: '즘                   ' - 1,925회
140. ID  40853: '장                   ' - 1,886회
141. ID  37087: '제                   ' - 1,878회
142. ID 126002: '았                   ' - 1,867회
143. ID  60960: '␣대                  ' - 1,851회
144. ID  57026: '여                   ' - 1,823회
145. ID  93701: '임                   ' - 1,812회
146. ID  44518: '␣시                  ' - 1,790회
147. ID 127454: '␣너                  ' - 1,786회
148. ID  54116: '␣기                  ' - 1,766회
149. ID  29346: '드                   ' - 1,765회

================================================================================
상위 200개 중 영어 토큰 전체 목록 (0개)
================================================================================
(영어 토큰 없음)

================================================================================
상위 200개 중 특수문자 토큰 (50개)
================================================================================
  1. ID     30: '?'                  - 26,572회
  2. ID   5140: ' �'                 - 14,263회
  3. ID     13: '.'                  - 11,803회
  4. ID     14: '/'                  - 11,672회
  5. ID  10764: ' �'                 - 10,040회
  6. ID   1112: '...'                - 8,641회
  7. ID    250: '�'                  - 7,626회
  8. ID    230: '�'                  - 6,827회
  9. ID    112: '�'                  - 6,758회
 10. ID    120: '�'                  - 6,659회
 11. ID    226: '�'                  - 6,367회
 12. ID   3315: ' �'                 - 6,084회
 13. ID      0: '!'                  - 6,008회
 14. ID    117: '�'                  - 5,623회
 15. ID    222: '�'                  - 5,304회
 16. ID    116: '�'                  - 4,886회
 17. ID  28927: ' �'                 - 4,576회
 18. ID    242: '�'                  - 4,557회
 19. ID    238: '�'                  - 4,327회
 20. ID    254: '�'                  - 3,962회
 21. ID 137767: ' �'                 - 3,917회
 22. ID    105: '�'                  - 3,752회
 23. ID    101: '�'                  - 3,721회
 24. ID  74884: ' �'                 - 3,569회
 25. ID    246: '�'                  - 3,481회
 26. ID    108: '�'                  - 3,439회
 27. ID     97: '�'                  - 3,341회
 28. ID  37195: ' �'                 - 3,339회
 29. ID    244: '�'                  - 3,310회
 30. ID   8620: ' �'                 - 2,946회
 31. ID    234: '�'                  - 2,812회
 32. ID  32985: ' �'                 - 2,697회
 33. ID 134312: ' �'                 - 2,642회
 34. ID  16778: ' �'                 - 2,569회
 35. ID  24485: ' �'                 - 2,516회
 36. ID    239: '�'                  - 2,503회
 37. ID    114: '�'                  - 2,488회
 38. ID  90711: ' �'                 - 2,417회
 39. ID     93: '~'                  - 2,378회
 40. ID     11: ','                  - 2,376회
 41. ID    109: '�'                  - 2,285회
 42. ID  98734: '��'                 - 2,263회
 43. ID  23872: ' �'                 - 2,102회
 44. ID    121: '�'                  - 1,952회
 45. ID  38523: ' �'                 - 1,919회
 46. ID  30520: ' �'                 - 1,868회
 47. ID    255: '�'                  - 1,838회
 48. ID    252: '�'                  - 1,825회
 49. ID    251: '�'                  - 1,797회
 50. ID    231: '�'                  - 1,794회

{'korean_count': 149,
 'english_count': 0,
 'korean_freq': 721415,
 'english_freq': 0,
 'korean_tokens': [(144410, 'ㅋ', 42872),
  (52959, '아', 23209),
  (12802, '이', 21705),
  (47985, '도', 20812),
  (31079, '어', 19678),
  (16560, '는', 16304),
  (60315, '나', 15562),
  (21329, '지', 14969),
  (19969, '가', 14551),
  (34395, '고', 12852),
  (89659, '야', 12837),
  (144065, 'ㅠ', 10883),
  (19391, '에', 10797),
  (48606, '그', 9971),
  (26698, '서', 9165),
  (126352, ' 거', 8706),
  (33704, '은', 8518),
  (124419, '데', 8434),
  (92192, '거', 8288),
  (16186, '하', 8062),
  (53900, ' 하', 7981),
  (17877, '을', 7314),
  (73518, ' 나', 7242),
  (28002, '리', 7094),
  (95170, ' 안', 7092),
  (13146, '다', 7041),
  (57801, '게', 6939),
  (20487, '기', 6818),
  (33883, '해', 6725),
  (83036, '니', 6712),
  (54825, ' 그', 6705),
  (32290, '면', 6452),
  (35509, ' 가', 6431),
  (88259, '구', 6069),
  (126730, '네', 6014),
  (131518, '응', 5606),
  (17380, '로', 5441),
  (60716, ' 해', 5400),
  (25715, '자', 5041),
  (144330, '맞', 4975),
  (78374, ' 같', 4965),
  (137771, '짜', 4917),
  (23573, '한', 4732),
  (126551, '는데', 4707),
  (72553, '만', 4475),
  (49367, ' 다', 4296),
  (57268, '오', 4111),
  (126616, ' 진', 4052),
  (144579, 'ㅜ', 4011),
  (63332, ' 보', 3949),
  (126720, ' 잘', 3901),
  (50340, '라', 3864),
  (125199, '었', 3832),
  (125953, ' 좋', 3777),
  (48408, ' 아', 3721),
  (32077, '일', 3712),
  (124923, '겠', 3658),
  (125716, '니까', 3583),
  (142703, '더라', 3566),
  (66845, '대', 3524),
  (125476, '려', 3445),
  (64850, '들', 3277),
  (60294, '러', 3273),
  (46682, ' 없', 3243),
  (24897, '스', 3204),
  (127816, '겠다', 3182),
  (125544, '마', 3176),
  (35711, '요', 3174),
  (130966, ' 많이', 3127),
  (31328, '인', 3104),
  (71108, ' 것', 3083),
  (40281, '우', 3079),
  (65865, '전', 3056),
  (138779, ' 좋아', 3028),
  (53442, '래', 2961),
  (28733, ' 수', 2957),
  (139772, '그래', 2921),
  (124685, ' 어', 2914),
  (133507, '긴', 2856),
  (133267, ' 너무', 2842),
  (54330, '주', 2834),
  (133738, '랑', 2819),
  (131417, ' 맞', 2805),
  (56475, '에서', 2758),
  (32129, ' 사', 2706),
  (142309, '잖아', 2664),
  (55054, '사', 2629),
  (125722, '근', 2604),
  (97143, ' 되', 2603),
  (29326, '시', 2558),
  (98927, ' 게', 2552),
  (73077, ' 오', 2529),
  (127353, ' 있어', 2507),
  (41671, '보', 2506),
  (61298, ' 한', 2468),
  (126254, ' 말', 2398),
  (48431, '음', 2376),
  (126615, ' 그런', 2357),
  (42905, '하는', 2357),
  (18411, '를', 2356),
  (89940, '으면', 2351),
  (130109, '워', 2319),
  (80573, '와', 2313),
  (126366, ' 더', 2293),
  (53618, ' 때', 2286),
  (137613, '봐', 2277),
  (127085, '너', 2204),
  (124667, '까', 2199),
  (130572, ' 좀', 2194),
  (85251, '진', 2191),
  (124873, '건', 2188),
  (125615, '던', 2167),
  (35339, ' 있', 2146),
  (54321, '원', 2137),
  (129293, ' 못', 2121),
  (144308, '웅', 2117),
  (128646, ' 생각', 2099),
  (126523, ' 아니', 2095),
  (29281, '정', 2084),
  (23084, ' 이', 2072),
  (126588, '난', 2049),
  (73986, ' 비', 2039),
  (59698, '치', 2031),
  (126735, ' 많', 2017),
  (47836, '할', 1999),
  (28626, '트', 1985),
  (129242, ' 재', 1984),
  (55673, ' 주', 1980),
  (129254, '라고', 1972),
  (125118, '청', 1963),
  (42039, '으로', 1959),
  (20401, '의', 1942),
  (130270, ' 건', 1935),
  (23259, '수', 1932),
  (125511, '히', 1932),
  (128956, ' 하는', 1931),
  (131866, '때', 1928),
  (64577, ' 자', 1927),
  (140891, '즘', 1925),
  (40853, '장', 1886),
  (37087, '제', 1878),
  (126002, '았', 1867),
  (60960, ' 대', 1851),
  (57026, '여', 1823),
  (93701, '임', 1812),
  (44518, ' 시', 1790),
  (127454, ' 너', 1786),
  (54116, ' 기', 1766),
  (29346, '드', 1765)],
 'english_tokens': [],
 'special_tokens': [(30, '?', 26572),
  (5140, ' �', 14263),
  (13, '.', 11803),
  (14, '/', 11672),
  (10764, ' �', 10040),
  (1112, '...', 8641),
  (250, '�', 7626),
  (230, '�', 6827),
  (112, '�', 6758),
  (120, '�', 6659),
  (226, '�', 6367),
  (3315, ' �', 6084),
  (0, '!', 6008),
  (117, '�', 5623),
  (222, '�', 5304),
  (116, '�', 4886),
  (28927, ' �', 4576),
  (242, '�', 4557),
  (238, '�', 4327),
  (254, '�', 3962),
  (137767, ' �', 3917),
  (105, '�', 3752),
  (101, '�', 3721),
  (74884, ' �', 3569),
  (246, '�', 3481),
  (108, '�', 3439),
  (97, '�', 3341),
  (37195, ' �', 3339),
  (244, '�', 3310),
  (8620, ' �', 2946),
  (234, '�', 2812),
  (32985, ' �', 2697),
  (134312, ' �', 2642),
  (16778, ' �', 2569),
  (24485, ' �', 2516),
  (239, '�', 2503),
  (114, '�', 2488),
  (90711, ' �', 2417),
  (93, '~', 2378),
  (11, ',', 2376),
  (109, '�', 2285),
  (98734, '��', 2263),
  (23872, ' �', 2102),
  (121, '�', 1952),
  (38523, ' �', 1919),
  (30520, ' �', 1868),
  (255, '�', 1838),
  (252, '�', 1825),
  (251, '�', 1797),
  (231, '�', 1794)]}

In [63]:
quick_token_analysis(singleturn_df,'res')

=== res 컬럼 토큰 분석 ===
총 샘플 수: 88,969
총 토큰 수: 1,516,124
고유 토큰 수: 3,353
다양성 비율: 0.22%

상위 10개 토큰 집중도: 15.03%
상위 100개 토큰 집중도: 50.22%

가장 많이 사용된 토큰 20개:
  'ㅋ': 42,872회 (2.83%)
  '?': 26,572회 (1.75%)
  ' ': 26,208회 (1.73%)
  '아': 23,209회 (1.53%)
  '이': 21,705회 (1.43%)
  '도': 20,812회 (1.37%)
  '어': 19,678회 (1.30%)
  '는': 16,304회 (1.08%)
  '나': 15,562회 (1.03%)
  '지': 14,969회 (0.99%)
  '가': 14,551회 (0.96%)
  ' �': 14,263회 (0.94%)
  '고': 12,852회 (0.85%)
  '야': 12,837회 (0.85%)
  '.': 11,803회 (0.78%)
  '/': 11,672회 (0.77%)
  'ㅠ': 10,883회 (0.72%)
  '에': 10,797회 (0.71%)
  ' �': 10,040회 (0.66%)
  '그': 9,971회 (0.66%)

Counter({144410: 42872,
         30: 26572,
         220: 26208,
         52959: 23209,
         12802: 21705,
         47985: 20812,
         31079: 19678,
         16560: 16304,
         60315: 15562,
         21329: 14969,
         19969: 14551,
         5140: 14263,
         34395: 12852,
         89659: 12837,
         13: 11803,
         14: 11672,
         144065: 10883,
         19391: 10797,
         10764: 10040,
         48606: 9971,
         26698: 9165,
         126352: 8706,
         1112: 8641,
         33704: 8518,
         124419: 8434,
         92192: 8288,
         16186: 8062,
         53900: 7981,
         250: 7626,
         17877: 7314,
         73518: 7242,
         28002: 7094,
         95170: 7092,
         13146: 7041,
         57801: 6939,
         230: 6827,
         20487: 6818,
         112: 6758,
         33883: 6725,
         83036: 6712,
         54825: 6705,
         120: 6659,
         32290: 6452,
         35509: 6431,
         226: 6367,
         3315: 6084,
         88259: 6069,
         126730: 6014,
         0: 6008,
         117: 5623,
         131518: 5606,
         17380: 5441,
         60716: 5400,
         222: 5304,
         25715: 5041,
         144330: 4975,
         78374: 4965,
         137771: 4917,
         116: 4886,
         23573: 4732,
         126551: 4707,
         28927: 4576,
         242: 4557,
         72553: 4475,
         238: 4327,
         49367: 4296,
         57268: 4111,
         126616: 4052,
         144579: 4011,
         254: 3962,
         63332: 3949,
         137767: 3917,
         126720: 3901,
         50340: 3864,
         125199: 3832,
         125953: 3777,
         105: 3752,
         101: 3721,
         48408: 3721,
         32077: 3712,
         124923: 3658,
         125716: 3583,
         74884: 3569,
         142703: 3566,
         66845: 3524,
         246: 3481,
         125476: 3445,
         108: 3439,
         97: 3341,
         37195: 3339,
         244: 3310,
         64850: 3277,
         60294: 3273,
         46682: 3243,
         24897: 3204,
         127816: 3182,
         125544: 3176,
         35711: 3174,
         130966: 3127,
         31328: 3104,
         71108: 3083,
         40281: 3079,
         65865: 3056,
         138779: 3028,
         53442: 2961,
         28733: 2957,
         8620: 2946,
         139772: 2921,
         124685: 2914,
         133507: 2856,
         133267: 2842,
         54330: 2834,
         133738: 2819,
         234: 2812,
         131417: 2805,
         56475: 2758,
         32129: 2706,
         32985: 2697,
         142309: 2664,
         134312: 2642,
         55054: 2629,
         125722: 2604,
         97143: 2603,
         16778: 2569,
         29326: 2558,
         98927: 2552,
         73077: 2529,
         24485: 2516,
         127353: 2507,
         41671: 2506,
         239: 2503,
         114: 2488,
         61298: 2468,
         90711: 2417,
         126254: 2398,
         93: 2378,
         11: 2376,
         48431: 2376,
         126615: 2357,
         42905: 2357,
         18411: 2356,
         89940: 2351,
         130109: 2319,
         80573: 2313,
         126366: 2293,
         53618: 2286,
         109: 2285,
         137613: 2277,
         98734: 2263,
         127085: 2204,
         124667: 2199,
         130572: 2194,
         85251: 2191,
         124873: 2188,
         125615: 2167,
         35339: 2146,
         54321: 2137,
         129293: 2121,
         144308: 2117,
         23872: 2102,
         128646: 2099,
         126523: 2095,
         29281: 2084,
         23084: 2072,
         126588: 2049,
         73986: 2039,
         59698: 2031,
         126735: 2017,
         47836: 1999,
         28626: 1985,
         129242: 1984,
         55673: 1980,
         129254: 1972,
         125118: 1963,
         42039: 1959,
         121: 1952,
         20401: 1942,
         130270: 1935,
         23259: 1932,
         125511: 1932,
         128956: 1931,
         131866: 1928,
         64577: 1927,
         140891: 1925,
         38523: 1919,
         40853: 1886,
         37087: 1878,
         30520: 1868,
         126002: 1867,
         60960: 1851,
         255: 1838,
         252: 1825,
         57026: 1823,
         93701: 1812,
         251: 1797,
         231: 1794,
         44518: 1790,
         127454: 1786,
         54116: 1766,
         29346: 1765,
         34143: 1760,
         129547: 1754,
         95002: 1754,
         125932: 1749,
         85997: 1748,
         127284: 1747,
         125054: 1744,
         64805: 1742,
         95218: 1733,
         74361: 1728,
         249: 1722,
         44680: 1714,
         125580: 1698,
         76435: 1666,
         16: 1650,
         126429: 1633,
         126204: 1627,
         247: 1618,
         235: 1616,
         132311: 1614,
         130263: 1609,
         228: 1592,
         15: 1591,
         63089: 1582,
         36978: 1577,
         55838: 1576,
         66136: 1573,
         85403: 1569,
         66790: 1558,
         83556: 1539,
         56419: 1530,
         57089: 1517,
         96137: 1512,
         236: 1504,
         241: 1481,
         22042: 1481,
         50696: 1473,
         76337: 1422,
         45130: 1421,
         223: 1417,
         125894: 1394,
         81718: 1389,
         33509: 1385,
         70582: 1384,
         125052: 1366,
         95577: 1355,
         87425: 1352,
         73669: 1347,
         125512: 1346,
         56039: 1342,
         132968: 1326,
         125625: 1324,
         94: 1320,
         125149: 1313,
         144671: 1310,
         125214: 1309,
         56290: 1306,
         62071: 1299,
         82528: 1293,
         144130: 1287,
         55902: 1283,
         129381: 1279,
         126893: 1259,
         141551: 1257,
         128753: 1247,
         126402: 1245,
         131042: 1244,
         124934: 1238,
         136108: 1225,
         127673: 1212,
         93672: 1212,
         131961: 1209,
         125068: 1200,
         64521: 1191,
         126246: 1180,
         17: 1180,
         58677: 1176,
         134247: 1167,
         139456: 1166,
         127166: 1166,
         130127: 1162,
         65553: 1161,
         129378: 1147,
         125548: 1145,
         243: 1138,
         104: 1136,
         131380: 1127,
         16235: 1126,
         79207: 1118,
         144840: 1110,
         42044: 1104,
         85413: 1104,
         138903: 1101,
         129901: 1101,
         141357: 1100,
         127452: 1095,
         126251: 1089,
         129082: 1083,
         131050: 1082,
         125866: 1079,
         43590: 1074,
         124830: 1074,
         132269: 1069,
         98: 1066,
         130271: 1066,
         129624: 1053,
         229: 1051,
         16751: 1047,
         128555: 1040,
         125120: 1039,
         129330: 1037,
         126322: 1037,
         53989: 1035,
         47818: 1027,
         40771: 1024,
         130229: 1020,
         95617: 1020,
         57835: 1018,
         133339: 1017,
         129885: 1013,
         125466: 1012,
         96: 1009,
         124889: 1008,
         36330: 1001,
         79716: 996,
         64795: 995,
         129413: 995,
         125640: 993,
         126559: 989,
         144131: 984,
         92120: 984,
         46832: 984,
         129548: 983,
         125568: 983,
         77353: 982,
         62275: 980,
         225: 975,
         20136: 973,
         131277: 971,
         227: 970,
         135944: 968,
         126253: 966,
         132330: 963,
         48108: 963,
         128878: 960,
         134246: 958,
         111: 958,
         62618: 951,
         126310: 950,
         129882: 944,
         62107: 944,
         126216: 938,
         83596: 936,
         89235: 929,
         126377: 925,
         70943: 925,
         126886: 925,
         129900: 921,
         233: 921,
         126781: 917,
         135968: 916,
         129439: 911,
         18585: 901,
         48364: 897,
         129471: 888,
         85057: 879,
         137289: 877,
         134663: 877,
         130626: 876,
         41429: 870,
         136105: 868,
         132028: 867,
         124982: 861,
         126291: 860,
         125569: 858,
         47911: 858,
         57160: 856,
         47665: 853,
         83518: 848,
         102: 847,
         38150: 841,
         87980: 840,
         130262: 838,
         123: 826,
         124708: 823,
         65510: 821,
         84621: 818,
         76497: 813,
         132557: 813,
         129392: 810,
         1725: 808,
         33861: 807,
         137298: 806,
         132654: 806,
         126898: 805,
         126321: 803,
         26699: 801,
         127165: 791,
         137116: 789,
         45104: 786,
         125545: 780,
         134582: 779,
         63154: 778,
         126673: 777,
         136233: 775,
         126445: 767,
         113: 759,
         245: 756,
         126345: 756,
         129359: 756,
         62099: 754,
         126558: 753,
         131303: 753,
         107: 748,
         133553: 747,
         77596: 746,
         79004: 746,
         130217: 745,
         54070: 745,
         142510: 745,
         125714: 739,
         131344: 738,
         83277: 735,
         36055: 735,
         79632: 735,
         142374: 734,
         58777: 733,
         58034: 731,
         1940: 729,
         139740: 728,
         129709: 727,
         125489: 727,
         125086: 727,
         131219: 727,
         139957: 726,
         65291: 726,
         130974: 725,
         124683: 717,
         115: 714,
         129264: 712,
         125834: 708,
         144388: 705,
         240: 704,
         124785: 702,
         132125: 702,
         125590: 700,
         144186: 698,
         132911: 698,
         53680: 697,
         18: 696,
         130898: 696,
         59761: 695,
         129296: 695,
         126614: 690,
         23894: 689,
         137676: 689,
         137638: 687,
         125703: 686,
         130507: 685,
         132236: 683,
         65306: 681,
         125144: 680,
         126333: 677,
         82619: 677,
         82965: 674,
         47324: 674,
         131097: 671,
         129704: 671,
         125971: 669,
         125822: 666,
         128732: 659,
         125519: 657,
         129034: 657,
         135854: 656,
         124528: 652,
         126488: 650,
         124517: 647,
         126923: 644,
         125261: 643,
         73523: 638,
         125496: 635,
         129062: 635,
         78125: 635,
         130105: 634,
         129238: 634,
         86831: 633,
         129093: 628,
         128772: 626,
         128901: 626,
         124459: 623,
         126746: 621,
         127027: 619,
         118: 618,
         125522: 616,
         97172: 615,
         126932: 613,
         81676: 609,
         129807: 607,
         132920: 603,
         129273: 603,
         28754: 601,
         144036: 598,
         135448: 597,
         129027: 597,
         32831: 595,
         129262: 595,
         131611: 595,
         129865: 592,
         129423: 592,
         98005: 589,
         136593: 588,
         141767: 587,
         129616: 587,
         130108: 586,
         127621: 586,
         138658: 586,
         81133: 585,
         134798: 584,
         132556: 583,
         135562: 582,
         140611: 580,
         130847: 577,
         129007: 576,
         134657: 575,
         132183: 571,
         132751: 570,
         140914: 569,
         63757: 564,
         80901: 561,
         133016: 559,
         130000: 557,
         128058: 557,
         20: 556,
         139217: 556,
         126793: 555,
         142815: 554,
         125686: 552,
         130689: 552,
         130454: 551,
         137571: 550,
         126440: 549,
         124780: 545,
         135379: 541,
         127042: 540,
         133857: 533,
         81173: 531,
         129567: 530,
         131355: 527,
         129419: 526,
         125166: 525,
         134422: 523,
         134828: 522,
         130612: 521,
         92817: 520,
         51275: 520,
         128618: 518,
         125160: 517,
         128036: 516,
         72344: 516,
         47455: 514,
         128677: 513,
         130609: 513,
         144161: 504,
         131793: 502,
         129835: 501,
         69441: 499,
         136999: 499,
         131293: 497,
         51588: 494,
         144110: 493,
         136398: 492,
         141231: 492,
         136125: 490,
         126835: 488,
         134133: 487,
         125535: 484,
         131587: 483,
         89095: 481,
         143835: 481,
         64119: 478,
         129044: 477,
         79302: 476,
         74808: 473,
         126550: 472,
         131196: 472,
         132772: 470,
         77226: 469,
         124781: 468,
         129695: 467,
         143861: 467,
         138665: 465,
         132513: 465,
         144035: 464,
         136982: 463,
         131170: 463,
         133166: 460,
         131498: 459,
         41902: 458,
         132182: 457,
         128514: 455,
         124632: 453,
         138038: 452,
         54969: 449,
         80968: 444,
         57132: 443,
         131131: 443,
         135660: 443,
         131508: 442,
         129147: 442,
         129534: 442,
         135607: 440,
         126365: 439,
         139958: 435,
         127478: 435,
         142063: 434,
         126896: 434,
         65722: 432,
         128844: 429,
         37064: 429,
         144411: 428,
         130768: 427,
         92751: 426,
         129875: 426,
         127173: 424,
         45710: 423,
         136633: 423,
         133692: 423,
         128792: 423,
         139188: 422,
         144135: 421,
         136387: 421,
         143863: 420,
         136065: 419,
         119: 419,
         135889: 419,
         69192: 417,
         134808: 417,
         128911: 416,
         134745: 416,
         43115: 415,
         134006: 415,
         134563: 415,
         124546: 413,
         126346: 413,
         66425: 412,
         125341: 409,
         144285: 408,
         125674: 408,
         124657: 407,
         129510: 404,
         130647: 403,
         49543: 402,
         61741: 402,
         130902: 401,
         127677: 401,
         138630: 400,
         144661: 399,
         128552: 398,
         125678: 398,
         128719: 397,
         144007: 396,
         130137: 396,
         94315: 396,
         142067: 395,
         134107: 390,
         133788: 389,
         141906: 387,
         67511: 386,
         77953: 384,
         131766: 384,
         126844: 384,
         63256: 382,
         19: 381,
         127969: 380,
         129400: 380,
         131565: 379,
         128187: 378,
         143230: 378,
         95996: 378,
         143279: 377,
         94203: 377,
         136499: 376,
         126317: 376,
         127048: 376,
         43866: 374,
         133995: 372,
         135839: 372,
         125746: 372,
         138659: 371,
         127937: 371,
         136168: 370,
         134794: 369,
         144090: 365,
         142353: 364,
         128909: 364,
         134929: 360,
         134013: 358,
         127121: 351,
         126423: 351,
         144017: 346,
         126641: 345,
         125880: 345,
         130436: 343,
         132184: 343,
         144039: 343,
         237: 343,
         135940: 343,
         126337: 342,
         138313: 342,
         83315: 340,
         133215: 339,
         106: 336,
         127840: 336,
         129923: 332,
         136133: 330,
         135243: 329,
         87608: 328,
         126712: 326,
         132526: 326,
         144505: 326,
         133914: 325,
         130939: 324,
         129804: 323,
         134497: 323,
         144030: 322,
         66019: 322,
         131573: 321,
         144141: 320,
         130408: 318,
         135807: 318,
         143862: 317,
         19946: 316,
         138666: 316,
         130737: 315,
         98358: 313,
         126596: 313,
         128808: 312,
         98869: 310,
         135990: 309,
         125639: 309,
         126871: 309,
         126667: 309,
         131137: 308,
         130822: 306,
         126674: 305,
         138667: 304,
         130508: 302,
         130729: 301,
         139328: 300,
         100: 300,
         127105: 300,
         132044: 299,
         136841: 299,
         138685: 297,
         52300: 296,
         137266: 296,
         129150: 295,
         126038: 295,
         137351: 293,
         83291: 291,
         126299: 289,
         140490: 289,
         132376: 288,
         84667: 285,
         69923: 283,
         35530: 282,
         138863: 281,
         128533: 280,
         136892: 280,
         125761: 277,
         84255: 277,
         129112: 277,
         131891: 277,
         127475: 276,
         144266: 276,
         129321: 275,
         125713: 275,
         97834: 274,
         138097: 274,
         130472: 272,
         125786: 272,
         144124: 272,
         140532: 272,
         144467: 272,
         144041: 271,
         138268: 270,
         133847: 268,
         232: 268,
         141836: 267,
         139764: 266,
         937: 266,
         134836: 265,
         144071: 265,
         129615: 265,
         144137: 265,
         135354: 263,
         90486: 263,
         130345: 262,
         753: 261,
         142655: 260,
         144022: 260,
         131823: 260,
         97929: 259,
         49664: 257,
         77002: 256,
         22714: 256,
         26: 255,
         127194: 254,
         144724: 254,
         129502: 253,
         93721: 253,
         89860: 252,
         99: 250,
         130722: 249,
         143948: 248,
         144058: 247,
         95351: 247,
         131767: 246,
         127919: 246,
         134521: 245,
         130728: 245,
         134583: 244,
         142451: 244,
         136849: 243,
         88781: 243,
         21: 242,
         144413: 242,
         128739: 241,
         135946: 241,
         132618: 240,
         144091: 239,
         135032: 239,
         103: 238,
         75528: 236,
         138694: 236,
         134277: 235,
         143337: 234,
         8843: 234,
         138078: 234,
         27767: 233,
         127041: 233,
         90686: 233,
         137879: 232,
         144290: 229,
         130037: 229,
         71015: 229,
         144156: 228,
         132466: 228,
         135227: 227,
         124905: 226,
         92031: 226,
         144213: 225,
         122: 224,
         248: 223,
         131903: 223,
         21876: 222,
         130973: 221,
         144219: 221,
         130288: 221,
         143600: 219,
         137844: 219,
         127033: 219,
         24: 218,
         126039: 217,
         124970: 217,
         130790: 217,
         134952: 216,
         45881: 215,
         140667: 215,
         144143: 214,
         144317: 214,
         126563: 214,
         68232: 213,
         85322: 213,
         50972: 213,
         53189: 213,
         127819: 212,
         125991: 212,
         144515: 211,
         2503: 211,
         126591: 210,
         132064: 209,
         142561: 209,
         142512: 208,
         132872: 208,
         137843: 207,
         129283: 207,
         57583: 206,
         86034: 206,
         137237: 205,
         62740: 204,
         137769: 204,
         145308: 203,
         130653: 203,
         128013: 203,
         139274: 203,
         130671: 203,
         135420: 203,
         143353: 203,
         145411: 202,
         144010: 202,
         127559: 200,
         132264: 200,
         136585: 199,
         136541: 199,
         128841: 198,
         138449: 198,
         136448: 198,
         131456: 198,
         133864: 197,
         137601: 197,
         139039: 197,
         140017: 197,
         144372: 197,
         130651: 196,
         53435: 195,
         138329: 195,
         136671: 194,

In [64]:
for n in [2, 3, 5]:
    ngrams = []
    for text in singleturn_df['res'].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        for i in range(len(tokens) - n + 1):
            ngrams.append(tuple(tokens[i:i+n]))
    
    ngram_counts = Counter(ngrams)
    
    print(f"\n=== {n}-gram ===")
    print(f"다양성: {len(ngram_counts)/len(ngrams)*100:.2f}%")
    print(f"\n상위 20개:")
    for pattern, count in ngram_counts.most_common(20):
        decoded = tokenizer.decode(list(pattern))
        print(f"  '{decoded}': {count:,}회")

=== 2-gram ===
다양성: 12.38%

상위 20개:
  'ㅋㅋ': 21,282회
  ' ㅋ': 15,380회
  'ㅠㅠ': 4,717회
  ' ㅠ': 4,521회
  '맞아': 4,454회
  ' 같아': 3,794회
  ' 진짜': 3,743회
  ' 먹': 3,412회
  '야?': 3,134회
  ' �': 3,066회
  ' 하하': 2,982회
  '어?': 2,938회
  '나는': 2,549회
  ' 싶': 2,367회
  ' 것 같': 2,366회
  ' �': 2,365회
  '나도': 2,330회
  '구나': 2,285회
  ' 뭐': 2,263회
  '?/': 2,192회

=== 3-gram ===
다양성: 44.98%

상위 20개:
  ' ㅋㅋ': 15,157회
  ' ㅠㅠ': 3,561회
  'ㅋㅋ/': 2,057회
  ' 했': 2,044회
  ' 것 같아': 1,974회
  ' 엄청': 1,577회
  ' ㅜㅜ': 1,498회
  ' 봐': 1,483회
  ' 힘': 1,360회
  ' 봤': 1,343회
  ' 근데': 1,330회
  '고 싶': 1,282회
  ' 거 같아': 1,251회
  ' 편': 1,195회
  '어 ㅋ': 1,156회
  ' 괜': 1,054회
  '아 ㅋ': 1,053회
  '��들': 1,037회
  '? ㅋ': 999회
  '��찮': 950회

=== 5-gram ===
다양성: 86.81%

상위 20개:
  '맞아 ㅋㅋ': 357회
  ' 같아 ㅋㅋ': 275회
  ' 괜찮아': 250회
  'ㅋㅋ 근데': 230회
  ' 힘들어': 217회
  ' 괜찮은': 200회
  '? ㅋㅋ/': 198회
  ' 거 같아 ㅋ': 184회
  ' 했어?': 178회
  ' 봤어?': 177회
  ' 편이야': 172회
  '그렇구나.': 167회
  '도 괜찮': 163회
  '어 ㅋㅋ/': 160회
  '구나 ㅋㅋ': 148회
  ' ㅋㅋ/그': 146회
  ' 스타일': 146회
  ' ㅋㅋ 근': 138회
  ' ㅋㅋ 나도': 129회
  ' 힘들었': 128회

In [66]:
for n in [4, 6, 7]:
    ngrams = []
    for text in singleturn_df['res'].dropna().astype(str):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        for i in range(len(tokens) - n + 1):
            ngrams.append(tuple(tokens[i:i+n]))
    
    ngram_counts = Counter(ngrams)
    
    print(f"\n=== {n}-gram ===")
    print(f"다양성: {len(ngram_counts)/len(ngrams)*100:.2f}%")
    print(f"\n상위 20개:")
    for pattern, count in ngram_counts.most_common(20):
        decoded = tokenizer.decode(list(pattern))
        print(f"  '{decoded}': {count:,}회")

=== 4-gram ===
다양성: 71.41%

상위 20개:
  ' ㅋㅋ/': 2,036회
  '어 ㅋㅋ': 1,142회
  '아 ㅋㅋ': 1,042회
  ' 힘들': 1,037회
  '? ㅋㅋ': 987회
  ' 괜찮': 950회
  '지 ㅋㅋ': 623회
  ' 봤어': 563회
  ' 했어': 549회
  ' ㅠㅠ/': 531회
  '네 ㅋㅋ': 501회
  '그렇구나': 481회
  '응 ㅋㅋ': 420회
  '야 ㅋㅋ': 414회
  '고 싶어': 402회
  ' 코로나': 396회
  ' 빨리': 391회
  ' 갑자기': 369회
  ' 챙겨': 359회
  '지 않아?': 357회

=== 6-gram ===
다양성: 94.41%

상위 20개:
  ' 거 같아 ㅋㅋ': 184회
  ' ㅋㅋ 근데': 135회
  ' ㅋㅋ/근데': 108회
  ' 거 같아 ㅠㅠ': 95회
  '는 편이야': 76회
  ' 챙겨 먹': 74회
  ' 봐 ㅋㅋ': 69회
  ' 괜찮아?': 64회
  ' 것 같아 ㅋㅋ': 64회
  '��어 ㅋㅋ': 60회
  ' 했어 ㅋ': 59회
  ' 갑자기 왜': 55회
  '그러게 말이야': 55회
  ' 재밌게 봤': 49회
  ' 괜찮은데': 49회
  ' 키우고 싶': 48회
  ' 괜찮았어': 48회
  ' 싶어 ㅋㅋ': 47회
  ' 편이야?': 46회
  '기로 했어': 46회

=== 7-gram ===
다양성: 97.62%

상위 20개:
  ' 했어 ㅋㅋ': 59회
  ' 봤어 ㅋㅋ': 37회
  ' 엄청 힘들': 33회
  ' 갑자기 왜?': 29회
  '아 진짜? ㅋㅋ': 26회
  '고 싶어 ㅋㅋ': 25회
  '아 ㅋㅋ 근데': 24회
  ' 재밌게 봤어': 24회
  '나 봐 ㅋㅋ': 24회
  '던 거 같아 ㅋㅋ': 24회
  ' 괜찮은 거 같': 24회
  '고 싶어 ㅠㅠ': 24회
  ' 잘 챙겨 먹': 23회
  '는 거 같아 ㅋㅋ': 23회
  'ㅋㅋㅋㅋㅋㅋㅋ': 23회
  ' 했지 ㅋㅋ': 22회
  '는 편이야?': 22회
  ' 키우고 싶어': 21회
  '고 싶다 ㅠㅠ': 20회
  '그렇구나 ㅋㅋ': 20회