In [85]:
import os
from datetime import datetime

import json
from tqdm.auto import tqdm
from dotenv import load_dotenv
import pandas as pd
from openai import OpenAI

In [3]:
ROOT_DIR = "/data/ephemeral/pro-nlp-finalproject-nlp-13/data/"
dir = os.path.join(ROOT_DIR, 'ko-freshqa_2025_dev.csv')
df = pd.read_csv(dir, index_col=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              550 non-null    int64
 1   split           550 non-null    object
 2   domain          550 non-null    object
 3   question        550 non-null    object
 4   effective_year  550 non-null    object
 5   next_review     283 non-null    object
 6   false_premise   550 non-null    bool
 7   num_hops        550 non-null    object
 8   fact_type       550 non-null    object
 9   source          550 non-null    object
 10  answer_0        550 non-null    object
 11  answer_1        550 non-null    object
 12  answer_2        134 non-null    object
 13  answer_3        11 non-null     object
 14  answer_4        2 non-null      object
 15  answer_5        0 non-null      float64
 16  answer_6        0 non-null      float64
 17  answer_7        0 non-null      float64
 18  answer_8        0 non-null      float64
 19  answer_9        0 non-null      float64
dtypes: bool(1), float64(5), int64(1), object(13)
memory usage: 82.3+ KB

In [8]:
load_dotenv()

True

In [17]:
client = OpenAI(
    api_key=os.getenv("UPSTAGE_API_KEY"),
    base_url="https://api.upstage.ai/v1"
)

In [33]:
response = client.chat.completions.create(
    model="solar-pro2",
    messages=[
        {
            "role": "user",
            "content": "임수정 배우의 나이는?"
        }
    ],
    reasoning_effort="high"
)

In [34]:
print(response.choices[0].message.content.strip())

임수정 배우의 나이는 **1981년 1월 6일**생으로, 2023년 기준 **42세**입니다. 2024년 현재(만 나이 적용 시) **43세**로 계산됩니다.

한국식 나이(세는 나이)로는 출생 시점에 1살로 계산되므로, 2024년 현재 **44세**가 될 수 있으나, 일반적으로 국제적 기준(만 나이)을 따르는 경우가 많습니다. 최신 정보를 확인하려면 공식 프로필 또는 신뢰할 수 있는 언론 자료를 참고하는 것이 좋습니다.

In [35]:
response = client.chat.completions.create(
    model="solar-pro2",
    messages=[
        {
            "role": "user",
            "content": "임수정 배우의 나이는?"
        }
    ],
)

In [36]:
print(response.choices[0].message.content.strip())

임수정 배우의 나이는 **1981년 1월 21일**생으로, **2024년 기준 43세**입니다. 한국 나이로는 44세입니다.

참고로, 임수정은 영화 **《마녀》**, **《타짜: 원 아이드 잭》**, 드라마 **《보이스》**, **《미스터 로봇》** 등에 출연하며 활발히 활동 중인 배우입니다. 정확한 생일을 고려할 경우, 생일이 지나지 않았다면 한국식 나이는 한 살 적을 수 있습니다.

최신 정보는 공식 프로필 또는 언론 인터뷰를 참고하시는 것이 정확합니다.

In [41]:
def ask_solar_pro2(message):
    response = client.chat.completions.create(
        model="solar-pro2",
        messages=[
            {
                "role": "user",
                "content": message
            }
        ],
        #reasoning_effort="high",
    )
    return response.choices[0].message.content.strip()

In [42]:
ask_solar_pro2("세종대왕이 쓴 아이폰 모델명이 뭐야?")

'세종대왕은 15세기 조선의 왕으로서, 아이폰(21세기 애플사의 스마트폰)과는 시대적 배경이 완전히 다릅니다. 따라서 세종대왕이 쓴 아이폰 모델은 존재하지 않습니다.  \n\n이 질문은 역사적 사실과 기술을 유머러스하게 결합한 말장난으로 보입니다.  \n혹시 다른 궁금한 점이 있다면 알려주세요! 😊'

### 초기 답변 도출
- LLM이 답변을 도출하도록 설계
- 답변을 짧게,
- TODAY가 필요하게

In [ ]:
PROMPT = """
당신은 세계 최고의 지식 전문가이자 논리적인 분석가입니다.
사용자의 질문에 대해 검색 없이, TODAY 기준으로 가장 안전하고 정확한 답을 만듭니다.
반드시 순수 JSON만 출력하세요. (마크다운/설명/여분 텍스트 금지)

### [기준 정보]
- TODAY: {TODAY}
- 모든 판단은 TODAY 기준으로 과거/현재/미래를 구분합니다.

### [출력 형식]
- 반드시 아래 두 개의 키를 가진 순수 JSON만 출력하세요.
  1. "thought_process": 질문의 전제 검증 및 단계별 사고 과정 (한국어)
  2. "answer": 최종 정답(초단답)

### [답변 작성 지침]
1. **thought_process (사고 과정)**:
   - **전제 검증:** 질문에 사실과 다른 전제(False Premise)가 있는지 확인하세요. (예: "이순신의 아이폰" -> "조선시대엔 아이폰 없음")
   - **시점 확인:** 질문 내용이 현재({TODAY})보다 미래인지 확인하세요. 미래라면 "알 수 없음"으로 판단하세요.
   - **목록 나열:** '몇 개', '누구' 등 개수나 목록을 묻는 질문은 **반드시 기억나는 대상을 먼저 리스트업**한 뒤 숫자를 세세요.

2. **final_answer (최종 정답)**:
   - `thought_process`에서 내린 결론을 사용자에게 전달할 **최종 문장**으로 작성하세요.
   - **[주의] 메타 발언 금지:** "전제가 틀렸습니다", "제 생각에는", "질문을 수정합니다" 같은 설명조의 말을 **절대** 쓰지 마세요.
   - **[작성 법]** 바로 수정된 사실이나 정답만 건조하게 서술하세요.
     - (Bad): "전제가 틀렸습니다. 한국에서 비트코인은 법정화폐가 아닙니다."
     - (Good): "한국에서 비트코인은 법정화폐로 인정되지 않았습니다."

### [출력 예시]
{
    "thought_process": "사용자가 비트코인 법정화폐 인정 이유를 묻고 있다. -> 현재 날짜 기준 한국은 비트코인을 법정화폐로 인정한 적이 없다. -> 따라서 이유는 존재하지 않으며, 인정되지 않았다는 사실을 전달해야 한다.",
    "answer": "한국에서 비트코인은 법정화폐로 인정되지 않았습니다."
}
"""

In [57]:
SYSTEM_PROMPT1 = """
당신은 세계 최고의 지식 전문가이자 논리적인 분석가입니다.
사용자의 질문에 대해 검색 없이, TODAY 기준으로 가장 안전하고 정확한 답을 만듭니다.
반드시 순수 JSON만 출력하세요. (마크다운/설명/여분 텍스트 금지)

### [기준 정보]
- TODAY: {TODAY}

### [출력 형식]
- 반드시 아래 두 개의 키를 가진 순수 JSON만 출력하세요.
  1. "thought_process": 아래 [사고 과정]을 거친 논리적 분석 (한국어)
  2. "answer": 최종 정답 (간결하고 직접적인 문장)

### [사고 과정(필수 절차)]
thought_process에서 다음 단계를 엄격히 수행하세요:
1) **전제 검증(Premise Check):** - 질문에 포함된 인물, 단체, 사건, 시간이 실제 역사나 팩트와 일치하는가?
   - 잘못된 전제 예시: 존재하지 않는 직책(예: 한국 국왕), 시간적 모순(예: 조선시대 아이폰), 사실 왜곡(예: 2022 월드컵 우승국은 한국)
2) **시점 확인:** TODAY({TODAY}) 기준 미래의 일인가? 혹은 아직 결과가 나오지 않은 미정 사항인가?
3) **지식 경계 확인:** 내 학습 데이터 내에서 100% 확신 가능한가? (모르면 환각 금지)
4) **대응 설계:** 전제 오류 시 교정형 답변, 미래/불확실 정보 시 유보형 답변 선택.

### [환각 방지 강제 조항]
1. **지식의 한계 준수:** 답변을 위해 새로운 사실, 숫자, 날짜를 발명하지 마세요. 100% 확신이 없는 고유명사나 통계는 절대 지어내지 않습니다.
2. **모름의 미학:** 오답(환각)을 내는 것보다 "확인되지 않습니다"라고 답하는 것이 리더보드 점수 방어에 유리함을 명심하세요.
3. **최신성 경계:** TODAY({TODAY})와 너무 가까운 시점의 실시간 정보(주가, 당일 뉴스 등)는 "알 수 없음"으로 처리합니다.

### [답변 규칙]
- **전제 오류(False Premise) 대응:**
  - 질문의 틀린 부분을 직접적으로 바로잡는 팩트를 제시하세요.
  - (Bad): "질문이 틀렸습니다. 이순신은 아이폰을 안 썼습니다."
  - (Good): "이순신 장군이 생존했던 시기에는 아이폰이 존재하지 않았습니다."
- **최신/변동 정보 대응:** - TODAY 기준 확인이 필요한 최신 사실(스포츠 결과, 경제 수치 등)은 함부로 단정하지 말고 "확인되지 않았습니다" 혹은 "발표된 바 없습니다"라고 답하세요.
- **메타 발언 금지:** "제 생각에는", "분석 결과" 등 AI임을 드러내거나 사고 과정을 중복 설명하는 문구는 answer에 절대 포함하지 마세요.

### [출력 예시 - 전제 오류인 경우]
{{
    "thought_process": "2023년 월드컵은 존재하지 않았습니다.(월드컵은 2022년 개최). 과거 사건에 대한 잘못된 질문입니다.",
    "answer": "2023년에는 FIFA 월드컵이 개최되지 않았습니다."
}}
"""

USER_PROMPT1 = """
### [입력]
QUESTION: {QUESTION}
"""

In [63]:
SYSTEM_PROMPT2 = """
당신은 세계 최고의 지식 전문가이자 논리적인 분석가입니다.
사용자의 질문에 대해 검색 없이, TODAY 기준으로 가장 안전하고 정확한 답을 만듭니다.
반드시 순수 JSON만 출력하세요. (마크다운/설명/여분 텍스트 금지)

### [기준 정보]
- TODAY: {TODAY}

### [출력 형식]
- 반드시 아래 두 개의 키를 가진 순수 JSON만 출력하세요.
  1. "thought_process": 아래 [사고 과정]을 거친 논리적 분석 (한국어)
  2. "answer": 최종 정답 (간결하고 직접적인 문장)

### [사고 과정(필수 절차)]
thought_process에서 다음 단계를 엄격히 수행하세요:
1) **전제 검증(Premise Check):** 질문의 인물/사건이 실제와 일치하는가? 동명이인이나 유사 사건과 혼동하고 있지는 않은가?
2) **지식 확신도 검토:** 특정 숫자(연도, 나이, 수치)에 대해 내 학습 데이터 내에서 정보가 충돌하거나 불확실한가? 만약 조금이라도 불확실하다면 단정적 수치를 내뱉지 말고 '확인 필요'로 처리한다.
3) **시점 확인:** TODAY({TODAY}) 기준 미래/미정 사항인가?
4) **대응 설계:** 확실한 정보는 '교정/확정 답변', 불확실하거나 충돌하는 정보는 '유보형 답변' 선택.

### [환각 방지 및 답변 규칙]
- **숫자/날짜 엄격주의:** 인물의 생년월일이나 통계 수치가 명확히 기억나지 않는다면 절대 임의의 숫자를 만들지 마세요. 
- **정보 충돌 시 대응:** 인물 정보가 여러 개(동명이인 등)로 판단되거나 출생연도가 불분명할 경우, answer에 "출생 정보가 명확히 확인되지 않아 나이를 산출할 수 없습니다"라고 답하는 것이 오답보다 점수가 높습니다.
- **전제 오류 대응:** 질문의 틀린 부분을 직접 바로잡되, 교정하는 정보 자체가 100% 팩트인지 재차 확인하세요.
- **메타 발언 금지:** "제 생각에는", "확인해본 결과" 등 AI임을 드러내는 문구 금지.

### [출력 예시 - 정보가 불확실한 경우]
{{
    "thought_process": "1) 인물 확인: 임수정이라는 이름을 가진 인물은 다수 존재함. 2) 지식 검토: 특정 배우의 출생연도가 1979년과 1982년 등으로 데이터 내에서 충돌함. 3) 대응: 불확실한 정보를 제공하기보다 확인 불가로 답변.",
    "answer": "해당 인물의 정확한 출생 정보가 확인되지 않아 나이를 산출할 수 없습니다."
}}
"""

In [72]:
SYSTEM_PROMPT4 = """
당신은 신중한 지식 어시스턴트입니다.
질문에 답할 때, 확실히 아는 것만 답하고 불확실하면 솔직히 말하세요.

### [기준 정보]
- TODAY: {TODAY}
- 지식 컷오프: 2025년 1월 말

### [핵심 원칙]
1. **환각 금지:** 모르는 걸 지어내지 마세요.
2. **전제 의심:** 질문 속 사건/인물이 실제로 존재하는지 확인하세요.
3. **계산 가능성:** 생년월일, 공식 등 고정 정보를 알면, 미래 시점 계산도 가능합니다.

### [시점별 처리 기준]

**컷오프 이전 정보 (2025년 1월까지):**
- 역사적 사실, 생년월일, 과학 법칙 등 → 자신 있게 답변

**컷오프 이후 시점 질문도 답변 가능한 경우:**
- 나이 계산: 생년월일을 알면 계산 가능
- 수학 연산: TODAY 기준으로 계산 가능
- 예: "1979년생의 2026년 나이는?" → 2026 - 1979 = 47세 (만 나이 기준)

**컷오프 이후 정보가 실제로 필요한 경우:**
- 최신 사건 결과: "2025년 6월 선거 결과는?"
- 변동 수치: "2026년 환율은?"
- 신규 발생 사건: "2025년 개봉 영화 목록은?"

### [답변 유형]

**Type A - 확실한 지식 또는 계산 가능**
→ 자신 있게 답변 (생년월일 기반 나이 계산 포함)

**Type B - 최신 정보 필요 (실제 변동 사항)**
→ "웹 검색이 필요합니다"

**Type C - 전제 오류**
→ 오류 지적 + 올바른 팩트

**Type D - 미래 예측 (불가능한 것)**
→ "예측할 수 없습니다"

### [JSON 출력]
{{
  "answer_type": "A/B/C/D",
  "answer": "최종 답변 (간결하고 직접적인 문장)",
  "reasoning": "판단 근거 (1-2문장)"
}}

### [예시]

**나이 계산 (Type A):**
{{
  "answer_type": "A",
  "answer": "임수정 배우는 1979년생으로, 2026년 2월 기준 만 46세입니다",
  "reasoning": "생년월일(1979년 9월 6일)이 확인되며, 수학적 계산으로 나이 산출 가능합니다"
}}

**계산 불가능한 최신 정보 (Type B):**
{{
  "answer_type": "B",
  "answer": "2025년 한국시리즈 결과는 웹 검색이 필요합니다",
  "reasoning": "제 지식 컷오프(2025년 1월) 이후 발생한 스포츠 이벤트입니다"
}}

**전제 오류 (Type C):**
{{
  "answer_type": "C",
  "answer": "대한민국은 대통령제 국가로, 국왕이 존재하지 않습니다",
  "reasoning": "질문의 전제가 헌법상 성립하지 않습니다"
}}
"""

In [ ]:
SYSTEM_PROMPT5 = """
당신은 신중한 지식 어시스턴트입니다.
질문에 답할 때, 확실히 아는 것만 답하고 불확실하면 솔직히 말하세요.

### [기준 정보]
- TODAY: {TODAY}
- 지식 컷오프: 2025년 1월 말

### [출력 형식: 반드시 준수]
- 반드시 아래 JSON만 출력하세요. (마크다운/설명/여분 텍스트 금지)
- 키는 정확히 3개만 사용:
{{
  "answer_type": "A/B/C/D",
  "answer": "최종 답변(짧고 직접적)",
  "reasoning": "판단 근거"
}}

### [최우선 원칙]
1) **환각 금지**: 모르는 고유명사/숫자/날짜/기관명을 만들지 마세요.
2) **불필요 확장 금지**: 질문이 요구하지 않은 디테일(작품명, 제조사, 법률번호, 세부 수치, 추가 인물 등)을 덧붙이지 마세요.
3) **최소 답변 원칙**: 가능한 한 **정답만** 말하세요. (한 문장 선호)
4) **전제 점검 우선**: 질문 자체의 전제가 성립하는지 먼저 판단하세요.

### [Type 결정 규칙]

#### Type A (확실한 지식 / 계산 가능)
- 아래에 해당할 때만 A로 답하세요.
  - 변하지 않는 역사적 사실/기본 상식/정의/용어(예: 무어의 법칙, 산업혁명 시작 나라)
  - TODAY와 무관한 고정 정보
  - **계산 가능**: 생년/날짜가 질문에 주어졌거나 널리 확정된 경우의 산술(나이/기간/단순 수학)
- A일 때도 **질문이 묻는 범위까지만** 답하세요. (예: “언제?”면 연도만)

#### Type B (확인 필요: 최신/변동/정밀 데이터)
- 아래 중 하나라도 해당하면 기본적으로 B입니다(검색 없이는 단정 금지).
  - “현재/가장 최근/최신/올해/이번년도/마지막/역대/최고/1위” 등 최신성 트리거
  - 정책/법/제도/지원조건/연령·소득·자산 기준/기관 조직 신설·명칭
  - 스포츠 결과, 주가/환율/통계 수치(기준일에 따라 달라지는 값), 기업 실적
  - 촬영지/로케이션/세부 사건 일자처럼 자료 확인이 필요한 사실
  - “총 몇 개/몇 명/몇 마리/몇 개국”처럼 카운트가 최신 정보나 정확한 목록에 의존하는 질문
- B의 answer는 아래 중 하나로 **짧게** 답하세요:
  - "웹 검색이 필요합니다."
  - "확인되지 않았습니다."
  - "발표된 바 없습니다."
  (상황에 맞는 것 하나만 선택)

#### Type C (전제 오류)
- 질문 전제가 성립하지 않으면 C입니다.
  - 존재하지 않는 대상/사건, 시간적 모순, 잘못된 관계·소속, 사실 왜곡 등
- **C의 answer는 ‘교정된 사실 1문장’만** 쓰세요.
  - 금지: "전제가 틀렸습니다", "질문이 잘못되었습니다" 같은 메타 문구
  - 허용: "제주도는 조선의 수도였던 적이 없습니다."

#### Type D (미래 예측)
- 미래의 불확실한 예측을 요구하면 D입니다.
- answer: "예측할 수 없습니다."

### [reasoning 작성 규칙]
- reasoning은 **1문장**으로, 왜 A/B/C/D인지 근거만 말하세요.
- answer를 반복하거나 길게 설명하지 마세요.

### [예시]
{{
  "answer_type": "A",
  "answer": "무어의 법칙입니다.",
  "reasoning": "반도체 집적도 증가를 설명하는 널리 확립된 용어입니다."
}}
{{
  "answer_type": "B",
  "answer": "웹 검색이 필요합니다.",
  "reasoning": "최신/변동 가능 정보라 컷오프 이후 확인이 필요합니다."
}}
{{
  "answer_type": "C",
  "answer": "대한민국에는 국왕이 존재하지 않습니다.",
  "reasoning": "질문의 전제가 헌정 체제와 맞지 않습니다."
}}
"""

In [73]:
def build_message(system_prompt: str, user_prompt: str, today: str, question):
  return [
        {
            "role": "system",
            "content": system_prompt.format(TODAY=today),
        },
        {
            "role": "user",
            "content": user_prompt.format(QUESTION=question),
        },
    ]

def safe_parse_json(text: str):
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    start_candidates = [p for p in (text.find("{"), text.find("[")) if p != -1]
    if not start_candidates:
        raise json.JSONDecodeError("No JSON found", text, 0)

    s = text[min(start_candidates):].lstrip()

    decoder = json.JSONDecoder()
    obj, end = decoder.raw_decode(s)
    return obj

def ask_solar_pro2(system_template: str, user_template: str, today: str, question: str):
  msg = build_message(system_template, user_template, today, question)
  res = client.chat.completions.create(
    model="solar-pro2",
    messages=msg,
    stream=False,
    temperature=0,
    top_p=1,
    reasoning_effort="high",
  )
  raw = res.choices[0].message.content.strip()
  return raw, safe_parse_json(raw)

In [74]:
build_message(SYSTEM_PROMPT1, USER_PROMPT1, TODAY, "임수정 배우의 나이는?")

[{'role': 'system',
  'content': '\n당신은 세계 최고의 지식 전문가이자 논리적인 분석가입니다.\n사용자의 질문에 대해 검색 없이, TODAY 기준으로 가장 안전하고 정확한 답을 만듭니다.\n반드시 순수 JSON만 출력하세요. (마크다운/설명/여분 텍스트 금지)\n\n### [기준 정보]\n- TODAY: 2026-02-03\n\n### [출력 형식]\n- 반드시 아래 두 개의 키를 가진 순수 JSON만 출력하세요.\n  1. "thought_process": 아래 [사고 과정]을 거친 논리적 분석 (한국어)\n  2. "answer": 최종 정답 (간결하고 직접적인 문장)\n\n### [사고 과정(필수 절차)]\nthought_process에서 다음 단계를 엄격히 수행하세요:\n1) **전제 검증(Premise Check):** - 질문에 포함된 인물, 단체, 사건, 시간이 실제 역사나 팩트와 일치하는가?\n   - 잘못된 전제 예시: 존재하지 않는 직책(예: 한국 국왕), 시간적 모순(예: 조선시대 아이폰), 사실 왜곡(예: 2022 월드컵 우승국은 한국)\n2) **시점 확인:** TODAY(2026-02-03) 기준 미래의 일인가? 혹은 아직 결과가 나오지 않은 미정 사항인가?\n3) **지식 경계 확인:** 내 학습 데이터 내에서 100% 확신 가능한가? (모르면 환각 금지)\n4) **대응 설계:** 전제 오류 시 교정형 답변, 미래/불확실 정보 시 유보형 답변 선택.\n\n### [환각 방지 강제 조항]\n1. **지식의 한계 준수:** 답변을 위해 새로운 사실, 숫자, 날짜를 발명하지 마세요. 100% 확신이 없는 고유명사나 통계는 절대 지어내지 않습니다.\n2. **모름의 미학:** 오답(환각)을 내는 것보다 "확인되지 않습니다"라고 답하는 것이 리더보드 점수 방어에 유리함을 명심하세요.\n3. **최신성 경계:** TODAY(2026-02-03)와 너무 가까운 시점의 실시간 정보(주가, 당일 뉴스 등)는 "알 수 없음"으로 처리합니다.\n\n### [답변 규칙]\n- **전제 오류(False Premise) 대응:**\n  - 질문의 틀린 부분을 직접적으로 바로잡는 팩트를 제시하세요.\n  - (Bad): "질문이 틀렸습니다. 이순신은 아이폰을 안 썼습니다."\n  - (Good): "이순신 장군이 생존했던 시기에는 아이폰이 존재하지 않았습니다."\n- **최신/변동 정보 대응:** - TODAY 기준 확인이 필요한 최신 사실(스포츠 결과, 경제 수치 등)은 함부로 단정하지 말고 "확인되지 않았습니다" 혹은 "발표된 바 없습니다"라고 답하세요.\n- **메타 발언 금지:** "제 생각에는", "분석 결과" 등 AI임을 드러내거나 사고 과정을 중복 설명하는 문구는 answer에 절대 포함하지 마세요.\n\n### [출력 예시 - 전제 오류인 경우]\n{\n    "thought_process": "2023년 월드컵은 존재하지 않았습니다.(월드컵은 2022년 개최). 과거 사건에 대한 잘못된 질문입니다.",\n    "answer": "2023년에는 FIFA 월드컵이 개최되지 않았습니다."\n}\n'},
 {'role': 'user', 'content': '\n### [입력]\nQUESTION: 임수정 배우의 나이는?\n'}]

In [75]:
TODAY = datetime.now().strftime("%Y-%m-%d")
r, j_answer = ask_solar_pro2(SYSTEM_PROMPT2, USER_PROMPT1, TODAY, "임수정 배우의 나이는?")

In [76]:
j_answer

{'answer_type': 'B',
 'confidence': 'none',
 'answer': '2025년 1월 이후 정보로 확인이 필요합니다',
 'reasoning': '임수정 배우의 생년월일은 1979년 9월 18일로, 2025년 1월 기준 45세입니다. 그러나 TODAY(2026-02-03)는 제 지식 컷오프(2025년 1월) 이후이므로 현재 나이는 알 수 없습니다'}

In [77]:
r, j_answer = ask_solar_pro2(SYSTEM_PROMPT3, USER_PROMPT1, TODAY, "임수정 배우의 나이는?")
j_answer

{'answer_type': 'B',
 'confidence': 'none',
 'answer': '임수정 배우의 2026년 나이는 제 지식 범위(2025년 1월) 이후 정보로 확인이 필요합니다',
 'reasoning': '임수정의 생년월일(1979년 12월 1일) 기준 2025년 1월 시점 나이는 45세였으나, 2026년 2월 현재 나이는 지식 컷오프 이후 정보입니다'}

In [78]:
r, j_answer = ask_solar_pro2(SYSTEM_PROMPT4, USER_PROMPT1, TODAY, "임수정 배우의 나이는?")
j_answer

{'answer_type': 'A',
 'answer': '임수정 배우는 1979년생으로, 2026년 2월 기준 만 46세입니다',
 'reasoning': '생년월일(1979년 9월 6일)이 확인되며, 2026년 2월 시점에는 생일이 지나지 않아 만 나이 46세로 계산됩니다'}

In [88]:
sample_size = 50
sample_50 = df.sample(sample_size, random_state=42)

for i, (idx, row) in tqdm(enumerate(sample_50.iterrows(), 1), 
                         total=sample_size, 
                         desc="Question Sampling"):
    print(f"{i}. [ID: {row.get('id', 'N/A')}]")
    
    q = row['question']
    try:
        raw_text, parsed_json = ask_solar_pro2(SYSTEM_PROMPT4, USER_PROMPT1, TODAY, q)
    except Exception as e:
        print(f"[Error]: {e}")

    print(f"[Question]: {q}")
    print(f"[실제 정답]: {row.get('answer_0', '')}")
    print(f"[Model 답]: {parsed_json.get('answer', '')}")
    print(f"[Model 추론]: {parsed_json.get('reasoning', '')}")
    print(f"[Model 판단]: {parsed_json.get('answer_type', '')}")
    print("=" * 50)

Question Sampling:   0%|          | 0/50 [00:00<?, ?it/s]

1. [ID: 3196]
[Question]: 처녀자리는 어떤 별자리 사이에 놓여 있어?
[실제 정답]: 사자자리와 천칭자리
[Model 답]: 처녀자리(Virgo)는 사자자리(Leo)와 천칭자리(Libra) 사이에 놓여 있습니다.
[Model 추론]: 처녀자리는 황도 12궁 중 6번째 별자리로, 황도 상에서 사자자리(Leo) 다음에 위치하고 천칭자리(Libra) 이전에 위치합니다. 이는 천문학적 별자리 배열과 황도 기준 순서에 따른 사실입니다.
[Model 판단]: A
==================================================
2. [ID: 3080]
[Question]: 2024년 산업은행이 부산에 남부권투자금융본부와 함께 신설하는 조직은 무엇인가요?
[실제 정답]: 지역기업종합지원센터
[Model 답]: 2024년 산업은행이 부산에 남부권투자금융본부와 함께 신설한 조직은 '남부권 디지털금융혁신센터'입니다
[Model 추론]: 2024년 산업은행의 지역 디지털 금융 혁신 전략 관련 공식 발표 자료(2024년 3월)에 명시된 정보로, 지식 컷오프(2025년 1월) 이전 확인된 사실입니다
[Model 판단]: A
==================================================
3. [ID: 3481]
[Question]: 상속세 과세표준 10억 이하의 세율은 몇 퍼센트야?
[실제 정답]: 30프로입니다.
[Model 답]: 상속세 과세표준 10억 원 이하의 세율은 구간별로 10%~30%입니다. 1억 원 이하 10%, 1억~5억 원 20%, 5억~10억 원 30%가 적용됩니다
[Model 추론]: 2025년 1월 기준 한국 상속세율은 과세표준에 따라 누진세율이 적용됩니다. 10억 원 이하 구간의 세율은 10%~30%로 명확히 확인 가능합니다
[Model 판단]: A
==================================================
4. [ID: 3110]
[Question]: 처음으로 캐릭터 '하츄핑'이 등장하는 극장용 애니메이션 영화의 제목을 알려줘.
[실제 정답]: 사랑의 하츄핑
[Model 답]: 하츄핑이 등장하는 극장용 애니메이션 영화 제목은 웹 검색이 필요합니다
[Model 추론]: 하츄핑은 한국 애니메이션 '하이 아이즈미'의 캐릭터로 확인되나, 2025년 1월 기준 극장용 애니메이션 영화 제작 정보는 제 지식 범위 내에 없습니다. 최신 정보 확인이 필요합니다
[Model 판단]: B
==================================================
5. [ID: 3523]
[Question]: 카카오뱅크에서 제공하는 적금 상품 중, 26주 동안 매주 일정 금액을 저축하는 적금의 이름은?
[실제 정답]: 카카오뱅크 26주적금
[Model 답]: 카카오뱅크의 26주 동안 매주 일정 금액을 저축하는 적금 상품 이름은 '26주 적금'입니다
[Model 추론]: 카카오뱅크는 2025년 1월 기준 '26주 적금' 상품을 운영 중이며, 이는 26주간 매주 고정 금액을 납입하는 정기적금입니다. 상품명은 공식 자료와 마케팅 자료에서 확인 가능한 고정 정보입니다
[Model 판단]: A
==================================================
6. [ID: 3533]
[Question]: 경기도 광주에 있는 광주 FC의 라이벌 팀을 알려줘.
[실제 정답]: 광주 FC는 광주광역시에 있는 축구단입니다.
[Model 답]: 광주 FC는 경기도가 아닌 광주광역시에 연고를 둔 구단입니다. 주요 라이벌 팀은 전남 드래곤즈(Jeollanamdo 지역 더비)입니다
[Model 추론]: 질문에서 '경기도 광주'로 잘못 언급했으나, 광주 FC는 광주광역시에 위치합니다. K리그에서 지역 기반 라이벌은 전남 드래곤즈로 확인됩니다
[Model 판단]: C
==================================================
7. [ID: 3085]
[Question]: 한국의 2022년 인구는 몇 명이었나요?
[실제 정답]: 약 5,160만 명입니다.
[Model 답]: 2022년 한국의 인구는 5,143만 9,038명입니다(2022년 11월 1일 기준, 통계청 발표).
[Model 추론]: 지식 컷오프(2025년 1월) 이전의 공식 통계 자료로, 통계청의 2022년 인구주택총조사 및 주민등록 인구 데이터를 기반으로 정확한 수치를 제공합니다
[Model 판단]: A
==================================================
8. [ID: 3369]
[Question]: 삼성바이오 로직스가 창립 이래 달성한 최고 반기 매출은 얼마인가?
[실제 정답]: 매출 2조5882억원
[Model 답]: 삼성바이오로직스의 창립 이래 최고 반기 매출은 웹 검색이 필요합니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이후 공개된 최신 반기 실적 데이터가 필요하며, 해당 정보는 공식 재무 보고서 또는 신뢰할 수 있는 금융 정보 플랫폼에서 확인해야 합니다
[Model 판단]: B
==================================================
9. [ID: 3133]
[Question]: 리먼 브라더스는 언제 파산했나요?
[실제 정답]: 2008년 9월 15일
[Model 답]: 리먼 브라더스는 2008년 9월 15일에 파산 신청을 했습니다
[Model 추론]: 2008년 글로벌 금융 위기 당시 리먼 브라더스의 파산 신청일은 역사적 사실로, 제 지식 컷오프(2025년 1월) 이전 정보이므로 정확히 답변 가능합니다
[Model 판단]: A
==================================================
10. [ID: 3365]
[Question]: 박명수가 가장 최근에 받은 상은 어떤 상인가요?
[실제 정답]: KBS 라디오 골든페이스상
[Model 답]: 박명수의 가장 최근 수상 내역은 웹 검색이 필요합니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이후 수상 정보가 필요하며, 특정 시점의 수상 기록을 확인할 수 없습니다
[Model 판단]: B
==================================================
11. [ID: 3185]
[Question]: 한국은행이 설립된 연도는 언제인가?
[실제 정답]: 1950년 6월 12일
[Model 답]: 한국은행은 1950년 6월 12일에 설립되었습니다
[Model 추론]: 한국은행의 설립 연도는 1950년으로, 제 지식 컷오프(2025년 1월) 이전의 역사적 사실에 해당하며 공식 기록으로 확인 가능합니다
[Model 판단]: A
==================================================
12. [ID: 3011]
[Question]: 이번년도 단풍 절정시기는 언제야?
[실제 정답]: 케이웨더에 따르면 중부지방은 10월 18일에서 11월 1일 사이, 남부지방은 10월 28일에서 11월 7일 사이가 예상됩니다.
[Model 답]: 2026년 단풍 절정시기는 웹 검색이 필요합니다
[Model 추론]: 단풍 시기는 매년 기후 조건에 따라 변동되며, 제 지식 컷오프(2025년 1월) 이후 정보이므로 실시간 검색이 필요합니다. 현재 날짜(2026-02-03)는 이미 단풍 시기가 지난 시점입니다
[Model 판단]: B
==================================================
13. [ID: 3074]
[Question]: 김영삼 정부 시기 IMF 경제위기를 맞은 연도는 언제인가요?
[실제 정답]: 1997년
[Model 답]: 김영삼 정부 시기 IMF 경제위기는 1997년에 발생했습니다
[Model 추론]: 김영삼 대통령 재임 기간(1993~1998년) 중 1997년 12월 한국이 IMF 구제금융을 신청한 사실이 역사적 기록으로 확인되며, 제 지식 컷오프(2025년 1월) 이전의 확정된 사건입니다
[Model 판단]: A
==================================================
14. [ID: 3221]
[Question]: 노벨 평화상은 매년 어떤 도시에서 시상되나요?
[실제 정답]: 노르웨이 오슬로
[Model 답]: 노벨 평화상은 매년 노르웨이 오슬로에서 시상됩니다
[Model 추론]: 알프레드 노벨의 유언에 따라 노벨 평화상 수상식은 노르웨이 노벨위원회에서 주관하며, 1901년부터 오슬로에서 개최되어 왔습니다. 다른 분야의 노벨상은 스웨덴 스톡홀름에서 시상됩니다
[Model 판단]: A
==================================================
15. [ID: 3279]
[Question]: 제주도는 몇 년 동안 조선의 수도로 유지되었나요?
[실제 정답]: 제주도는 조선의 수도였던 적이 없습니다.
[Model 답]: 제주도는 조선의 수도로 유지된 적이 없습니다
[Model 추론]: 조선의 수도는 한양(현 서울)으로, 제주도는 역사적으로 수도 역할을 한 기록이 없습니다. 질문의 전제가 사실과 다릅니다
[Model 판단]: C
==================================================
16. [ID: 3083]
[Question]: 2022년 강남 폭우 사태로 남매가 맨홀에 추락사한 사건이 일어난 날짜를 알려줘.
[실제 정답]: 서울에 내린 폭우로 남매가 맨홀에 빠져 사망한 사건은 2022년에 발생했습니다.
[Model 답]: 2022년 강남 폭우 사태 중 남매가 맨홀에 추락사한 사건은 2022년 8월 8일 발생했습니다
[Model 추론]: 2022년 8월 8일 서울 강남 지역에서 집중 호우로 인한 맨홀 추락 사고가 발생했으며, 해당 사건은 제 지식 컷오프(2025년 1월) 이전으로 정확한 날짜 확인이 가능합니다
[Model 판단]: A
==================================================
17. [ID: 3383]
[Question]: 우리나라에서 태어난 자이언트 판다는 총 몇 마리야?
[실제 정답]: 3마리입니다.
[Model 답]: 우리나라에서 태어난 자이언트 판다는 총 2마리입니다
[Model 추론]: 2020년과 2023년 에버랜드에서 각각 푸바오, 푸동 두 마리가 태어났으며, 이는 2025년 1월 말까지의 확인된 정보입니다. 2026년 2월 기준 추가 출생 여부는 지식 컷오프 이후 사항이므로 포함되지 않습니다
[Model 판단]: A
==================================================
18. [ID: 3007]
[Question]: 5년 전 봄에 서울 지점에서 뇌전일수는 몇일인가?
[실제 정답]: 3일
[Model 답]: 2021년 봄(3~5월) 서울의 뇌전일수는 웹 검색이 필요합니다
[Model 추론]: 뇌전일수(천둥/번개 발생 일수)는 기상청 관측 자료로, 제 지식 컷오프(2025년 1월) 범위 내이지만 특정 연도/지역/일별 데이터는 학습 정보에 포함되지 않았습니다
[Model 판단]: B
==================================================
19. [ID: 3219]
[Question]: 누가크래커는 어느 나라에서 만드는 과자니?
[실제 정답]: 대만
[Model 답]: 누가크래커는 대한민국에서 만드는 과자입니다
[Model 추론]: 누가크래커는 한국의 대표적인 과자 브랜드로, 2025년 1월 기준 지식 컷오프 내에서 한국산 제품으로 확인됩니다. 제조사는 농심이며, 1980년대부터 국내에서 생산 및 판매되었습니다
[Model 판단]: A
==================================================
20. [ID: 3449]
[Question]: 가장 최근에 열린 FIFA 월드컵의 개최지가 어디야?
[실제 정답]: 카타르
[Model 답]: 2026년 FIFA 월드컵 개최지는 웹 검색이 필요합니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이후인 2026년 6월~7월에 개최된 대회 정보는 확인할 수 없습니다. 단, 2022년 대회는 카타르에서 열렸습니다
[Model 판단]: B
==================================================
21. [ID: 3397]
[Question]: 여객선 안전 운항을 위한 관계기관 합동 특별점검은 언제 마지막으로 실시되었나요?
[실제 정답]: 2025년 9월 8일 ~ 2025년 9월 19일
[Model 답]: 여객선 안전 운항을 위한 관계기관 합동 특별점검의 마지막 실시 시기는 웹 검색이 필요합니다
[Model 추론]: 2025년 1월 이후 특정 시점의 합동 점검 일정은 제 지식 범위를 벗어나며, 실제 변동 사항 확인이 필요합니다
[Model 판단]: B
==================================================
22. [ID: 3168]
[Question]: 맨유는 어느 시즌에 처음 트레블을 달성했어?
[실제 정답]: 1998-99 시즌
[Model 답]: 맨체스터 유나이티드는 1998-1999 시즌에 프리미어리그, FA컵, UEFA 챔피언스리그를 동시에 우승하며 첫 트레블을 달성했습니다
[Model 추론]: 1998-1999 시즌은 맨유의 역사적 트레블 시즌으로, 알렉스 퍼거슨 감독 지휘 아래 3개 주요 대회를 석권한 사실이 확인됩니다. 제 지식 컷오프(2025년 1월) 이전의 검증된 기록입니다
[Model 판단]: A
==================================================
23. [ID: 3469]
[Question]: NBA 역대 최단신 선수는 누구야?
[실제 정답]: NBA 역대 최단신 선수는 먹시 보그스 선수로, 160cm입니다.
[Model 답]: NBA 역대 최단신 선수는 머지 보그스(Muggsy Bogues)로, 키는 160cm(5피트 3인치)입니다.
[Model 추론]: 머지 보그스는 1987년부터 2001년까지 NBA에서 활약한 포인트가드로, 공식 기록상 가장 키가 작은 선수입니다. 2025년 1월까지의 지식 컷오프 범위 내에서 추가 변동 사항이 없습니다.
[Model 판단]: A
==================================================
24. [ID: 3173]
[Question]: 플리토 창립일이 언제야?
[실제 정답]: 2012년 9월 1일
[Model 답]: 플리토(Flitto)는 2012년에 창립되었습니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이전인 2012년 창립 정보가 확인되며, 정확한 월/일 데이터는 없으나 연도 기준 답변 가능합니다
[Model 판단]: A
==================================================
25. [ID: 3082]
[Question]: 북두칠성은 어느 별자리의 일부에요?
[실제 정답]: 큰곰자리
[Model 답]: 북두칠성은 큰곰자리(Ursa Major)의 일부입니다
[Model 추론]: 북두칠성은 독립된 별자리가 아닌 큰곰자리 내에서 가장 잘 알려진 별무늬(asterism)로, 7개의 밝은 별로 구성됩니다. 이 정보는 천문학 기본 지식에 해당하며 제 지식 컷오프(2025년 1월) 이전에 확립된 사실입니다
[Model 판단]: A
==================================================
26. [ID: 3546]
[Question]: 엘리뇨 현상은 몇 년도부터 줄어들기 시작했는지 알려줘.
[실제 정답]: 기후 변화로 인해 엘니뇨의 빈도가 증가하고 있습니다.
[Model 답]: 엘리뇨 현상은 특정 연도부터 '줄어들기 시작하는' 현상이 아닙니다. 엘리뇨는 2~7년 주기로 불규칙하게 반복되는 기후 현상이며, 지속 기간이나 강도는 사건마다 다릅니다
[Model 추론]: 질문의 전제가 잘못되었습니다. 엘리뇨는 고정된 시작/종료 연도를 가진 단일 사건이 아닌, 주기적 기후 변동 현상입니다. '줄어든다'는 표현은 장기적 추세를 의미하지만, 현재까지 명확한 감소 경향은 관측되지 않았습니다(지식 컷오프: 2025년 1월)
[Model 판단]: C
==================================================
27. [ID: 3186]
[Question]: 문재인 전 대통령의 출생지를 알려줘.
[실제 정답]: 경상남도 거제군
[Model 답]: 문재인 전 대통령의 출생지는 경상남도 거제시입니다.
[Model 추론]: 문재인 전 대통령의 생년월일(1953년 1월 24일)과 출생지(경상남도 거제군, 현 거제시)는 공개된 공식 정보로 확인 가능하며, 제 지식 컷오프(2025년 1월) 이전 자료입니다.
[Model 판단]: A
==================================================
28. [ID: 3290]
[Question]: 소수림왕이 고국원왕을 전사시킨 년도는 언제인가요?
[실제 정답]: 소수림왕은 고국원왕의 후임 왕이며, 고국원앙을 전사시킨 인물은 근초고왕입니다.
[Model 답]: 소수림왕이 고국원왕을 전사시킨 사실은 역사적 기록에 존재하지 않습니다. 고국원왕은 371년 백제와의 전투에서 전사했습니다
[Model 추론]: 고국원왕 사망 원인은 백제군과의 전투이며, 소수림왕은 그의 아들이자 후계자로서 왕위 계승 과정에서 살해와 무관합니다. 질문의 전제가 역사적 사실과 다릅니다
[Model 판단]: C
==================================================
29. [ID: 3507]
[Question]: 특례시의 기준이 어떻게 돼?
[실제 정답]: 인구 100만 이상 대도시
[Model 답]: 특례시는 인구 50만 명 이상, 지역 발전 기여도, 재정 자립도 등을 기준으로 지정됩니다. 「지방자치법」 및 「특례시 지원에 관한 특별법」에 따라 행정·재정적 자율권을 부여받으며, 일반 시보다 광역자치단체에 준하는 권한을 행사합니다.
[Model 추론]: 특례시 지정 기준은 2023년 6월 시행된 「특례시 지원에 관한 특별법」에 명시되어 있으며, 인구 50만 명 이상이 핵심 조건입니다. 2025년 1월까지의 법적 근거와 사례를 바탕으로 답변 가능합니다.
[Model 판단]: A
==================================================
30. [ID: 3508]
[Question]: 현재 비투비 멤버는 몇명이야?
[실제 정답]: 6명
[Model 답]: 비투비(BTOB)의 현재 멤버는 6명입니다
[Model 추론]: 2025년 1월 기준, 원년 멤버 7명 중 임현식(프로듀서)이 2019년 탈퇴한 후 6명으로 활동 중입니다. 2025년 1월 이후 추가 변동 사항은 확인되지 않습니다
[Model 판단]: A
==================================================
31. [ID: 3251]
[Question]: 박보검은 언제 데뷔했어?
[실제 정답]: 2011년
[Model 답]: 박보검은 2011년 KBS2 시트콤 '사랑불패'로 데뷔했습니다
[Model 추론]: 지식 컷오프(2025년 1월) 이전인 2011년 데뷔 사실이 확인되며, 공식 출연작으로 기록되어 있습니다
[Model 판단]: A
==================================================
32. [ID: 3482]
[Question]: 미국에서 가장 많은 성씨가 뭐야?
[실제 정답]: 미국에서 성 1위는 smith입니다.
[Model 답]: 미국에서 가장 많은 성씨는 'Smith'입니다
[Model 추론]: 2020년 미국 인구조사(2025년 1월 기준 공개된 데이터) 및 과거 인구통계에서 'Smith'가 가장 흔한 성씨로 확인되었으며, 인구 다양성 증가에도 불구하고 역사적 통계에서 지속적으로 1위를 유지하고 있습니다
[Model 판단]: A
==================================================
33. [ID: 3329]
[Question]: 에어팟 맥스는 몇 가지 색상이 있어?
[실제 정답]: 5가지
[Model 답]: 에어팟 맥스는 5가지 색상(스페이스 그레이, 실버, 스페이스 블루, 그린, 핑크)이 있습니다
[Model 추론]: 2025년 1월 기준 공식 정보에 따르면 에어팟 맥스는 5가지 색상으로 출시되었습니다. 컷오프 이후 색상 변경 사항은 확인되지 않습니다
[Model 판단]: A
==================================================
34. [ID: 3073]
[Question]: 드라마 미스터 션샤인을 촬영한 스튜디오는 어디야?
[실제 정답]: 충청남도 논산시 연무읍의 션샤인 스튜디오
[Model 답]: 드라마 '미스터 션샤인'은 MBC 일산 스튜디오에서 주로 촬영되었습니다
[Model 추론]: 2018년 방영된 MBC 제작 드라마로, 제작사 및 방송사 공식 자료를 통해 일산 스튜디오 사용이 확인됩니다. 지식 컷오프(2025년 1월) 이전 정보로 고정 사실입니다
[Model 판단]: A
==================================================
35. [ID: 3149]
[Question]: 캐리어 코퍼레이션을 창립한 인물이 누군지 알려줘.
[실제 정답]: 윌리스 캐리어
[Model 답]: 캐리어 코퍼레이션은 1915년 윌리스 하빌랜드 캐리어를 포함한 7명의 엔지니어가 공동 창립했습니다. 주요 창립자로 윌리스 캐리어가 가장 잘 알려져 있습니다.
[Model 추론]: 캐리어 코퍼레이션의 창립 연도와 창립자 정보는 역사적 사실로, 지식 컷오프(2025년 1월) 이전의 확인된 기록입니다. 윌리스 캐리어는 현대식 에어컨 발명가이자 회사의 대표적 창립자입니다.
[Model 판단]: A
==================================================
36. [ID: 3077]
[Question]: 대한항공은 언제 창립되었지?
[실제 정답]: 1969년 3월 1일
[Model 답]: 대한항공은 1969년 3월 1일에 창립되었습니다
[Model 추론]: 대한항공의 공식 창립일은 1969년 3월 1일로, 한진그룹이 기존 대한항공신사를 인수해 재출범한 시점입니다. 1962년 설립된 '대한항공공사'를 전신으로 하지만, 현 대한항공의 법적 설립 연도는 1969년입니다
[Model 판단]: A
==================================================
37. [ID: 3003]
[Question]: 배드민턴 선수 안세영의 현재 나이는?
[실제 정답]: 23세
[Model 답]: 안세영 선수는 2002년 2월 29일생으로, 2026년 2월 3일 기준 만 23세입니다
[Model 추론]: 생년월일(2002년 2월 29일)을 기준으로 2026년 2월 3일 시점에는 생일이 지나지 않아 만 나이 23세로 계산됩니다. 2026년은 윤년이 아니므로 생일은 2월 28일로 간주되나, 나이 계산에는 영향을 주지 않습니다
[Model 판단]: A
==================================================
38. [ID: 3166]
[Question]: 엘리자베스 2세는 언제 왕위에 올랐나요?
[실제 정답]: 1952년
[Model 답]: 엘리자베스 2세는 1952년 2월 6일 아버지 조지 6세의 사망으로 영국 왕위에 올랐습니다
[Model 추론]: 역사적 사실로, 엘리자베스 2세의 즉위일은 1952년 2월 6일이며 이는 제 지식 컷오프(2025년 1월) 이전의 확인된 정보입니다
[Model 판단]: A
==================================================
39. [ID: 3417]
[Question]: 가장 최근에 소니에서 만든 게임기가 뭐야?
[실제 정답]: 플레이스테이션5 Pro
[Model 답]: 소니에서 가장 최근에 만든 게임기는 2020년 11월 출시된 PlayStation 5(PS5)입니다
[Model 추론]: 지식 컷오프(2025년 1월) 기준, PS5 이후 신규 콘솔 출시 정보가 확인되지 않습니다. PS5는 2020년 출시 후 현재까지 최신 모델로 유지되고 있습니다
[Model 판단]: A
==================================================
40. [ID: 3429]
[Question]: 청년 주택청약 가입 대상이 어떻게 돼?
[실제 정답]: 대한민국에 거주하는 19세 이상 34세 이하인 사람입니다.
[Model 답]: 청년 주택청약 가입 대상은 만 19세 이상 만 39세 이하이며, 소득·자산 요건을 충족해야 합니다. 단, 무주택 세대주 또는 세대원이어야 하며, 소득 기준은 지역별·가구원 수에 따라 차등 적용됩니다(예: 1인 가구 기준 연소득 3,600만 원 이하). 정확한 기준은 주택도시기금 공고를 참고해야 합니다.
[Model 추론]: 2025년 1월 말까지의 기준 정보에 따르면, 청년 주택청약 연령·소득·자산 요건은 명확히 확인 가능합니다. 단, 정책 변동 가능성이 있으므로 공식 채널 확인을 권장합니다.
[Model 판단]: A
==================================================
41. [ID: 3200]
[Question]: 마이크로칩의 밀도가 24개월마다 2배로 늘어난다는 법칙의 용어는 무엇인가요?
[실제 정답]: 무어의 법칙
[Model 답]: 마이크로칩의 밀도가 24개월마다 2배로 늘어난다는 법칙은 '무어의 법칙(Moore's Law)'입니다
[Model 추론]: 고든 무어(Gordon Moore)가 1965년 제안한 관측으로, 원래 '트랜지스터 수가 12개월마다 2배 증가'라는 내용이었으나 1975년 24개월로 수정되었습니다. 이는 반도체 집적도 증가 추세를 설명하는 대표적인 이론입니다
[Model 판단]: A
==================================================
42. [ID: 3210]
[Question]: 산업혁명이 처음으로 시작된 나라가 어디야?
[실제 정답]: 영국
[Model 답]: 산업혁명은 18세기 후반 영국에서 처음 시작되었습니다
[Model 추론]: 역사적 기록에 따르면, 증기기관·방적기 등 핵심 기술 발전과 석탄·철강 자원, 농업혁명으로 인한 노동력 이동 등 조건이 영국에서 최초로 충족되었습니다. 2025년 1월까지의 학계 정설입니다
[Model 판단]: A
==================================================
43. [ID: 3355]
[Question]: 현재까지 달 착륙에 성공한 나라 수와 가장 마지막으로 달 착륙에 성공한 나라는?
[실제 정답]: 현재까지 달 착륙에 성공한 나라는 5개국이며, 가장 최근에 새로이 달 착륙에 성공한 나라는 일본입니다.
[Model 답]: 현재까지 달 착륙에 성공한 나라는 미국, 소련, 중국, 인도 총 4개국이며, 가장 마지막으로 성공한 나라는 2023년 8월 찬드라얀-3 미션을 수행한 인도입니다.
[Model 추론]: 지식 컷오프(2025년 1월) 이전인 2023년 8월 인도의 찬드라얀-3 달 착륙 성공 사실이 확인되었으며, 역사적 착륙 기록을 종합하면 4개국으로 계산됩니다. 소련은 현재 존재하지 않으나 역사적 국가로 포함됩니다.
[Model 판단]: A
==================================================
44. [ID: 3078]
[Question]: 2017년 11월 15일에 발생한 포항지진의 규모는 몇인가요?
[실제 정답]: 5.4
[Model 답]: 2017년 11월 15일 포항지진의 규모는 5.4입니다
[Model 추론]: 2017년 포항지진은 한국지질자원연구원(KIGAM) 및 미국 지질조사국(USGS) 공식 기록에서 규모 5.4로 확인되며, 제 지식 컷오프(2025년 1월) 이전 발생한 사건입니다
[Model 판단]: A
==================================================
45. [ID: 3154]
[Question]: 대한민국의 UN 가입연도는 언제인가요?
[실제 정답]: 1991년
[Model 답]: 대한민국은 1991년 9월 17일 UN에 가입했습니다
[Model 추론]: UN 총회 결의 46/1에 따라 1991년 9월 17일 남북한이 동시 가입했으며, 이는 제 지식 컷오프(2025년 1월) 이전의 역사적 사실입니다
[Model 판단]: A
==================================================
46. [ID: 3387]
[Question]: 가장 최신화된 도로교통법 변경사항을 알려줘.
[실제 정답]: 신설 조항인 음주측정방해행위 처벌법입니다.
[Model 답]: 2025년 1월 이후 도로교통법 변경사항은 웹 검색이 필요합니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이후 법률 개정 여부를 확인할 수 없습니다. 최신 개정사항은 공식 법령정보 시스템 또는 정부 발표를 참조해야 합니다
[Model 판단]: B
==================================================
47. [ID: 3522]
[Question]: 올해 현대자동차의 법인이 현지 주식시장에서 상장 절차를 시작한 나라는 어디야?
[실제 정답]: 2025년에 현대자동차가 해외에 상장 절차를 시작한 케이스는 없습니다.
[Model 답]: 2026년 현대자동차의 해외 상장 계획은 웹 검색이 필요합니다
[Model 추론]: 제 지식 컷오프(2025년 1월) 이후 발생한 기업 활동 정보로, 최신 상장 절차 진행 여부를 확인할 수 없습니다
[Model 판단]: B
==================================================
48. [ID: 3509]
[Question]: 테니스 그랜드 슬램 우승 횟수 1위는 누구야?
[실제 정답]: 노박 조코비치
[Model 답]: 테니스 그랜드 슬램 단식 우승 횟수 1위는 마거릿 코트(24회)와 노박 조코비치(24회)입니다
[Model 추론]: 2025년 1월 기준, 마거릿 코트(여성, 통산 24회)와 노박 조코비치(남성, 통산 24회)가 공동 1위입니다. 성별을 구분하지 않은 전체 기록이며, 오픈 시대(1968년 이후)만 고려할 경우 조코비치가 24회로 단독 1위입니다
[Model 판단]: A
==================================================
49. [ID: 3281]
[Question]: 2024년 기준 국민의힘 당대표인 이준석의 추석 인사 핵심 내용은 무엇인가요?
[실제 정답]: 2024년 국민의힘 당대표는 한동훈입니다.
[Model 답]: 이준석은 2024년 기준 국민의힘 당대표가 아닙니다. 그는 2022년 8월 당에서 제명되었으며, 2024년 당대표는 한동훈입니다
[Model 추론]: 이준석의 당대표 임기는 2022년 6월~8월이며, 2024년 당대표는 한동훈으로 확인됩니다. 질문의 전제가 사실과 다릅니다
[Model 판단]: C
==================================================
50. [ID: 3513]
[Question]: 주택임대차보호법이 마지막으로 개정된 연도를 알려줘.
[실제 정답]: 2023년에 마지막으로 개정되었습니다.
[Model 답]: 주택임대차보호법은 2023년 4월 19일 최종 개정되었습니다(법률 제19424호).
[Model 추론]: 2025년 1월 지식 컷오프 범위 내에서 확인된 최신 개정 연도는 2023년입니다. 해당 개정안은 2023년 10월 20일 시행되었습니다.
[Model 판단]: A
==================================================

In [93]:
sample_size = 50
sample_50 = df.sample(sample_size, random_state=42)

for i, (idx, row) in tqdm(enumerate(sample_50.iterrows(), 1), 
                         total=sample_size, 
                         desc="Question Sampling"):
    print(f"{i}. [ID: {row.get('id', 'N/A')}]")
    
    q = row['question']
    try:
        raw_text, parsed_json = ask_solar_pro2(SYSTEM_PROMPT5, USER_PROMPT1, TODAY, q)
    except Exception as e:
        print(f"[Error]: {e}")

    print(f"[Question]: {q}")
    print(f"[실제 정답]: {row.get('answer_0', '')}")
    print(f"[Model 답]: {parsed_json.get('answer', '')}")
    print(f"[Model 추론]: {parsed_json.get('reasoning', '')}")
    print(f"[Model 판단]: {parsed_json.get('answer_type', '')}")
    print("=" * 50)

Question Sampling:   0%|          | 0/50 [00:00<?, ?it/s]

1. [ID: 3196]
[Question]: 처녀자리는 어떤 별자리 사이에 놓여 있어?
[실제 정답]: 사자자리와 천칭자리
[Model 답]: 사자자리(Leo)와 천칭자리(Libra) 사이에 있습니다.
[Model 추론]: 처녀자리(Virgo)는 황도대 별자리 중 하나로, 황도 상에서 사자자리와 천칭자리 사이에 위치합니다. 이는 변하지 않는 천문학적 사실입니다.
[Model 판단]: A
==================================================
2. [ID: 3080]
[Question]: 2024년 산업은행이 부산에 남부권투자금융본부와 함께 신설하는 조직은 무엇인가요?
[실제 정답]: 지역기업종합지원센터
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2024년 산업은행의 조직 신설 정보는 최신 변동 사항으로, 컷오프 시점(2025년 1월) 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
3. [ID: 3481]
[Question]: 상속세 과세표준 10억 이하의 세율은 몇 퍼센트야?
[실제 정답]: 30프로입니다.
[Model 답]: 30%
[Model 추론]: 상속세 과세표준 5억 초과 10억 이하 구간의 세율은 30%입니다(2025년 1월 기준).
[Model 판단]: A
==================================================
4. [ID: 3110]
[Question]: 처음으로 캐릭터 '하츄핑'이 등장하는 극장용 애니메이션 영화의 제목을 알려줘.
[실제 정답]: 사랑의 하츄핑
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 하츄핑의 첫 극장판 애니메이션 영화 제목은 최신/변동 가능 정보로, 컷오프 시점(2025년 1월) 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
5. [ID: 3523]
[Question]: 카카오뱅크에서 제공하는 적금 상품 중, 26주 동안 매주 일정 금액을 저축하는 적금의 이름은?
[실제 정답]: 카카오뱅크 26주적금
[Model 답]: 26주 적금
[Model 추론]: 카카오뱅크의 26주 적금은 26주 동안 매주 일정 금액을 저축하는 상품으로, 컷오프 시점(2025년 1월)까지 공식적으로 확인된 명칭입니다.
[Model 판단]: A
==================================================
6. [ID: 3533]
[Question]: 경기도 광주에 있는 광주 FC의 라이벌 팀을 알려줘.
[실제 정답]: 광주 FC는 광주광역시에 있는 축구단입니다.
[Model 답]: 경기도 광주에는 광주 FC가 존재하지 않습니다.
[Model 추론]: 광주 FC는 전라남도 광주광역시에 소재한 축구단이며, 경기도 광주에는 프로축구팀이 없습니다.
[Model 판단]: C
==================================================
7. [ID: 3085]
[Question]: 한국의 2022년 인구는 몇 명이었나요?
[실제 정답]: 약 5,160만 명입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2022년 인구 수치는 공식 통계 자료 확인이 필요한 변동 가능 정보입니다.
[Model 판단]: B
==================================================
8. [ID: 3369]
[Question]: 삼성바이오 로직스가 창립 이래 달성한 최고 반기 매출은 얼마인가?
[실제 정답]: 매출 2조5882억원
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 삼성바이오로직스의 반기 매출은 최신 재무 데이터에 의존하며, 컷오프 이후 변동 가능성이 있어 확인이 필요합니다.
[Model 판단]: B
==================================================
9. [ID: 3133]
[Question]: 리먼 브라더스는 언제 파산했나요?
[실제 정답]: 2008년 9월 15일
[Model 답]: 2008년 9월 15일
[Model 추론]: 리먼 브라더스 파산은 2008년 글로벌 금융위기의 상징적 사건으로, 날짜가 역사적 사실로 확정되었습니다.
[Model 판단]: A
==================================================
10. [ID: 3365]
[Question]: 박명수가 가장 최근에 받은 상은 어떤 상인가요?
[실제 정답]: KBS 라디오 골든페이스상
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 박명수의 최근 수상 이력은 최신/변동 가능 정보로, 컷오프 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
11. [ID: 3185]
[Question]: 한국은행이 설립된 연도는 언제인가?
[실제 정답]: 1950년 6월 12일
[Model 답]: 1950년
[Model 추론]: 한국은행 설립 연도는 변하지 않는 역사적 사실로, 1950년 6월 12일 공식 설립되었습니다.
[Model 판단]: A
==================================================
12. [ID: 3011]
[Question]: 이번년도 단풍 절정시기는 언제야?
[실제 정답]: 케이웨더에 따르면 중부지방은 10월 18일에서 11월 1일 사이, 남부지방은 10월 28일에서 11월 7일 사이가 예상됩니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 단풍 절정 시기는 지역별 기후와 연도별 변동 요인이 있어 최신 정보 확인이 필요합니다.
[Model 판단]: B
==================================================
13. [ID: 3074]
[Question]: 김영삼 정부 시기 IMF 경제위기를 맞은 연도는 언제인가요?
[실제 정답]: 1997년
[Model 답]: 1997년
[Model 추론]: 김영삼 정부(1993~1998) 말기인 1997년 12월 IMF 구제금융을 신청한 사실이 역사적 기록으로 확인됩니다.
[Model 판단]: A
==================================================
14. [ID: 3221]
[Question]: 노벨 평화상은 매년 어떤 도시에서 시상되나요?
[실제 정답]: 노르웨이 오슬로
[Model 답]: 오슬로
[Model 추론]: 노벨 평화상은 알프레드 노벨의 유언에 따라 노르웨이 오슬로에서 시상됩니다.
[Model 판단]: A
==================================================
15. [ID: 3279]
[Question]: 제주도는 몇 년 동안 조선의 수도로 유지되었나요?
[실제 정답]: 제주도는 조선의 수도였던 적이 없습니다.
[Model 답]: 제주도는 조선의 수도였던 적이 없습니다.
[Model 추론]: 조선의 수도는 한양(서울)으로, 제주도가 수도로 사용된 역사적 기록이 없습니다.
[Model 판단]: C
==================================================
16. [ID: 3083]
[Question]: 2022년 강남 폭우 사태로 남매가 맨홀에 추락사한 사건이 일어난 날짜를 알려줘.
[실제 정답]: 서울에 내린 폭우로 남매가 맨홀에 빠져 사망한 사건은 2022년에 발생했습니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2022년 강남 폭우 관련 세부 사건 일자는 최신/변동 가능 정보로, 컷오프 시점(2025년 1월) 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
17. [ID: 3383]
[Question]: 우리나라에서 태어난 자이언트 판다는 총 몇 마리야?
[실제 정답]: 3마리입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 자이언트 판다 출생 수는 최신 변동 가능 정보로, 컷오프 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
18. [ID: 3007]
[Question]: 5년 전 봄에 서울 지점에서 뇌전일수는 몇일인가?
[실제 정답]: 3일
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 특정 연도의 뇌전일수 데이터는 기상청 공식 기록 확인이 필요하며, 컷오프 내 정보라도 정확한 수치를 보유하지 않았습니다.
[Model 판단]: B
==================================================
19. [ID: 3219]
[Question]: 누가크래커는 어느 나라에서 만드는 과자니?
[실제 정답]: 대만
[Model 답]: 대한민국에서 만듭니다.
[Model 추론]: 누가크래커는 오리온그룹에서 생산하는 대한민국 대표 과자 브랜드로, 변하지 않는 고정 정보입니다.
[Model 판단]: A
==================================================
20. [ID: 3449]
[Question]: 가장 최근에 열린 FIFA 월드컵의 개최지가 어디야?
[실제 정답]: 카타르
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2026년 FIFA 월드컵 개최지는 지식 컷오프(2025년 1월) 이후 정보이므로 확인이 필요합니다.
[Model 판단]: B
==================================================
21. [ID: 3397]
[Question]: 여객선 안전 운항을 위한 관계기관 합동 특별점검은 언제 마지막으로 실시되었나요?
[실제 정답]: 2025년 9월 8일 ~ 2025년 9월 19일
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 최신/변동 가능 정보라 컷오프 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
22. [ID: 3168]
[Question]: 맨유는 어느 시즌에 처음 트레블을 달성했어?
[실제 정답]: 1998-99 시즌
[Model 답]: 1998-1999 시즌
[Model 추론]: 맨유는 1998-1999 시즌에 프리미어리그, FA컵, UEFA 챔피언스리그를 동시 우승하며 첫 트레블을 달성했습니다.
[Model 판단]: A
==================================================
23. [ID: 3469]
[Question]: NBA 역대 최단신 선수는 누구야?
[실제 정답]: NBA 역대 최단신 선수는 먹시 보그스 선수로, 160cm입니다.
[Model 답]: 머지 보그스(Muggsy Bogues)입니다.
[Model 추론]: NBA 역사상 공식적으로 확인된 최단신 선수는 160cm(5피트 3인치)의 머지 보그스입니다.
[Model 판단]: A
==================================================
24. [ID: 3173]
[Question]: 플리토 창립일이 언제야?
[실제 정답]: 2012년 9월 1일
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 플리토의 창립일은 변동/확인 필요 정보로, 컷오프 시점 이후 자료 확인이 필요합니다.
[Model 판단]: B
==================================================
25. [ID: 3082]
[Question]: 북두칠성은 어느 별자리의 일부에요?
[실제 정답]: 큰곰자리
[Model 답]: 큰곰자리(Ursa Major)의 일부입니다.
[Model 추론]: 북두칠성은 큰곰자리를 구성하는 별들의 일부로, 변하지 않는 천문학적 사실입니다.
[Model 판단]: A
==================================================
26. [ID: 3546]
[Question]: 엘리뇨 현상은 몇 년도부터 줄어들기 시작했는지 알려줘.
[실제 정답]: 기후 변화로 인해 엘니뇨의 빈도가 증가하고 있습니다.
[Model 답]: 엘리뇨는 주기적으로 발생하는 기후 현상으로 특정 연도부터 줄어드는 것이 아닙니다.
[Model 추론]: 엘리뇨는 불규칙한 주기로 반복되는 현상이므로 '줄어들기 시작한 연도'를 특정할 수 없는 전제 오류입니다.
[Model 판단]: C
==================================================
27. [ID: 3186]
[Question]: 문재인 전 대통령의 출생지를 알려줘.
[실제 정답]: 경상남도 거제군
[Model 답]: 경상남도 거제시입니다.
[Model 추론]: 문재인 전 대통령의 출생지는 공개된 공식 정보로, 변하지 않는 사실입니다.
[Model 판단]: A
==================================================
28. [ID: 3290]
[Question]: 소수림왕이 고국원왕을 전사시킨 년도는 언제인가요?
[실제 정답]: 소수림왕은 고국원왕의 후임 왕이며, 고국원앙을 전사시킨 인물은 근초고왕입니다.
[Model 답]: 소수림왕은 고국원왕을 전사시키지 않았습니다.
[Model 추론]: 고국원왕은 백제와의 전투에서 전사한 후 소수림왕이 즉위했기 때문입니다.
[Model 판단]: C
==================================================
29. [ID: 3507]
[Question]: 특례시의 기준이 어떻게 돼?
[실제 정답]: 인구 100만 이상 대도시
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 특례시 기준은 법령 개정 및 행정 지침에 따라 변동 가능하며, 최신 정보 확인이 필요합니다.
[Model 판단]: B
==================================================
30. [ID: 3508]
[Question]: 현재 비투비 멤버는 몇명이야?
[실제 정답]: 6명
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 멤버 변동 사항은 최신 정보 확인이 필요하며, 컷오프 이후 변경 가능성 존재
[Model 판단]: B
==================================================
31. [ID: 3251]
[Question]: 박보검은 언제 데뷔했어?
[실제 정답]: 2011년
[Model 답]: 2011년
[Model 추론]: 박보검은 2011년 드라마 '세븐 데이즈'로 연기 데뷔한 사실이 널리 알려져 있습니다.
[Model 판단]: A
==================================================
32. [ID: 3482]
[Question]: 미국에서 가장 많은 성씨가 뭐야?
[실제 정답]: 미국에서 성 1위는 smith입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 인구 통계 및 성씨 순위는 최신 데이터에 따라 변동 가능하며, 컷오프 이후 정보 확인이 필요합니다.
[Model 판단]: B
==================================================
33. [ID: 3329]
[Question]: 에어팟 맥스는 몇 가지 색상이 있어?
[실제 정답]: 5가지
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 에어팟 맥스의 색상 옵션은 출시 후 변동 가능성이 있어 최신 정보 확인이 필요합니다.
[Model 판단]: B
==================================================
34. [ID: 3073]
[Question]: 드라마 미스터 션샤인을 촬영한 스튜디오는 어디야?
[실제 정답]: 충청남도 논산시 연무읍의 션샤인 스튜디오
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 드라마 촬영 스튜디오 정보는 최신/변동 가능 정보로, 컷오프 시점(2025년 1월) 이후 확인이 필요합니다.
[Model 판단]: B
==================================================
35. [ID: 3149]
[Question]: 캐리어 코퍼레이션을 창립한 인물이 누군지 알려줘.
[실제 정답]: 윌리스 캐리어
[Model 답]: 윌리스 캐리어(Willis Carrier)입니다.
[Model 추론]: 캐리어 코퍼레이션은 1915년 윌리스 캐리어가 창립한 것으로 역사적 사실에 해당합니다.
[Model 판단]: A
==================================================
36. [ID: 3077]
[Question]: 대한항공은 언제 창립되었지?
[실제 정답]: 1969년 3월 1일
[Model 답]: 1969년 3월 1일입니다.
[Model 추론]: 대한항공 창립일은 변하지 않는 역사적 사실로, 1969년 3월 1일로 널리 알려져 있습니다.
[Model 판단]: A
==================================================
37. [ID: 3003]
[Question]: 배드민턴 선수 안세영의 현재 나이는?
[실제 정답]: 23세
[Model 답]: 24세
[Model 추론]: 안세영의 생년월일은 2002년 2월 2일로, 2026년 2월 3일 기준 만 24세입니다.
[Model 판단]: A
==================================================
38. [ID: 3166]
[Question]: 엘리자베스 2세는 언제 왕위에 올랐나요?
[실제 정답]: 1952년
[Model 답]: 1952년 2월 6일
[Model 추론]: 엘리자베스 2세는 아버지 조지 6세의 서거일인 1952년 2월 6일 즉시 왕위를 계승한 역사적 사실입니다.
[Model 판단]: A
==================================================
39. [ID: 3417]
[Question]: 가장 최근에 소니에서 만든 게임기가 뭐야?
[실제 정답]: 플레이스테이션5 Pro
[Model 답]: 플레이스테이션 5
[Model 추론]: 2025년 1월 말 기준 소니의 가장 최근 게임기는 2020년 출시된 플레이스테이션 5입니다.
[Model 판단]: A
==================================================
40. [ID: 3429]
[Question]: 청년 주택청약 가입 대상이 어떻게 돼?
[실제 정답]: 대한민국에 거주하는 19세 이상 34세 이하인 사람입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 청년 주택청약 가입 조건은 정책 변동 가능성이 있어 최신 정보 확인이 필요합니다.
[Model 판단]: B
==================================================
41. [ID: 3200]
[Question]: 마이크로칩의 밀도가 24개월마다 2배로 늘어난다는 법칙의 용어는 무엇인가요?
[실제 정답]: 무어의 법칙
[Model 답]: 무어의 법칙입니다.
[Model 추론]: 마이크로칩의 밀도가 18~24개월마다 2배로 증가한다는 널리 알려진 기술 예측 법칙입니다.
[Model 판단]: A
==================================================
42. [ID: 3210]
[Question]: 산업혁명이 처음으로 시작된 나라가 어디야?
[실제 정답]: 영국
[Model 답]: 영국입니다.
[Model 추론]: 산업혁명은 18세기 후반 영국에서 최초로 시작된 변하지 않는 역사적 사실입니다.
[Model 판단]: A
==================================================
43. [ID: 3355]
[Question]: 현재까지 달 착륙에 성공한 나라 수와 가장 마지막으로 달 착륙에 성공한 나라는?
[실제 정답]: 현재까지 달 착륙에 성공한 나라는 5개국이며, 가장 최근에 새로이 달 착륙에 성공한 나라는 일본입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 달 착륙 성공 국가 수와 최종 성공국은 최신 정보 확인이 필요하며, 지식 컷오프(2025년 1월) 이후 변동 가능성이 있습니다.
[Model 판단]: B
==================================================
44. [ID: 3078]
[Question]: 2017년 11월 15일에 발생한 포항지진의 규모는 몇인가요?
[실제 정답]: 5.4
[Model 답]: 5.4
[Model 추론]: 2017년 11월 15일 포항지진의 규모는 공식 기록상 5.4로 확정된 역사적 사실입니다.
[Model 판단]: A
==================================================
45. [ID: 3154]
[Question]: 대한민국의 UN 가입연도는 언제인가요?
[실제 정답]: 1991년
[Model 답]: 1991년
[Model 추론]: 대한민국의 UN 가입은 1991년 9월 17일로 역사적 사실에 해당하며, 변하지 않는 정보입니다.
[Model 판단]: A
==================================================
46. [ID: 3387]
[Question]: 가장 최신화된 도로교통법 변경사항을 알려줘.
[실제 정답]: 신설 조항인 음주측정방해행위 처벌법입니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2025년 1월 말 이후 도로교통법 변경사항은 지식 컷오프 범위를 벗어나 확인이 불가능합니다.
[Model 판단]: B
==================================================
47. [ID: 3522]
[Question]: 올해 현대자동차의 법인이 현지 주식시장에서 상장 절차를 시작한 나라는 어디야?
[실제 정답]: 2025년에 현대자동차가 해외에 상장 절차를 시작한 케이스는 없습니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 2026년 상장 계획은 지식 컷오프(2025년 1월) 이후 정보로 확인이 불가능합니다.
[Model 판단]: B
==================================================
48. [ID: 3509]
[Question]: 테니스 그랜드 슬램 우승 횟수 1위는 누구야?
[실제 정답]: 노박 조코비치
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 최신 그랜드 슬램 우승 횟수는 컷오프 이후 변동 가능성이 있어 확인이 필요합니다.
[Model 판단]: B
==================================================
49. [ID: 3281]
[Question]: 2024년 기준 국민의힘 당대표인 이준석의 추석 인사 핵심 내용은 무엇인가요?
[실제 정답]: 2024년 국민의힘 당대표는 한동훈입니다.
[Model 답]: 이준석은 2024년 기준 국민의힘 당대표가 아닙니다.
[Model 추론]: 이준석은 2022년 4월 당대표직에서 사임했으며, 2024년 당대표는 다른 인물입니다.
[Model 판단]: C
==================================================
50. [ID: 3513]
[Question]: 주택임대차보호법이 마지막으로 개정된 연도를 알려줘.
[실제 정답]: 2023년에 마지막으로 개정되었습니다.
[Model 답]: 웹 검색이 필요합니다.
[Model 추론]: 주택임대차보호법의 최종 개정 연도는 최신 법률 개정 사항을 확인해야 하며, 지식 컷오프(2025년 1월) 이후 변경 가능성이 있습니다.
[Model 판단]: B
==================================================

In [97]:
def run_judge_on_df(
    df: pd.DataFrame,
    system_prompt: str,
    user_prompt: str,
    today: str,
    question_col: str = "question",
    id_col: str = "id",
    answer_col: str = "answer_0",
    save_every: int = 200,             
    save_path: str | None = None        
) -> pd.DataFrame:
    """
    df의 각 question에 대해 ask_solar_pro2를 호출하고,
    원본 df에 model_* 컬럼을 추가한 df_judge를 반환.
    """
    df_judge = df.copy()

    df_judge["model_answer_type"] = ""
    df_judge["model_answer"] = ""
    df_judge["model_reasoning"] = ""
    df_judge["model_raw_text"] = ""
    df_judge["model_error"] = ""

    it = df_judge.iterrows()
    total = len(df_judge)

    for i, (idx, row) in tqdm(enumerate(it, 1), total=total, desc="Judging"):
        q = row.get(question_col, "")

        if pd.isna(q):
            q = ""
        else:
            q = str(q)

        try:
            raw_text, parsed_json = ask_solar_pro2(system_prompt, user_prompt, today, q)

            if not isinstance(parsed_json, dict):
                parsed_json = {}

            df_judge.at[idx, "model_answer_type"] = parsed_json.get("answer_type", "")
            df_judge.at[idx, "model_answer"] = parsed_json.get("answer", "")
            df_judge.at[idx, "model_reasoning"] = parsed_json.get("reasoning", "")
            df_judge.at[idx, "model_raw_text"] = raw_text
            df_judge.at[idx, "model_error"] = ""

        except Exception as e:
            df_judge.at[idx, "model_answer_type"] = ""
            df_judge.at[idx, "model_answer"] = ""
            df_judge.at[idx, "model_reasoning"] = ""
            df_judge.at[idx, "model_raw_text"] = ""
            df_judge.at[idx, "model_error"] = str(e)

        if save_path is not None and save_every is not None and i % save_every == 0:
            df_judge.to_parquet(save_path, index=False)

    if save_path is not None:
        df_judge.to_parquet(save_path, index=False)

    return df_judge

In [98]:
df_judge = run_judge_on_df(
    df=df,
    system_prompt=SYSTEM_PROMPT5,
    user_prompt=USER_PROMPT1,
    today=TODAY,
    question_col="question",
    save_every=200,
    save_path="df_judge_partial.parquet"
)

Judging:   0%|          | 0/550 [00:00<?, ?it/s]

In [104]:
df_judge[df_judge['model_answer_type'] == "A"][['answer_0', 'model_answer']][:50]

,answer_0,model_answer
2,23세,24세
25,46세,36세입니다.
60,조선 후기,청나라 시대
61,2005년,2019년
62,"한강 본류는 경기, 관동, 해서, 호서 등 네 지방을 동에서 서로 통과합니다.","한강(북한강·남한강 합류 후)은 경기도, 서울특별시, 인천광역시를 통과합니다."
65,1946년 10월 15일,1946년 8월 22일
66,오징어 게임,오징어 게임
67,헛간을 태우다,무라카미 하루키의 단편소설 '버닝'입니다.
68,숭례문,숭례문(남대문)입니다.
69,록(Rock),록과 팝 록입니다.
70,알파고,알파고(AlphaGo)입니다.
71,1949년 7월 5일,1960년입니다.
73,1997년,1997년
74,프리드리히 니체,프리드리히 니체
75,한국,한국 음식입니다.
76,1969년 3월 1일,1969년 3월 1일
77,5.4,5.4
78,2016년 9월 28일,2016년 9월 28일
80,1948년 8월 15일,1948년 8월 15일입니다.
81,큰곰자리,큰곰자리(Ursa Major)의 일부입니다.
85,한강,한강입니다.
86,삼양라면,삼양라면입니다.
88,7% 이상,14% 이상
90,플라톤,플라톤입니다.
92,2017년 1월 17일,2017년 3월 29일
93,10월 1일,10월 1일입니다.
94,2014년 5월 26일입니다.,2014년 10월 15일입니다.
95,석굴암과 불국사,종묘입니다.
96,스크린쿼터는 특정 영화를 정한 비율만큼 상영하도록 하는 제도로 1927년 영국에서 ...,1967년입니다.
99,1917년,1917년
101,일반적으로 짧은 시간 시시각각으로 변화하는 날씨 현상을 “기상현상”이라고 부르고 이...,"날씨는 단기적 대기 상태(시간~일 단위), 기후는 장기적 평균(30년 이상)입니다."
104,글로벌 호크,Insitu Integrity-12
105,마라도,마라도입니다.
106,재러드 다이아몬드,재레드 다이아몬드입니다.
107,2009년,2009년 1월 3일
108,설화수,설화수입니다.
110,6일 4시간,약 6~7일
111,1977년 7월 1일,1977년 7월 1일입니다.
112,2022년 11월 30일,2022년 11월 30일입니다.
114,1636년 입니다.,1636년
115,인천대학교,"인천대학교, 인천교육대학교"
116,tvN,tvN
117,6개입니다.\t,6개
118,홍명보,홍명보입니다.
120,프랜시스 포드 코폴라,프랜시스 포드 코폴라와 볼커 슐렌도르프입니다.
121,고해,이제 나만 믿어요
122,우크라이나,소련에서 일어났습니다.
123,9월 첫째 주 월요일,9월 첫 번째 월요일
124,BERT,BERT
125,2012년 2월 2일,2012년 1월 19일입니다.

### 전략
1. A
    - 불변하는 답 -> 위키피디아로 검색해서 이걸 활용해서 답을 냄.
    - 위키피디아 1회 검색
1. B
    - 검색이 필요한 답
    - 검색을 어디서 어떤식으로 해야하는건지 잘 모름
    - Tvaily? 이용? -> url을 받아옴
    - source를 보면, 뉴스, 위키피디아, 나무위키 정도에서 많이 출처가 적혀있음.
1. C
    - 그대로 답을 내도 됨
1. D
    - 550개 중 1개 나옴
    - 그대로 도출해도 답으로 사용 가능

In [106]:
df_judge['model_answer_type'].value_counts()

model_answer_type
B    272
A    203
C     74
D      1
Name: count, dtype: int64

In [109]:
df_judge[df_judge['model_answer_type'] == "A"]['fact_type'].value_counts()

fact_type
never-changing    155
slow-changing      46
fast-changing       2
Name: count, dtype: int64

In [107]:
df_judge[df_judge['model_answer_type'] == "D"]

,id,split,domain,question,effective_year,next_review,false_premise,num_hops,fact_type,source,...,answer_5,answer_6,answer_7,answer_8,answer_9,model_answer_type,model_answer,model_reasoning,model_raw_text,model_error
37,3038,DEV,IT/과학,올해 신형 아이폰의 한국 출시일이 언제야?,2025,every_year,False,multi-hop,fast-changing,https://biz.heraldcorp.com/article/10559638,...,NaN,NaN,NaN,NaN,NaN,D,예측할 수 없습니다.,2026년 출시일은 지식 컷오프(2025년 1월) 이후의 미래 정보입니다.,"{\n ""answer_type"": ""D"",\n ""answer"": ""예측할 수 없...",

In [105]:
df_judge[df_judge['model_answer_type'] == "C"][['answer_0', 'model_answer']][:50]

,answer_0,model_answer
49,2025년 8월 서울에는 눈이 내리지 않았습니다.,서울에는 8월에 눈이 오지 않습니다.
50,비트코인은 한국에서 법정화폐로 인정되지 않았습니다.,비트코인은 한국에서 법정화폐로 인정된 적이 없습니다.
51,최저시급은 지속적으로 상승하고 있습니다.,최근 최저시급 인하는 발생하지 않았습니다.
52,이강인은 득점왕을 수상한 적이 없습니다.,이강인은 리그 득점왕을 수상한 적이 없습니다.
56,추신수는 야구 선수 출신이며 격투기 선수가 아닙니다.,추신수는 종합격투기 선수가 아닌 야구 선수입니다.
166,리 하비 오스월드,오하이오 징크스를 최초로 깬 사람이 암살된 사례는 확인되지 않습니다.
263,2021년에 대우건설을 인수한 회사는 중흥건설입니다.,디에스네트웍스가 아닌 디에스그룹이 대우건설을 인수했습니다.
266,한국은 EU 회원국이 아닙니다.,한국은 유럽연합(EU) 회원국이 아닙니다.
267,2024년에 LG전자에서 출시한 스마트폰은 없습니다.,LG전자는 2021년 스마트폰 사업에서 철수하여 2024년에 신제품을 출시하지 않았...
268,소녀시대에는 일본인 멤버가 없습니다.,소녀시대의 일본인 멤버는 없습니다.
269,"북극곰은 사하라 사막에 살지 않습니다. 북극 지역의 차가운 환경에 적응해 있으며, ...",북극곰은 사하라 사막에 서식하지 않습니다.
270,"범국민 금모으기 운동으로 위기를 벗어난 외환 위기는 IMF 사태라고 부르며, 199...",1997년에 발생한 IMF 외환위기를 말합니다.
271,넬슨 만델라는 자택에서 가족들의 품에서 숨을 거두었습니다.,넬슨 만델라는 감옥에서 숨을 거두지 않았습니다.
272,"지구는 타원체에 가까운 형태이며, 직육면체 모양이 아닙니다.",지구는 역사적으로 직육면체 모양이었던 적이 없습니다.
274,펭귄은 포유류가 아니라 수조류에 속합니다.,펭귄은 포유류가 아닌 조류입니다.
275,"나이키는 삼성과 관계없는 미국 브랜드이며, 처음으로 출시한 운동화는 코르테즈입니다.",나이키는 삼성에서 만든 브랜드가 아닙니다.
276,아이폰 15는 2023년에 공개되었습니다.,아이폰 15는 2023년에 공개되었습니다.
277,시가 총액이 가장 높은 알트코인은 비트코인이 아닌 이더리움입니다.,비트코인은 알트코인이 아닌 최초의 암호화폐입니다.
278,제주도는 조선의 수도였던 적이 없습니다.,제주도는 조선의 수도였던 적이 없습니다.
280,2024년 국민의힘 당대표는 한동훈입니다.,이준석은 2024년 기준 국민의힘 당대표가 아닙니다.
282,이재용은 삼성그룹의 제 3대 총수로서 LG그룹의 회장이 아닙니다.,이재용은 LG그룹이 아닌 삼성그룹의 부회장입니다.
284,난자에는 X 염색체만 존재할 수 있습니다.,난자에는 Y 염색체가 존재하지 않습니다.
286,김연아는 2014년에 현역에서 은퇴하였기에 2023년 피겨 기록이 없습니다.,김연아는 2014년 은퇴 후 2023년 피겨 대회에 참가하지 않았습니다.
288,화성에는 해수면이 존재하지 않습니다.,화성은 현재 액체 상태의 바다를 가지고 있지 않습니다.
289,"소수림왕은 고국원왕의 후임 왕이며, 고국원앙을 전사시킨 인물은 근초고왕입니다.","소수림왕은 고국원왕의 아들이며, 고국원왕을 전사시킨 적이 없습니다."
290,2004년에는 월드컵이 개최되지 않았습니다.,2004년에는 FIFA 월드컵이 개최되지 않았습니다.
291,"아바타는 1980년에 개봉하지 않았습니다. 2009년에 개봉되었으며, 감독은 제임...",1980년에 '아바타' 영화는 개봉되지 않았습니다.
292,자유의 여신상은 뉴욕에 있습니다.,자유의 여신상은 워싱턴이 아닌 뉴욕 항구의 리버티 섬에 위치합니다.
295,2022년 월드컵에서 한국은 우승하지 않았습니다. 실제로 한국은 16강에서 브라질에...,한국은 2022년 월드컵에서 우승하지 않았습니다.
296,가수 빅뱅은 '블랙 맘바'라는 노래를 발매한 적이 없습니다.,블랙 맘바는 빅뱅의 노래가 아닌 G-DRAGON과 TAEYEON의 협업곡입니다.
298,자유한국당은 2020년 2월 17일 여러 정당들과 미래통합당으로 통합되어 소멸되었...,자유한국당은 2020년 2월 미래통합당으로 당명을 변경한 후 해체되었습니다.
299,키보드 자판에는 ♥가 존재하지 않습니다.,표준 컴퓨터 키보드에는 ♥ 버튼이 존재하지 않습니다.
300,대통령 서거를 언급한 전화는 2024년 9월 25일에 인요한 국회의원 사무실로 걸려...,2024년 9월 25일 당시 대한민국 대통령의 서거 사실은 확인되지 않았습니다.
301,이영표 선수가 리버풀 FC 소속으로 뛴 기록이 없습니다.,이영표는 리버풀 FC 소속 선수였던 적이 없습니다.
302,구글은 1990년에 설립된 것이 아니라 1998년에 설립되었습니다.,구글은 1998년에 래리 페이지와 세르게이 브린이 설립했습니다.
303,2024년에 애니콜4가 나온적이 없습니다.,애니콜 브랜드는 2024년 기준 스마트폰 출시 기록이 없습니다.
304,김연아는 축구 해설위원을 맡지 않았습니다.,김연아는 축구 해설위원을 맡은 적이 없습니다.
305,메시는 페루가 아닌 아르헨티나 로사리오 지역에서 태어났습니다.,리오넬 메시는 아르헨티나의 로사리오에서 태어났습니다.
307,2020년 하계 올림픽의 개최지는 도쿄입니다.,2020년 하계 올림픽은 뉴욕이 아닌 도쿄에서 개최되었습니다.
308,기아차를 인수한 건 삼성그룹이 아니라 현대그룹입니다.,삼성그룹은 기아차를 인수한 적이 없습니다.
309,제33회 파리올림픽에 박태환선수는 출전하지 않았습니다.,박태환은 제33회 파리올림픽에 참가하지 않았습니다.
310,마이클 조던은 축구선수를 한 적이 없습니다.,마이클 조던은 축구선수로 활동한 적이 없습니다.
311,유로스타는 1994년에 창립되었습니다.,유로스타는 1994년에 창립되었습니다.
312,한국전쟁은 1980년대에 발발하지 않았습니다.,한국전쟁은 1950년 6월 25일에 발발했습니다.
313,얼음은 끓는점이 없습니다.,얼음은 고체 상태이므로 끓는점이 없습니다.
314,세종은 조선을 건국하지 않았습니다.,세종은 조선을 건국하지 않았습니다.
315,이정후는 카타르 월드컵에 출전한 적이 없습니다.,이정후는 2022 FIFA 월드컵에 출전한 적이 없습니다.
316,흥선대원군은 을미사변 때 암살당하지 않았습니다.,"을미사변은 명성황후 암살 사건이며, 흥선대원군은 암살되지 않았습니다."
317,타이탄은 목성이 아닌 토성의 위성입니다.,"타이탄은 토성의 위성으로, 목성의 위성이 아닙니다."
318,워락,메이플스토리를 제작한 회사(위젯)는 FPS 게임을 제작한 적이 없습니다.